# Generated by Django 1.11.29 on 2022-08-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osf', '0001_initial'),
        ('addons_forward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_forward_node_settings', to='osf.AbstractNode'),
        ),
    ]
