name: 'Gen Report'
description: 'Last composite action before tests are run'
runs:
  using: "composite"
  steps:
  - name: Gen report
    uses: dorny/test-reporter@v1
    if: success() || failure()    # run this step even if previous step failed
    with:
      name: Test Report     # Name of the check run which will be created
      path: report.xml      # Path to test results
      reporter: java-junit  # Format of test results
