name: 'Generate Report'
description: 'Generate test report from junit xml file'
runs:
  using: "composite"
  steps:
  - name: Archive code coverage results
    uses: actions/upload-artifact@v4
    with:
      name: ${{github.job}} HTML REPORT
      path: report
  - name: Generate Report
    uses: dorny/test-reporter@v2
    if: success() || failure()    # run this step even if previous step failed
    with:
      name: ${{github.job}} REPORT   # Name of the check run which will be created
      path: report.xml      # Path to test results
      reporter: java-junit  # Format of test results
      max-annotations: 49
      list-tests: failed
      list-suites: failed
