# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 18:14
from __future__ import unicode_literals

from django.db import migrations


def add_http_scheme_to_gitlab_host(apps, schema_editor):
    ExternalAccount = apps.get_model('osf', 'ExternalAccount')
    gitlab_accounts = ExternalAccount.objects.filter(provider='gitlab')
    for gitlab_account in gitlab_accounts:
        if not gitlab_account.oauth_secret.startswith('https://'):
            gitlab_account.oauth_secret = 'http://{}'.format(gitlab_account.oauth_secret)
            gitlab_account.save()


def revert_add_http_scheme_to_gitlab_host(apps, schema_editor):
    ExternalAccount = apps.get_model('osf', 'ExternalAccount')
    gitlab_accounts = ExternalAccount.objects.filter(provider='gitlab')
    for gitlab_account in gitlab_accounts:
        if gitlab_account.oauth_secret.startswith('http://'):
            gitlab_account.oauth_secret = gitlab_account.oauth_secret.lstrip('http://')
            gitlab_account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('addons_gitlab', '0002_auto_20171121_1426'),
    ]

    operations = [
        migrations.RunPython(add_http_scheme_to_gitlab_host, revert_add_http_scheme_to_gitlab_host)
    ]
