# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-05-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_onedrive', '0003_rename_deleted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='drive_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
