from website.project.taxonomies import Subject

from rest_framework import generics, permissions as drf_permissions

from api.taxonomies.serializers import TaxonomySerializer
from api.base.views import JSONAPIBaseView
from modularodm import Q


class PlosTaxonomy(JSONAPIBaseView, generics.ListAPIView):
    '''[PLOS taxonomy of subjects](http://journals.plos.org/plosone/browse/) in flattened form. *Read-only*

    ##Taxonomy Attributes

        name           type                   description
        ----------------------------------------------------------------------------
        data           array of subjects      List of subjects

    Each subject is represented by an object with the following fields:

    * `id` - autogenerated id of subject
    * `text` - a string that is the subject itself
    * `parent_ids` - ids of parent subjects
    * `type` - in this case the string `'plos'`

    **Note:** Subjects are unique (e.g. there exists only one object in this list with `text='Biology and life sciences'`),
    but as per the structure of the PLOS taxonomy, subjects can exist in separate paths down the taxonomy and as such
    can have multiple parent subjects.

    Only the top three levels of the PLOS taxonomy are included.
    '''
    permission_classes = (
        drf_permissions.IsAuthenticatedOrReadOnly,
    )

    serializer_class = TaxonomySerializer
    view_category = 'plos-taxonomies'
    view_name = 'plos-taxonomy'

    # overrides ListAPIView
    def get_queryset(self):
        return Subject.find(
            Q('type', 'eq', 'plos')
        )
