# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import location, institutional_storage, management, restore, export

urlpatterns = [
    # to register export data storage location
    url(r'^storage_location/$',
        location.ExportStorageLocationView.as_view(),
        name='export_data_storage_location'),
    url(r'^storage_location/institutions/$',
        location.ExportStorageLocationInstitutionListView.as_view(),
        name='export_data_storage_location_institution_list'),
    url(r'^storage_location/institutions/(?P<institution_id>[0-9]+)/$',
        location.ExportStorageLocationView.as_view(),
        name='export_data_storage_location_institution'),
    url(r'^storage_location/(?P<location_id>[0-9]+)/delete/$',
        location.DeleteCredentialsView.as_view(),
        name='export_data_delete_credentials'),
    url(r'^storage_location/(?P<location_id>[0-9]+)/delete/(?P<institution_id>[0-9]+)$',
        location.DeleteCredentialsView.as_view(),
        name='export_data_delete_credentials'),
    url(r'^test_connection/$',
        location.TestConnectionView.as_view(),
        name='export_data_test_connection'),
    url(r'^test_connection/(?P<institution_id>[0-9]+)$',
        location.TestConnectionView.as_view(),
        name='export_data_test_connection'),
    url(r'^save_credentials/$',
        location.SaveCredentialsView.as_view(),
        name='export_data_save_credentials'),
    url(r'^save_credentials/(?P<institution_id>[0-9]+)$',
        location.SaveCredentialsView.as_view(),
        name='export_data_save_credentials'),

    # to manage institutional storage
    url(r'^institutions/$',
        institutional_storage.ExportDataInstitutionListView.as_view(),
        name='export_data_institutions'),
    url(r'^management/institutions/$',
        institutional_storage.ExportDataListInstitutionListView.as_view(),
        name='export_data_list_institutions'),
    url(r'^institutions/(?P<institution_id>[0-9]+)/storages/$',
        institutional_storage.ExportDataInstitutionalStorageListView.as_view(),
        name='export_data_institutional_storage'),

    # to manage export data
    url(r'^$',
        management.ExportDataListView.as_view(),
        name='export_data_list'),
    url(r'^deleted/$',
        management.ExportDataDeletedListView.as_view(),
        name='export_data_deleted_list'),
    url(r'^institutions/(?P<institution_id>[0-9]+)/$',
        management.ExportDataListView.as_view(),
        name='export_data_list_institution'),
    url(r'^institutions/(?P<institution_id>[0-9]+)/deleted/$',
        management.ExportDataDeletedListView.as_view(),
        name='export_data_deleted_list_institution'),
    url(r'^institutions/(?P<institution_id>[0-9]+)/storages/(?P<storage_id>[0-9]+)/$',
        management.ExportDataListView.as_view(),
        name='export_data_institutional_storage_list'),
    url(r'^institutions/(?P<institution_id>[0-9]+)/storages/(?P<storage_id>[0-9]+)/deleted/$',
        management.ExportDataDeletedListView.as_view(),
        name='export_data_institutional_storage_deleted_list'),
    url(r'^(?P<data_id>[0-9]+)/$',
        management.ExportDataInformationView.as_view(),
        name='export_data_information'),
    url(r'^(?P<data_id>[0-9]+)/check_export_data/$',
        management.CheckExportData.as_view(),
        name='check_export_data'),
    url(r'^(?P<data_id>[0-9]+)/check_restore_data/$',
        management.CheckRestoreData.as_view(),
        name='check_restore_data'),
    url(r'^delete/$',
        management.DeleteExportDataView.as_view(),
        name='export_data_delete'),
    url(r'^revert/$',
        management.RevertExportDataView.as_view(),
        name='export_data_revert'),
    url(r'^(?P<data_id>[0-9]+)/output_csv/$',
        management.ExportDataFileCSVView.as_view(),
        name='export_data_output_csv'),

    # to export data
    url(r'^export/$',
        export.ExportDataActionView.as_view(), name='export_data_action'),
    url(r'^stop-export/$',
        export.StopExportDataActionView.as_view(), name='stop_export_data_action'),
    url(r'^check-export/$',
        export.CheckStateExportDataActionView.as_view(), name='check_state_export_data_action'),
    url(r'^check-data/$',
        export.CheckDataExportDataActionView.as_view(), name='check_data_export_data_action'),
    url(r'^check-running-export/$',
        export.CheckRunningExportActionView.as_view(), name='check_state_export_data_action'),

    # to manage restore export data storage
    url(r'^(?P<export_id>[0-9]+)/restore_export_data/$',
        restore.RestoreDataActionView.as_view(), name='restore_data_action'),
    url(r'^(?P<export_id>[0-9]+)/stop_restore_export_data/$',
        restore.StopRestoreDataActionView.as_view(), name='stop_restore_data_action'),
    url(r'^(?P<export_id>[0-9]+)/task_status/$',
        restore.CheckTaskStatusRestoreDataActionView.as_view(), name='check_task_status_restore_data_action'),
    url(r'^(?P<export_id>[0-9]+)/check_running_restore/$',
        restore.CheckRunningRestoreActionView.as_view(), name='restore_data_action'),
]
