# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 21:34
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType

import logging

logger = logging.getLogger(__file__)


def remove_web_stats_model(*args):
    try:
        ContentType.objects.get(app_label='metrics', model='osfwebsitestatistics').delete()
        migrations.DeleteModel(name='OSFWebsiteStatistics')
    except ContentType.DoesNotExist:
        pass

def replace_web_stats_model(*args):
    # reverse the removing of the contenttypes and restore the model!
    migrations.CreateModel(
        name='OSFWebsiteStatistics',
        fields=[
            ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
            ('users', models.IntegerField(default=0, verbose_name=b'OSF users')),
            ('delta_users', models.IntegerField(default=0)),
            ('unregistered_users', models.IntegerField(default=0, verbose_name=b'Unregistered users')),
            ('projects', models.IntegerField(default=0, verbose_name=b'Number of projects')),
            ('delta_projects', models.IntegerField(default=0)),
            ('public_projects', models.IntegerField(default=0, verbose_name=b'Number of public projects')),
            ('delta_public_projects', models.IntegerField(default=0)),
            ('registered_projects', models.IntegerField(default=0, verbose_name=b'Number of projects registered')),
            ('delta_registered_projects', models.IntegerField(default=0)),
            ('date', models.DateTimeField(default=None)),
        ],
    ),


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial')
    ]

    operations = [
        migrations.RunPython(remove_web_stats_model, replace_web_stats_model),
    ]
