# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OSFWebsiteStatistics',
        ),
    ]
