# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0048_auto_20170323_0841'),
    ]

    operations = [
        migrations.RunSQL(
            [
                """
                    CREATE UNIQUE INDEX osf_basefilenode_non_trashed_unique_index
                    ON public.osf_basefilenode
                    (node_id, name, parent_id, type, _path)
                    WHERE type NOT IN ('osf.trashedfilenode', 'osf.trashedfile', 'osf.trashedfolder');
                """,
            ],
            [
                """
                DROP INDEX public.osf_basefilenode_non_trashed_unique_index RESTRICT;
                """
            ]
        )
    ]
