
# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 20:20
from __future__ import unicode_literals
from website.app import setup_django
setup_django()

import logging

from django.db import migrations, models
from django.apps import apps

from addons.osfstorage.settings import DEFAULT_REGION_ID, DEFAULT_REGION_NAME

logger = logging.getLogger(__name__)

BATCHSIZE = 5000


def main():
    Region = apps.get_model('addons_osfstorage.region')
    FileVersion = apps.get_model('osf.fileversion')
    default_region = Region.objects.get(
        _id=DEFAULT_REGION_ID,
        name=DEFAULT_REGION_NAME,
    )
    max_pk = FileVersion.objects.aggregate(models.Max('pk'))['pk__max']
    logger.info('Max pk: {}'.format(max_pk))
    if max_pk is not None:
        for offset in range(0, max_pk + 1, BATCHSIZE):
            (FileVersion.objects
                .filter(pk__gte=offset)
                .filter(pk__lt=offset + BATCHSIZE)
                .filter(basefilenode__provider='osfstorage')
                .filter(region__isnull=True)
                .update(region=default_region))
            logger.info(
                'Updated osf_fileversions {}-{}/{}'.format(
                    offset,
                    offset + BATCHSIZE,
                    max_pk,
                )
            )


if __name__ == '__main__':
    main()
