# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('endpoint', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('info_url', models.CharField(blank=True, default=None, max_length=200)),
                ('logo_url', models.CharField(blank=True, default=None, max_length=200)),
                ('active', models.BooleanField()),
                ('admins', models.CharField(blank=True, default=None, max_length=200)),
                ('public_projects', models.BooleanField(default=True)),
                ('poster', models.BooleanField(default=True)),
                ('talk', models.BooleanField(default=True)),
                ('num_submissions', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['endpoint'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceFieldNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
            ],
        ),
    ]
