# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencefieldnames',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='conferencefieldnames',
            name='key',
        ),
        migrations.RemoveField(
            model_name='conferencefieldnames',
            name='value',
        ),
        migrations.AddField(
            model_name='conference',
            name='field_names',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.ConferenceFieldNames'),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='add_submission',
            field=models.CharField(blank=True, default='poster or talk', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='mail_attachment',
            field=models.CharField(blank=True, default='Your presentation file (e.g., PowerPoint, PDF, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='mail_message_body',
            field=models.CharField(blank=True, default='Presentation abstract (if any)', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='mail_subject',
            field=models.CharField(blank=True, default='Presentation title', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='meeting_title_type',
            field=models.CharField(blank=True, default='Posters & Talks', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='submission1',
            field=models.CharField(blank=True, default='poster', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='submission1_plural',
            field=models.CharField(blank=True, default='posters', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='submission2',
            field=models.CharField(blank=True, default='talk', max_length=200),
        ),
        migrations.AddField(
            model_name='conferencefieldnames',
            name='submission2_plural',
            field=models.CharField(blank=True, default='talks', max_length=200),
        ),
    ]
