# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_zotero', '0002_auto_20170323_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='library_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
