# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_zotero', '0003_auto_20170713_1125'),
        ('addons_zotero', '0003_nodesettings_library_id'),
    ]

    operations = [
    ]
