__all__ = (
    'DATACITE_RESOURCE_TYPES_GENERAL',
)

# controlled vocab for resourceTypeGeneral from https://schema.datacite.org/meta/kernel-4/
DATACITE_RESOURCE_TYPES_GENERAL = frozenset((
    'Audiovisual',
    'Award',
    'Book',
    'BookChapter',
    'Collection',
    'ComputationalNotebook',
    'ConferencePaper',
    'ConferenceProceeding',
    'DataPaper',
    'Dataset',
    'Dissertation',
    'Event',
    'Image',
    'Instrument',
    'InteractiveResource',
    'Journal',
    'JournalArticle',
    'Model',
    'OutputManagementPlan',
    'PeerReview',
    'PhysicalObject',
    'Preprint',
    'Project',
    'Report',
    'Service',
    'Software',
    'Sound',
    'Standard',
    'StudyRegistration',
    'Text',
    'Workflow',
    'Other',
))
