# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-02-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_weko', '0005_registrationmetadatamapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmetadatamapping',
            name='filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
