# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='suspended',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
