# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='date_modified',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
