# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import osf_models.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0002_auto_20160428_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='_affiliated_institutions',
            field=models.ManyToManyField(related_name='_node__affiliated_institutions_+', to='osf_models.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='_primary_institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_institution', to='osf_models.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='institution_auth_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='node',
            name='institution_banner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='node',
            name='institution_domains',
            field=osf_models.utils.datetime_aware_jsonfield.DatetimeAwareJSONField(default=None),
        ),
        migrations.AddField(
            model_name='node',
            name='institution_email_domains',
            field=osf_models.utils.datetime_aware_jsonfield.DatetimeAwareJSONField(default=None),
        ),
        migrations.AddField(
            model_name='node',
            name='institution_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='node',
            name='institution_logo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
