# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import osf_models.models.base
import osf_models.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', osf_models.utils.datetime_aware_jsonfield.DatetimeAwareJSONField()),
                ('guid', models.OneToOneField(default=osf_models.models.base.generate_guid_instance, on_delete=django.db.models.deletion.CASCADE, related_name='referent_collection', to='osf_models.Guid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
