# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0002_add_jsonb_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='category',
            field=models.CharField(choices=[(b'analysis', b'Analysis'), (b'communication', b'Communication'), (b'data', b'Data'), (b'hypothesis', b'Hypothesis'), (b'instrumentation', b'Instrumentation'), (b'methods and measures', b'Methods and Measures'), (b'procedure', b'Procedure'), (b'project', b'Project'), (b'software', b'Software'), (b'other', b'Other'), (b'', b'Uncategorized')], default=(b'', b'Uncategorized'), max_length=255),
        ),
    ]
