# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 20:33
from __future__ import unicode_literals

from django.db import migrations
import osf_models.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0002_auto_20160613_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_configured',
            field=osf_models.utils.datetime_aware_jsonfield.DatetimeAwareJSONField(default={}),
        ),
    ]
