# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0002_add_jsonb_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
