# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0003_auto_20160419_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
