# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0004_user__affiliated_institutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='institution_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
