# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0004_auto_20160419_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='registered_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
