# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0005_auto_20160503_1838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('_id', 'system')]),
        ),
    ]
