# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0006_auto_20160505_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelog',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='osf_models.Node'),
        ),
    ]
