# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0006_auto_20160419_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='deleted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
