# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import osf_models.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0008_auto_20160419_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.CharField(max_length=255, validators=[osf_models.models.validators.validate_title]),
        ),
    ]
