# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0009_auto_20160603_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='registration_approval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osf_models.RegistrationApproval'),
        ),
    ]
