# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import osf_models.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0009_auto_20160419_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='title',
            field=models.TextField(validators=[osf_models.models.validators.validate_title]),
        ),
    ]
