# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0010_auto_20160419_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='piwik_site_id',
            field=models.IntegerField(null=True),
        ),
    ]
