# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0010_node_registration_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embargo',
            old_name='initation_date',
            new_name='initiation_date',
        ),
        migrations.RenameField(
            model_name='registrationapproval',
            old_name='initation_date',
            new_name='initiation_date',
        ),
    ]
