# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0011_auto_20160419_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
