# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import osf_models.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0014_auto_20160421_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelog',
            name='action',
            field=models.CharField(choices=[(b'created_from', b'CREATED_FROM'), (b'project_created', b'PROJECT_CREATED'), (b'project_registered', b'PROJECT_REGISTERED'), (b'project_deleted', b'PROJECT_DELETED'), (b'node_created', b'NODE_CREATED'), (b'node_forked', b'NODE_FORKED'), (b'node_removed', b'NODE_REMOVED'), (b'pointer_created', b'POINTER_CREATED'), (b'pointer_forked', b'POINTER_FORKED'), (b'pointer_removed', b'POINTER_REMOVED'), (b'wiki_updated', b'WIKI_UPDATED'), (b'wiki_deleted', b'WIKI_DELETED'), (b'wiki_renamed', b'WIKI_RENAMED'), (b'made_wiki_public', b'MADE_WIKI_PUBLIC'), (b'made_wiki_private', b'MADE_WIKI_PRIVATE'), (b'contributor_added', b'CONTRIB_ADDED'), (b'contributor_removed', b'CONTRIB_REMOVED'), (b'contributors_reordered', b'CONTRIB_REORDERED'), (b'permissions_updated', b'PERMISSIONS_UPDATED'), (b'made_private', b'MADE_PRIVATE'), (b'made_public', b'MADE_PUBLIC'), (b'tag_added', b'TAG_ADDED'), (b'tag_removed', b'TAG_REMOVED'), (b'edit_title', b'EDITED_TITLE'), (b'edit_description', b'EDITED_DESCRIPTION'), (b'license_changed', b'CHANGED_LICENSE'), (b'updated_fields', b'UPDATED_FIELDS'), (b'addon_file_moved', b'FILE_MOVED'), (b'addon_file_copied', b'FILE_COPIED'), (b'addon_file_renamed', b'FILE_RENAMED'), (b'folder_created', b'FOLDER_CREATED'), (b'file_added', b'FILE_ADDED'), (b'file_updated', b'FILE_UPDATED'), (b'file_removed', b'FILE_REMOVED'), (b'file_restored', b'FILE_RESTORED'), (b'addon_added', b'ADDON_ADDED'), (b'addon_removed', b'ADDON_REMOVED'), (b'comment_added', b'COMMENT_ADDED'), (b'comment_removed', b'COMMENT_REMOVED'), (b'comment_updated', b'COMMENT_UPDATED'), (b'comment_restored', b'COMMENT_RESTORED'), (b'citation_added', b'CITATION_ADDED'), (b'citation_edited', b'CITATION_EDITED'), (b'citation_removed', b'CITATION_REMOVED'), (b'made_contributor_visible', b'MADE_CONTRIBUTOR_VISIBLE'), (b'made_contributor_invisible', b'MADE_CONTRIBUTOR_INVISIBLE'), (b'external_ids_added', b'EXTERNAL_IDS_ADDED'), (b'embargo_approved', b'EMBARGO_APPROVED'), (b'embargo_cancelled', b'EMBARGO_CANCELLED'), (b'embargo_completed', b'EMBARGO_COMPLETED'), (b'embargo_initiated', b'EMBARGO_INITIATED'), (b'retraction_approved', b'RETRACTION_APPROVED'), (b'retraction_cancelled', b'RETRACTION_CANCELLED'), (b'retraction_initiated', b'RETRACTION_INITIATED'), (b'registration_cancelled', b'REGISTRATION_APPROVAL_CANCELLED'), (b'registration_initiated', b'REGISTRATION_APPROVAL_INITIATED'), (b'registration_approved', b'REGISTRATION_APPROVAL_APPROVED'), (b'primary_institution_changed', b'PRIMARY_INSTITUTION_CHANGED'), (b'primary_institution_removed', b'PRIMARY_INSTITUTION_REMOVED')], db_index=True, default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodelog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 4, 22, 18, 42, 19, 100676, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodelog',
            name='foreign_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nodelog',
            name='params',
            field=osf_models.utils.datetime_aware_jsonfield.DatetimeAwareJSONField(default={}),
        ),
        migrations.AddField(
            model_name='nodelog',
            name='should_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodelog',
            name='was_connected_to',
            field=models.ManyToManyField(to='osf_models.Node'),
        ),
    ]
