# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0016_auto_20160422_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='date_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_registered',
            field=models.DateTimeField(db_index=True),
        ),
    ]
