# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0017_auto_20160422_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
