# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf_models', '0018_auto_20160422_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelog',
            name='date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
