# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 04:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorUserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('totp_secret', models.TextField(blank=True, null=True)),
                ('totp_drift', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
