# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-12 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_dropboxbusiness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodesettings',
            new_name='is_deleted',
            old_name='deleted',
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='deleted',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
    ]
