# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-15 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0080_auto_20180423_0634'),
        ('addons_dropboxbusiness', '0003_auto_20191214_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesettings',
            name='fileaccess_account',
        ),
        migrations.RemoveField(
            model_name='nodesettings',
            name='management_account',
        ),
    ]
