# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import osf.models.base
import osf.utils.fields
from reviews.permissions import GroupHelper


def create_provider_auth_groups(apps, schema_editor):
    PreprintProvider = apps.get_model('osf', 'PreprintProvider')
    for provider in PreprintProvider.objects.all():
        GroupHelper(provider).update_provider_auth_groups()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osf', '0053_auto_20170817_1056'),
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('edit_comment', 'Edit_Comment'), ('reject', 'Reject'), ('submit', 'Submit')], max_length=31)),
                ('from_state', models.CharField(choices=[('accepted', 'Accepted'), ('initial', 'Initial'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=31)),
                ('to_state', models.CharField(choices=[('accepted', 'Accepted'), ('initial', 'Initial'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=31)),
                ('comment', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', osf.utils.fields.NonNaiveDateTimeField(auto_now_add=True)),
                ('date_modified', osf.utils.fields.NonNaiveDateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='osf.PreprintService')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            create_provider_auth_groups
        )
    ]
