name: 'Start Build'
description: 'Last composite action before tests are run'
runs:
  using: "composite"
  steps:
  - id: cache-objects
    uses: actions/cache@v2
    with:
      path: ~/.cache
      key: reqs_${{ hashFiles('poetry.lock') }}
      restore-keys: reqs_
  - uses: ./.github/actions/build-es
    with:
      ELASTICSEARCH_ARCHIVE: ${{ env.ELASTICSEARCH_ARCHIVE }}
  - uses: ./.github/actions/build-es6
    with:
      ELASTICSEARCH6_ARCHIVE: ${{ env.ELASTICSEARCH6_ARCHIVE }}
  - name: Set up Python 3.12
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'
  - name: Install lxml
    shell: bash
    run: |
      sudo apt update
      sudo apt-get install libxml2-dev libxslt-dev python-dev
  - name: Copy Settings
    shell: bash
    run: |
      cp website/settings/local-travis.py website/settings/local.py
      cp api/base/settings/local-travis.py api/base/settings/local.py
      mkdir -p ~/preprints
      touch ~/preprints/index.html
  - name: PIP install
    shell: bash
    run: |
      # pinned pip to 21.0a and setuptools<58.0.0 as current dependencies do not build on newer versions of pip and setuptools
      pip install poetry==1.8.0
      poetry install --no-root --without release
  - name: Other installs
    shell: bash
    run: |
      # bumped psycopg to match requirements.txt, as otherwise build would fail
      poetry run python3 -m invoke travis-addon-settings
      pip uninstall uritemplate.py --yes
      # use yarn add --exact to match versions in yarn.lock w/o installing all deps
      yarn add --exact bower@^1.8.8
      yarn add --exact @centerforopenscience/list-of-licenses@^1.1.0
      # styles.git is a ruby project that contains a lot of useful data files. This
      # just clones the repo into bower_components, where we can access them.
      ./node_modules/.bin/bower install "https://github.com/CenterForOpenScience/styles.git#88e6ed31a91e9f5a480b486029cda97b535935d4"
