# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 00:40
from __future__ import unicode_literals

import admin.common_auth.logs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0002_osflogentry'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='osflogentry',
            managers=[
                ('objects', admin.common_auth.logs.OSFLogEntryManager()),
            ],
        ),
    ]
