# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 11:41
from __future__ import unicode_literals

import admin.common_auth.logs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0002_osflogentry'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='osflogentry',
            managers=[
                ('objects', admin.common_auth.logs.OSFLogEntryManager()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='osf_id',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
