# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0002_auto_20160223_1204'),
        ('common_auth', '0003_auto_20160427_1141'),
    ]

    operations = [
    ]
