# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_auth', '0003_auto_20160427_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='desk_token',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='myuser',
            name='desk_token_secret',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
