# Generated by Django 3.2.17 on 2023-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_s3', '0002_auto_20220817_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='bucket_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
