# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_s3', '0003_auto_20170713_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='hostname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
