# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_s3', '0004_nodesettings_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodesettings',
            old_name='hostname',
            new_name='host',
        ),
    ]
