# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_s3', '0005_auto_20180611_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesettings',
            name='host',
        ),
    ]
