# encoding: utf-8

USERNAME = None
API_KEY = None
REGION = None

PRIMARY_CONTAINER_NAME = None
PARITY_CONTAINER_NAME = None

GLACIER_VAULT = None
AWS_ACCESS_KEY = None
AWS_SECRET_KEY = None
AWS_SNS_ARN = None

AUDIT_TEMP_PATH = None
