
legacy_os_keys = {
    'IPA': 'IOS',
    'IPH': 'IOS',
    'IPD': 'IOS',
    'WIU': 'WII',
    '3DS': 'NDS',
    'DSI': 'NDS',
    'PSV': 'PSP',
    'MAE': 'SMG',
}

os_keys = {
    'AIX':  'AIX',
    'AND':  'Android',
    'AMG':  'AmigaOS',
    'ATV':  'Apple TV',
    'ARL':  'Arch Linux',
    'BTR':  'BackTrack',
    'SBA':  'Bada',
    'BEO':  'BeOS',
    'BLB':  'BlackBerry OS',
    'QNX':  'BlackBerry Tablet OS',
    'BMP':  'Brew',
    'CES':  'CentOS',
    'COS':  'Chrome OS',
    'CYN':  'CyanogenMod',
    'DEB':  'Debian',
    'DFB':  'DragonFly',
    'FED':  'Fedora',
    'FOS':  'Firefox OS',
    'BSD':  'FreeBSD',
    'GNT':  'Gentoo',
    'GTV':  'Google TV',
    'HPX':  'HP-UX',
    'HAI':  'Haiku OS',
    'IRI':  'IRIX',
    'INF':  'Inferno',
    'KNO':  'Knoppix',
    'KBT':  'Kubuntu',
    'LIN':  'Linux',
    'LBT':  'Lubuntu',
    'VLN':  'VectorLinux',
    'MAC':  'Mac OS X',
    'MAE':  'Maemo',
    'MDR':  'Mandriva',
    'SMG':  'MeeGo',
    'MCD':  'MocorDroid',
    'MIN':  'Mint',
    'MLD':  'MildWild',
    'MOR':  'MorphOS',
    'NBS':  'NetBSD',
    'MTK':  'MTK / Nucleus',
    'WII':  'Nintendo',
    'NDS':  'Nintendo Mobile',
    'OS2':  'OS/2',
    'T64':  'OSF1',
    'OBS':  'OpenBSD',
    'PSP':  'PlayStation Portable',
    'PS3':  'PlayStation',
    'RHT':  'Red Hat',
    'ROS':  'RISC OS',
    'RZD':  'RazoDroiD',
    'SAB':  'Sabayon',
    'SSE':  'SUSE',
    'SAF':  'Sailfish OS',
    'SLW':  'Slackware',
    'SOS':  'Solaris',
    'SYL':  'Syllable',
    'SYM':  'Symbian',
    'SYS':  'Symbian OS',
    'S40':  'Symbian OS Series 40',
    'S60':  'Symbian OS Series 60',
    'SY3':  'Symbian^3',
    'TDX':  'ThreadX',
    'TIZ':  'Tizen',
    'UBT':  'Ubuntu',
    'WTV':  'WebTV',
    'WIN':  'Windows <Unknown Version>',
    'W10':  'Windows 10',
    'W2K':  'Windows 2000',
    'W31':  'Windows 3.1',
    'WI7':  'Windows 7',
    'WI8':  'Windows 8',
    'W81':  'Windows 8.1',
    'W95':  'Windows 95',
    'W98':  'Windows 98',
    'WME':  'Windows ME',
    'WNT':  'Windows NT',
    'WS3':  'Windows Server 2003',
    'WVI':  'Windows Vista',
    'WXP':  'Windows XP',
    'WCE':  'Windows CE',
    'WMO':  'Windows Mobile',
    'WPH':  'Windows Phone',
    'WRT':  'Windows RT',
    'XBX':  'Xbox',
    'XBT':  'Xubuntu',
    'YNS':  'YunOs',
    'IOS':  'iOS',
    'POS':  'palmOS',
    'WOS':  'webOS'
}

browser_keys = {
    '36':  '360 Phone Browser',
    '3B':  '360 Browser',
    'AA':  'Avant Browser',
    'AB':  'ABrowse',
    'AF':  'ANT Fresco',
    'AG':  'ANTGalio',
    'AM':  'Amaya',
    'AO':  'Amigo',
    'AN':  'Android Browser',
    'AR':  'Arora',
    'AV':  'Amiga Voyager',
    'AW':  'Amiga Aweb',
    'AT':  'Atomic Web Browser',
    'BB':  'BlackBerry Browser',
    'BD':  'Baidu Browser',
    'BS':  'Baidu Spark',
    'BE':  'Beonex',
    'BJ':  'Bunjalloo',
    'BR':  'Brave',
    'BX':  'BrowseX',
    'CA':  'Camino',
    'CC':  'Coc Coc',
    'CD':  'Comodo Dragon',
    'CX':  'Charon',
    'CF':  'Chrome Frame',
    'CH':  'Chrome',
    'CI':  'Chrome Mobile iOS',
    'CK':  'Conkeror',
    'CM':  'Chrome Mobile',
    'CN':  'CoolNovo',
    'CO':  'CometBird',
    'CP':  'ChromePlus',
    'CR':  'Chromium',
    'CS':  'Cheshire',
    'DE':  'Deepnet Explorer',
    'DF':  'Dolphin',
    'DI':  'Dillo',
    'EL':  'Elinks',
    'EB':  'Element Browser',
    'EP':  'Epiphany',
    'ES':  'Espial TV Browser',
    'FB':  'Firebird',
    'FD':  'Fluid',
    'FE':  'Fennec',
    'FF':  'Firefox',
    'FL':  'Flock',
    'FW':  'Fireweb',
    'FN':  'Fireweb Navigator',
    'GA':  'Galeon',
    'GE':  'Google Earth',
    'HJ':  'HotJava',
    'IA':  'Iceape',
    'IB':  'IBrowse',
    'IC':  'iCab',
    'ID':  'IceDragon',
    'IW':  'Iceweasel',
    'IE':  'IE',
    'IM':  'IE Mobile',
    'IR':  'Iron',
    'JS':  'Jasmine',
    'JI':  'Jig Browser',
    'KI':  'Kindle Browser',
    'KM':  'K-meleon',
    'KO':  'Konqueror',
    'KP':  'Kapiko',
    'KY':  'Kylo',
    'KZ':  'Kazehakase',
    'LB':  'Liebao',
    'LG':  'LG Browser',
    'LI':  'Links',
    'LU':  'LuaKit',
    'LS':  'Lunascape',
    'LX':  'Lynx',
    'MB':  'MicroB',
    'MC':  'NCSA Mosaic',
    'ME':  'Mercury',
    'MF':  'Mobile Safari',
    'MI':  'Midori',
    'MU':  'MIUI Browser',
    'MS':  'Mobile Silk',
    'MX':  'Maxthon',
    'NB':  'Nokia Browser',
    'NO':  'Nokia OSS Browser',
    'NV':  'Nokia Ovi Browser',
    'NF':  'NetFront',
    'NL':  'NetFront Life',
    'NP':  'NetPositive',
    'NS':  'Netscape',
    'OB':  'Obigo',
    'OD':  'Odyssey Web Browser',
    'OF':  'Off By One',
    'OE':  'ONE Browser',
    'OI':  'Opera Mini',
    'OM':  'Opera Mobile',
    'OP':  'Opera',
    'ON':  'Opera Next',
    'OR':  'Oregano',
    'OV':  'Openwave Mobile Browser',
    'OW':  'OmniWeb',
    'OT':  'Otter Browser',
    'PL':  'Palm Blazer',
    'PM':  'Pale Moon',
    'PR':  'Palm Pre',
    'PU':  'Puffin',
    'PW':  'Palm WebPro',
    'PX':  'Phoenix',
    'PO':  'Polaris',
    'PS':  'Microsoft Edge',
    'QQ':  'QQ Browser',
    'RK':  'Rekonq',
    'RM':  'RockMelt',
    'SA':  'Sailfish Browser',
    'SC':  'SEMC-Browser',
    'SE':  'Sogou Explorer',
    'SF':  'Safari',
    'SH':  'Shiira',
    'SK':  'Skyfire',
    'SS':  'Seraphic Sraf',
    'SL':  'Sleipnir',
    'SM':  'SeaMonkey',
    'SN':  'Snowshoe',
    'SR':  'Sunrise',
    'SP':  'SuperBird',
    'SX':  'Swiftfox',
    'TZ':  'Tizen Browser',
    'UC':  'UC Browser',
    'VI':  'Vivaldi',
    'VB':  'Vision Mobile Browser',
    'WE':  'WebPositive',
    'WO':  'wOSBrowser',
    'WT':  'WeTab Browser',
    'YA':  'Yandex Browser',
    'XI':  'Xiino'
}
