# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-02-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldermetadata',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='storagemetadata',
            name='foldermetadata_ptr',
        ),
        migrations.RemoveField(
            model_name='storagemetadata',
            name='project',
        ),
        migrations.RenameField(
            model_name='filemetadata',
            old_name='name',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='parent',
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='folder',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_metadata', to='addons_metadata.NodeSettings'),
        ),
        migrations.DeleteModel(
            name='FolderMetadata',
        ),
        migrations.DeleteModel(
            name='StorageMetadata',
        ),
    ]
