# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-03-19 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemetadata',
            name='registered',
        ),
    ]
