# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-02-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0002_auto_20220207_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='registered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
