# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-04-10 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0002_remove_filemetadata_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
