# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-02-26 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0217_ensure_schemas'),
        ('addons_metadata', '0003_filemetadata_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationReportFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.TextField(blank=True, null=True)),
                ('default_filename', models.TextField(blank=True, null=True)),
                ('csv_template', models.TextField(blank=True, null=True)),
                ('registration_schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.RegistrationSchema')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
