# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-06-02 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0003_filemetadata_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='erad_researcher_number',
        ),
    ]
