# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-07-18 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('addons_metadata', '0012_registrationreportformat_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakenSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sync_type', models.CharField(choices=[('initial', 'Initial sync'), ('incremental', 'Incremental sync')], help_text='Synchronization processing type', max_length=20)),
                ('started_at', models.DateTimeField(help_text='Synchronization start time')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Synchronization completion time', null=True)),
                ('processed_records', models.IntegerField(default=0, help_text='Number of processed records')),
                ('errors_count', models.IntegerField(default=0, help_text='Number of errors')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], help_text='Synchronization status', max_length=10)),
                ('error_details', models.TextField(blank=True, help_text='Error details')),
                ('changelist_index', models.IntegerField(blank=True, help_text='Processed changelist index (for incremental sync)', null=True)),
                ('total_records', models.IntegerField(default=0, help_text='Total number of records after sync')),
                ('current_resourcelist_index', models.IntegerField(default=0, help_text='Current processing resourcelist index')),
                ('current_resourcelist_url', models.URLField(blank=True, help_text='URL of currently processing resourcelist', null=True)),
                ('current_resourcelist_progress', models.IntegerField(default=0, help_text='Number of processed JSON URLs in current resourcelist')),
                ('current_changelist_index', models.IntegerField(default=0, help_text='Current processing changelist index')),
                ('current_changelist_url', models.URLField(blank=True, help_text='URL of currently processing changelist', null=True)),
                ('current_changelist_progress', models.IntegerField(default=0, help_text='Number of processed changes in current changelist')),
                ('total_documents_in_batch', models.IntegerField(default=0, help_text='Total number of documents in current batch')),
                ('documents_processed_in_batch', models.IntegerField(default=0, help_text='Number of documents processed in current batch')),
            ],
            options={
                'ordering': ['-started_at'],
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AddIndex(
            model_name='kakensynclog',
            index=models.Index(fields=['status', 'completed_at'], name='addons_meta_status_57f18d_idx'),
        ),
        migrations.AddIndex(
            model_name='kakensynclog',
            index=models.Index(fields=['sync_type', 'status'], name='addons_meta_sync_ty_987f92_idx'),
        ),
    ]
