import datetime
import enum
import functools
from urllib.parse import urlsplit

import elasticsearch8.dsl as esdsl
from elasticsearch_metrics import DAILY, MONTHLY, YEARLY
import elasticsearch_metrics.imps.elastic8 as djelme

from osf.metadata.osfmap_utils import (
    osfmap_type,
    osf_iri,
    osfid_from_iri,
)
from osf.metrics.counted_usage import _get_surrounding_guids
from osf.metrics.utils import YearMonth
from osf import models as osfdb
from website import settings as website_settings


###
# custom dsl fields

class YearmonthField(esdsl.Date):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs, format='strict_year_month')

    def deserialize(self, data):
        if isinstance(data, int):
            # elasticsearch stores dates in milliseconds since the unix epoch
            _as_datetime = datetime.datetime.fromtimestamp(data // 1000)
            return YearMonth.from_date(_as_datetime)
        elif data is None:
            return None
        try:
            return YearMonth.from_any(data)
        except ValueError:
            raise ValueError(f'unsure how to deserialize "{data}" (of type {type(data)}) to YearMonth')

    def serialize(self, data):
        if isinstance(data, str):
            return data
        elif isinstance(data, YearMonth):
            return str(data)
        elif isinstance(data, (datetime.datetime, datetime.date)):
            return str(YearMonth.from_date(data))
        elif data is None:
            return None
        else:
            raise ValueError(f'unsure how to serialize "{data}" (of type {type(data)}) as YYYY-MM')


###
# inner objects for events

route_prefix_analyzer = esdsl.analyzer(
    'route_prefix_analyzer',
    tokenizer=esdsl.tokenizer('route_prefix_tokenizer', 'path_hierarchy', delimiter='.'),
)


class PageviewInfo(esdsl.InnerDoc):
    """PageviewInfo

    for CountedAuthUsage generated by viewing a web page
    """

    # fields that should be provided
    referer_url: str | None
    page_url: str | None
    page_title: str | None
    route_name: str | None = esdsl.mapped_field(esdsl.Keyword(
        fields={
            'by_prefix': esdsl.Text(analyzer=route_prefix_analyzer),
        },
    ))

    # fields auto-filled
    page_path: str | None
    referer_domain: str | None
    hour_of_day: int | None


###
# Event records

class OsfCountedUsageRecord(djelme.CountedUsageRecord):
    '''
    Aim to support a COUNTER-style reporting api
    https://cop5.projectcounter.org/en/5.1/appendices/a-glossary-of-terms.html
    https://coprd.countermetrics.org/en/1.0.1/appendices/a-glossary.html
    '''

    # inherited fields:
    #     timestamp: datetime.datetime
    #     platform_iri: str
    #     database_iri: str
    #     item_iri: str
    #     sessionhour_id: str
    #     within_iris: list[str]

    # osf-specific fields:
    item_osfid: str
    item_type: str
    item_public: bool
    provider_id: str | None
    user_is_authenticated: bool
    action_labels: list[str]
    pageview_info: PageviewInfo | None

    class Meta:
        timeseries_index_timedepth = MONTHLY

    @functools.cached_property
    def _osfid_referent(self):
        # for use by autofill methods, if needed
        return osfdb.Guid.load(self.item_osfid)

    def clean(self):
        super().clean()
        self._autofill_item_iri_and_osfid()
        self._autofill_item_public()
        self._autofill_item_type()
        self._autofill_provider_id()
        self._autofill_within_iris()
        self._autofill_pageview()
        self._autofill_database_iri()

    def _autofill_item_iri_and_osfid(self):
        if self.item_osfid and not self.item_iri:
            self.item_iri = osf_iri(self.item_osfid)
        elif self.item_iri and not self.item_osfid:
            try:
                self.item_osfid = osfid_from_iri(self.item_iri)
            except ValueError:
                pass

    def _autofill_item_public(self):
        if self.item_osfid and (self.item_public is None):
            _item = self._osfid_referent
            # if it quacks like BaseFileNode, look at .target instead
            _item = getattr(_item, 'target', None) or _item
            self.item_public = (
                _item.verified_publishable               # quacks like Preprint
                if hasattr(_item, 'verified_publishable')
                else getattr(_item, 'is_public', False)  # quacks like AbstractNode
            )

    def _autofill_item_type(self):
        if self.item_osfid and not self.item_type:
            self.item_type = osfmap_type(self._osfid_referent)

    def _autofill_provider_id(self):
        if self.item_osfid and not self.provider_id:
            _provider = getattr(self._osfid_referent, 'provider', None)
            if _provider is None:
                self.provider_id = 'osf'          # quacks like Node, Comment, WikiPage
            elif isinstance(_provider, str):
                self.provider_id = _provider      # quacks like BaseFileNode
            else:
                self.provider_id = _provider._id  # quacks like Registration, Preprint, Collection

    def _autofill_within_iris(self):
        if self.item_osfid and (self.within_iris is None) and self._osfid_referent:
            self.within_iris = [
                osf_iri(_osfid)
                for _osfid in _get_surrounding_guids(self._osfid_referent)
            ]
        # ensure inclusive "within"
        if not self.within_iris:
            self.within_iris = [self.item_iri]
        if self.item_iri not in self.within_iris:
            self.within_iris = [self.item_iri, *self.within_iris]

    def _autofill_pageview(self):
        # autofill pageview_info fields from other fields
        if self.pageview_info:
            self.pageview_info.hour_of_day = self.timestamp.hour
            _url = self.pageview_info.page_url
            if _url:
                self.pageview_info.page_path = urlsplit(_url).path.rstrip('/')
            _ref_url = self.pageview_info.referer_url
            if _ref_url:
                self.pageview_info.referer_domain = urlsplit(_ref_url).netloc

    def _autofill_database_iri(self):
        if self.item_osfid and not self.database_iri:
            _provider = getattr(self._osfid_referent, 'provider', None)
            if not _provider:
                self.database_iri = website_settings.DOMAIN
            elif isinstance(_provider, str):
                # file providers are a different thing that don't really have an iri, just an id
                self.database_iri = f'urn:files.osf.io:{self.provider_id}'
            else:
                self.database_iri = _provider.get_semantic_iri()

    def _get_unique_together_values(self):
        """get "unique together" values for "ON CONFLICT UPDATE" behavior

        override djelme.BaseDjelmeRecord._get_unique_together_values
        for more complex logic than UNIQUE_TOGETHER_FIELDS
        to slightly better approximate `counter:Double-Click Filtering`
        """
        # note: copied from osf.metrics.counted_usage._fill_document_id
        target_identifier = (
            self.pageview_info.page_url
            if self.pageview_info is not None and self.pageview_info.page_url is not None
            else self.item_osfid
        )
        # slice the day into an array of 30-second windows,
        # find this timestamp's windowslice index
        day_start = datetime.datetime(
            self.timestamp.year,
            self.timestamp.month,
            self.timestamp.day,
            tzinfo=self.timestamp.tzinfo,
        )
        time_in_seconds = (self.timestamp - day_start).total_seconds()
        time_window = int(time_in_seconds / 30)  # 30-second windows
        return (  # unique-together values:
            self.platform_iri,
            target_identifier,
            self.sessionhour_id,
            self.timestamp.date(),
            time_window,
            ','.join(sorted(self.action_labels)),
        )


class ActionLabel(enum.Enum):
    SEARCH = 'search'  # counter:Search
    VIEW = 'view'  # counter:Investigation
    DOWNLOAD = 'download'  # counter:Request
    WEB = 'web'  # counter:Regular (aka "pageview")
    API = 'api'  # counter:TDM (aka "non-web api usage")


class RegistriesModerationMetricsEs8(djelme.EventRecord):
    registration_id: str
    provider_id: str
    trigger: str
    from_state: str
    to_state: str
    user_id: str
    comment: str | None

    class Meta:
        timeseries_recordtype_name = 'RegistriesModerationMetrics'
        timeseries_index_timedepth = MONTHLY


###
# Reusable inner objects for reports

class RunningTotal(esdsl.InnerDoc):
    total: int
    total_daily: int


class FileRunningTotals(esdsl.InnerDoc):
    total: int
    public: int
    private: int
    total_daily: int
    public_daily: int
    private_daily: int


class NodeRunningTotals(esdsl.InnerDoc):
    total: int
    total_excluding_spam: int
    public: int
    private: int
    total_daily: int
    total_daily_excluding_spam: int
    public_daily: int
    private_daily: int


class RegistrationRunningTotals(esdsl.InnerDoc):
    total: int
    public: int
    embargoed: int
    embargoed_v2: int
    withdrawn: int
    total_daily: int
    public_daily: int
    embargoed_daily: int
    embargoed_v2_daily: int
    withdrawn_daily: int


class UsageByStorageAddon(esdsl.InnerDoc):
    addon_shortname: str
    enabled_usersettings: RunningTotal
    linked_usersettings: RunningTotal
    deleted_usersettings: RunningTotal
    usersetting_links: RunningTotal
    connected_nodesettings: RunningTotal
    disconnected_nodesettings: RunningTotal
    deleted_nodesettings: RunningTotal


###
# Cyclic reports


class StorageAddonUsageEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY

    usage_by_addon: list[UsageByStorageAddon]

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'StorageAddonUsage'


class DownloadCountReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY

    daily_file_downloads: int

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'DownloadCountReport'


class InstitutionSummaryReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY
    UNIQUE_TOGETHER_FIELDS = ('cycle_coverage', 'institution_id',)

    institution_id: str
    institution_name: str
    users: RunningTotal
    nodes: NodeRunningTotals
    projects: NodeRunningTotals
    registered_nodes: RegistrationRunningTotals
    registered_projects: RegistrationRunningTotals

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'InstitutionSummaryReport'


class NewUserDomainReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY
    UNIQUE_TOGETHER_FIELDS = ('cycle_coverage', 'domain_name',)

    domain_name: str
    new_user_count: int

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'NewUserDomainReport'


class NodeSummaryReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY

    nodes: NodeRunningTotals
    projects: NodeRunningTotals
    registered_nodes: RegistrationRunningTotals
    registered_projects: RegistrationRunningTotals

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'NodeSummaryReport'


class OsfstorageFileCountReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY

    files: FileRunningTotals

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'OsfstorageFileCountReport'


class PreprintSummaryReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY

    UNIQUE_TOGETHER_FIELDS = ('cycle_coverage', 'provider_key',)
    provider_key: str
    preprint_count: int

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'PreprintSummaryReport'


class UserSummaryReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = DAILY

    active: int
    deactivated: int
    merged: int
    new_users_daily: int
    new_users_with_institution_daily: int
    unconfirmed: int

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'UserSummaryReport'


class SpamSummaryReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = MONTHLY

    node_confirmed_spam: int
    node_confirmed_ham: int
    node_flagged: int
    registration_confirmed_spam: int
    registration_confirmed_ham: int
    registration_flagged: int
    preprint_confirmed_spam: int
    preprint_confirmed_ham: int
    preprint_flagged: int
    user_marked_as_spam: int
    user_marked_as_ham: int

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'SpamSummaryReport'


class InstitutionalUserReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = MONTHLY
    UNIQUE_TOGETHER_FIELDS = ('cycle_coverage', 'institution_id', 'user_id',)

    institution_id: str
    # user info:
    user_id: str
    user_name: str
    department_name: str
    month_last_login = YearmonthField()
    month_last_active = YearmonthField()
    account_creation_date = YearmonthField()
    orcid_id: str | None
    # counts:
    public_project_count: int
    private_project_count: int
    public_registration_count: int
    embargoed_registration_count: int
    published_preprint_count: int
    public_file_count: int = esdsl.mapped_field(esdsl.Long())
    storage_byte_count: int = esdsl.mapped_field(esdsl.Long())

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'InstitutionalUserReport'


class InstitutionMonthlySummaryReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = MONTHLY
    UNIQUE_TOGETHER_FIELDS = ('cycle_coverage', 'institution_id', )

    institution_id: str
    user_count: int
    public_project_count: int
    private_project_count: int
    public_registration_count: int
    embargoed_registration_count: int
    published_preprint_count: int
    storage_byte_count: int = esdsl.mapped_field(esdsl.Long())
    public_file_count: int = esdsl.mapped_field(esdsl.Long())
    monthly_logged_in_user_count: int = esdsl.mapped_field(esdsl.Long())
    monthly_active_user_count: int = esdsl.mapped_field(esdsl.Long())

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'InstitutionMonthlySummaryReport'


class PublicItemUsageReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = MONTHLY
    UNIQUE_TOGETHER_FIELDS = ('cycle_coverage', 'item_osfid')

    # where noted, fields are meant to correspond to defined terms from COUNTER
    # https://cop5.projectcounter.org/en/5.1/appendices/a-glossary-of-terms.html
    # https://coprd.countermetrics.org/en/1.0.1/appendices/a-glossary.html
    item_osfid: str
    item_type: list[str]           # counter:Data-Type
    provider_id: list[str]         # counter:Database(?)
    platform_iri: list[str]        # counter:Platform

    # view counts include views on components or files contained by this item
    view_count: int = esdsl.mapped_field(esdsl.Long())
    view_session_count: int = esdsl.mapped_field(esdsl.Long())
    cumulative_view_count: int = esdsl.mapped_field(esdsl.Long())
    cumulative_view_session_count: int = esdsl.mapped_field(esdsl.Long())

    # download counts of this item only (not including contained components or files)
    download_count: int = esdsl.mapped_field(esdsl.Long())
    download_session_count: int = esdsl.mapped_field(esdsl.Long())
    cumulative_download_count: int = esdsl.mapped_field(esdsl.Long())
    cumulative_download_session_count: int = esdsl.mapped_field(esdsl.Long())

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'PublicItemUsageReport'


class PrivateSpamMetricsReportEs8(djelme.CyclicRecord):
    CYCLE_TIMEDEPTH = MONTHLY

    node_oopspam_flagged: int
    node_oopspam_hammed: int
    node_akismet_flagged: int
    node_akismet_hammed: int
    preprint_oopspam_flagged: int
    preprint_oopspam_hammed: int
    preprint_akismet_flagged: int
    preprint_akismet_hammed: int

    class Meta:
        timeseries_index_timedepth = YEARLY
        timeseries_recordtype_name = 'PrivateSpamMetricsReport'


###
# data migration state

class Elastic6To8State(djelme.SimpleRecord):
    """index for storing values helpful for keeping track of the elastic 6->8 data migration"""
    UNIQUE_TOGETHER_FIELDS = ('key',)
    key: str
    value: str | None
    timestamp: datetime.datetime = esdsl.mapped_field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC),
    )

    @classmethod
    def get_by_key(cls, key: str):
        _response = cls.search().query({'term': {'key': key}})[0].execute()
        return _response[0] if _response else None

    @classmethod
    def get_timestamp(cls, key: str) -> datetime.datetime | None:
        _record = cls.get_by_key(key)
        return _record.timestamp if _record else None

    @classmethod
    def get_started_at(cls):
        return cls.get_timestamp('started_at')

    @classmethod
    def set_started_at_now(cls):
        _record = cls.record(key='started_at')
        cls.refresh()
        return _record.timestamp
