import datetime
import enum
import functools
from urllib.parse import urlsplit

import elasticsearch8.dsl as esdsl
from elasticsearch_metrics import MONTHLY
import elasticsearch_metrics.imps.elastic8 as djelme

from osf.metadata.osfmap_utils import osfid_from_iri
from osf.metrics.utils import (
    get_database_iri,
    get_item_type,
    get_surrounding_osfids,
)
from osf import models as osfdb
from osf.models.base import osfid_iri
from website import settings as website_settings

__all__ = (
    'OsfCountedUsageEvent',
    'RegistriesModerationEventEs8',
)


###
# inner objects for events

route_prefix_analyzer = esdsl.analyzer(
    'route_prefix_analyzer',
    tokenizer=esdsl.tokenizer('route_prefix_tokenizer', 'path_hierarchy', delimiter='.'),
)


class PageviewInfo(esdsl.InnerDoc):
    """PageviewInfo

    for OsfCountedUsageEvent generated by viewing a web page
    """

    # fields that should be provided
    referer_url: str | None
    page_url: str | None
    page_title: str | None
    route_name: str | None = esdsl.mapped_field(esdsl.Keyword(
        fields={
            'by_prefix': esdsl.Text(analyzer=route_prefix_analyzer),
        },
    ))

    # fields auto-filled
    page_path: str | None
    referer_domain: str | None
    hour_of_day: int | None


###
# Event records

class OsfCountedUsageEvent(djelme.CountedUsageRecord):
    '''
    Aim to support a COUNTER-style reporting api
    https://cop5.projectcounter.org/en/5.1/appendices/a-glossary-of-terms.html
    https://coprd.countermetrics.org/en/1.0.1/appendices/a-glossary.html
    '''
    UNIQUE_TOGETHER_FIELDS = (
        'platform_iri',
        'sessionhour_id',
        'action_labels',
        # include some non-field properties for more complex logic to
        # slightly better approximate `counter:Double-Click Filtering`
        # and allow for multiple pages describing the same item_iri
        '_page_url_or_osfid',  # non-field property
        '_timestamp_date',  # non-field property
        '_timestamp_30sec_window',  # non-field property
    )

    # inherited fields:
    #     timestamp: datetime.datetime
    #     platform_iri: str
    #     database_iri: str
    #     item_iri: str
    #     sessionhour_id: str
    #     within_iris: list[str]

    # osf-specific fields:
    item_osfid: str
    item_type: str
    item_public: bool
    provider_id: str | None
    user_is_authenticated: bool
    action_labels: list[str]
    pageview_info: PageviewInfo | None

    class Meta:
        timeseries_index_timedepth = MONTHLY

    class ActionLabel(enum.Enum):
        SEARCH = 'search'  # counter:Search
        VIEW = 'view'  # counter:Investigation
        DOWNLOAD = 'download'  # counter:Request
        WEB = 'web'  # counter:Regular (aka "pageview")
        API = 'api'  # counter:TDM (aka "non-web api usage")

    @classmethod
    def record(cls, **kwargs):
        # autofill `user_is_authenticated` before `user_id` discarded (couldn't in `clean`)
        if 'user_is_authenticated' not in kwargs:
            kwargs['user_is_authenticated'] = bool(kwargs.get('user_id'))
        return super().record(**kwargs)

    @property
    def _page_url_or_osfid(self):
        # for UNIQUE_TOGETHER_FIELDS
        return (
            self.pageview_info.page_url
            if self.pageview_info is not None and self.pageview_info.page_url is not None
            else self.item_osfid
        )

    @property
    def _timestamp_date(self):
        # for UNIQUE_TOGETHER_FIELDS
        return self.timestamp.date()

    @property
    def _timestamp_30sec_window(self):
        # for UNIQUE_TOGETHER_FIELDS
        # slice the day into an array of 30-second windows,
        # find this timestamp's windowslice index
        _day_start = datetime.datetime(
            self.timestamp.year,
            self.timestamp.month,
            self.timestamp.day,
            tzinfo=self.timestamp.tzinfo,
        )
        _time_in_seconds = (self.timestamp - _day_start).total_seconds()
        return int(_time_in_seconds / 30)  # 30-second windows

    @functools.cached_property
    def _osfid_referent(self):
        # for use by autofill methods, if needed
        _osfguid = osfdb.Guid.load(self.item_osfid)
        return _osfguid.referent if _osfguid else None

    def clean(self):
        self._autofill_platform_iri()
        self._autofill_item_iri_and_osfid()
        self._autofill_item_public()
        self._autofill_item_type()
        self._autofill_provider_id()
        self._autofill_within_iris()
        self._autofill_pageview()
        self._autofill_database_iri()
        self._clean_action_labels()
        super().clean()

    def _autofill_platform_iri(self):
        if self.platform_iri is None:
            self.platform_iri = website_settings.DOMAIN

    def _autofill_item_iri_and_osfid(self):
        if self.item_osfid and not self.item_iri:
            self.item_iri = osfid_iri(self.item_osfid)
        elif self.item_iri and not self.item_osfid:
            try:
                self.item_osfid = osfid_from_iri(self.item_iri)
            except ValueError:
                pass

    def _autofill_item_public(self):
        if self.item_osfid and (self.item_public is None):
            _item = self._osfid_referent
            # if it quacks like BaseFileNode, look at .target instead
            _item = getattr(_item, 'target', None) or _item
            self.item_public = (
                _item.verified_publishable               # quacks like Preprint
                if hasattr(_item, 'verified_publishable')
                else getattr(_item, 'is_public', False)  # quacks like AbstractNode
            )

    def _autofill_item_type(self):
        if self.item_osfid and not self.item_type:
            self.item_type = get_item_type(self._osfid_referent)

    def _autofill_provider_id(self):
        if self.item_osfid and not self.provider_id:
            _provider = getattr(self._osfid_referent, 'provider', None)
            if _provider is None:
                self.provider_id = 'osf'          # quacks like Node, Comment, WikiPage
            elif isinstance(_provider, str):
                self.provider_id = _provider      # quacks like BaseFileNode
            else:
                self.provider_id = _provider._id  # quacks like Registration, Preprint, Collection

    def _autofill_within_iris(self):
        if self.item_osfid and (not self.within_iris) and self._osfid_referent:
            self.within_iris = [
                osfid_iri(_osfid)
                for _osfid in get_surrounding_osfids(self._osfid_referent)
            ]
        # ensure inclusive "within"
        if self.item_iri not in self.within_iris:
            self.within_iris = [self.item_iri, *self.within_iris]
        self.within_iris = sorted(self.within_iris)

    def _autofill_pageview(self):
        # autofill pageview_info fields from other fields
        if self.pageview_info:
            self.pageview_info.hour_of_day = self.timestamp.hour
            _url = self.pageview_info.page_url
            if _url:
                self.pageview_info.page_path = urlsplit(_url).path.rstrip('/')
            _ref_url = self.pageview_info.referer_url
            if _ref_url:
                self.pageview_info.referer_domain = urlsplit(_ref_url).netloc

    def _autofill_database_iri(self):
        if self.item_osfid and not self.database_iri:
            self.database_iri = get_database_iri(self._osfid_referent)

    def _clean_action_labels(self):
        if self.action_labels:
            self.action_labels = sorted(self.action_labels)


class RegistriesModerationEventEs8(djelme.EventRecord):
    UNIQUE_TOGETHER_FIELDS = (
        'timestamp', 'registration_id', 'trigger', 'from_state', 'to_state', 'user_id'
    )

    registration_id: str
    provider_id: str
    trigger: str
    from_state: str
    to_state: str
    user_id: str
    comment: str | None

    class Meta:
        timeseries_recordtype_name = 'RegistriesModerationEvent'
        timeseries_index_timedepth = MONTHLY
