# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 15:44
from __future__ import unicode_literals

from bulk_update.helper import bulk_update
from osf.models import QuickFilesNode, PageCounter
from tqdm import tqdm

def noop(*args, **kwargs):
    # This is like NP hard or something
    pass

def rekey_pagecounters(state=None, schema=None):

    quickfiles = QuickFilesNode.objects.select_related('creator').exclude(files__isnull=True)

    progress_bar = tqdm(total=quickfiles.count() or 1)
    batch = []
    for i, qfn in enumerate(quickfiles, 1):
        for page_counter in PageCounter.objects.filter(_id__contains=':{}:'.format(qfn._id)):
            page_counter._id = page_counter._id.replace(qfn._id, qfn.creator._id)
            batch.append(page_counter)
        progress_bar.update(i)

    bulk_update(batch, update_fields=['_id'], batch_size=10000)

    progress_bar.close()
