# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_iqbrims', '0004_nodesettings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
