# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_iqbrims', '0005_nodesettings_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='process_definition_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
