# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import osf.models.oauth


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osf.AbstractNode'),
        ),
        migrations.AlterField(
            model_name='apioauth2application',
            name='client_secret',
            field=models.CharField(default=osf.models.oauth.generate_client_secret, max_length=40),
        ),
        migrations.AlterField(
            model_name='apioauth2personaltoken',
            name='token_id',
            field=models.CharField(default=osf.models.oauth.generate_token_id, max_length=70, unique=True),
        ),
    ]
