# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 16:59
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='extra',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict),
        ),
    ]
