# Generated by Django 3.2 on 2022-08-08 15:38

from django.db import migrations, models
import django.db.models.deletion
from django.db.utils import ProgrammingError


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except ProgrammingError as e:  # sometimes it can exist
            if 'already exists' not in str(e):
                print('Skipping as already this field was already built historically')
                pass


class Migration(migrations.Migration):
    '''
    This migration is for local setup.
    '''
    atomic = False

    dependencies = [
        ('addons_osfstorage', '0001_initial'),
        ('osf', '0001_initial'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='fileversion',
            name='region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.region'
            ),
        ),
        AddFieldIfNotExists(
            model_name='preprint',
            name='region',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='addons_osfstorage.region'
            ),
        ),
    ]
