# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            [
                """
                CREATE INDEX lowercase_tag_index ON osf_tag (lower(name), system);
                """
            ], [
                """
                DROP INDEX IF EXISTS lowercase_tag_index RESTRICT;
                """
            ]
        )
    ]
