# Generated by Django 3.2 on 2022-08-08 15:38

from django.db import migrations, models
from django.db.utils import ProgrammingError
from osf.utils.datetime_aware_jsonfield import DateTimeAwareJSONField, DateTimeAwareJSONEncoder


class AlterFieldIfNotAlready(migrations.AlterField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except ProgrammingError as e:  # sometimes it can exist
            if 'already exists' not in str(e):
                print('Skipping as already this field was already altered locally')
                pass


class Migration(migrations.Migration):
    '''
    This migration is for syncing production with the squashed db.
    '''
    atomic = False

    dependencies = [
        ('osf', '0002_cross_app_migrations'),
    ]

    operations = [
        AlterFieldIfNotAlready(
            model_name='pagecounter',
            name='action',
            field=models.CharField(
                max_length=128,
                null=True,
                blank=True
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='pagecounter',
            name='resource',
            field=models.ForeignKey(
                'osf.guid',
                related_name='pagecounters',
                null=True,
                blank=True,
                on_delete=models.CASCADE
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='pagecounter',
            name='file',
            field=models.ForeignKey(
                'osf.BaseFileNode',
                null=True,
                blank=True,
                related_name='pagecounters',
                on_delete=models.CASCADE
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='basefilenode',
            name='versions',
            field=models.ManyToManyField(
                'FileVersion',
                through='osf.BaseFileVersionsThrough'
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='basefilenode',
            name='target_content_type',
            field=models.ForeignKey(
                'contenttypes.contenttype',
                on_delete=models.CASCADE,
                blank=True,
                null=True,
                default=None
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='basefilenode',
            name='target_object_id',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                default=None
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='abstractprovider',
            name='additional_metadata_fields',
            field=DateTimeAwareJSONField(
                blank=True,
                encoder=DateTimeAwareJSONEncoder,
                null=True
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='abstractprovider',
            name='bulk_upload_auto_approval',
            field=models.BooleanField(default=False, null=True),
        ),
        AlterFieldIfNotAlready(
            model_name='abstractprovider',
            name='allow_updates',
            field=models.BooleanField(default=False, null=True),
        ),
        AlterFieldIfNotAlready(
            model_name='abstractprovider',
            name='allow_bulk_uploads',
            field=models.BooleanField(default=False, null=True),
        ),
        AlterFieldIfNotAlready(
            model_name='draftregistration',
            name='provider',
            field=models.ForeignKey(
                'RegistrationProvider',
                related_name='draft_registrations',
                null=True,
                on_delete=models.CASCADE,
                default=None,
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='subject',
            name='provider',
            field=models.ForeignKey(
                'RegistrationProvider',
                related_name='subjects',
                null=True,
                on_delete=models.CASCADE,
                default=None,
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='schemaresponse',
            name='schema',
            field=models.ForeignKey(
                'osf.RegistrationSchema',
                on_delete=models.DO_NOTHING
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='schemaresponse',
            name='initiator',
            field=models.ForeignKey(
                'osf.OsfUser',
                null=False,
                on_delete=models.DO_NOTHING
            ),
        ),
        AlterFieldIfNotAlready(
            model_name='schemaresponse',
            name='previous_response',
            field=models.ForeignKey(
                'osf.SchemaResponse',
                related_name='updated_response',
                null=True,
                blank=True,
                on_delete=models.DO_NOTHING
            ),
        ),
    ]
