# Generated by Django 3.2 on 2022-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0002_auto_20220726_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilenode',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
