# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 17:51
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0002_add_lower_index_to_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintservice',
            name='date_modified',
            field=osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now),
        ),
    ]
