# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0002_auto_20161012_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationstyle',
            name='short_title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='citationstyle',
            name='summary',
            field=models.CharField(blank=True, max_length=4200, null=True),
        ),
    ]
