# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0002_add_lower_index_to_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelManagers(
            name='fileversion',
            managers=[
                ('includable_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='preprintprovider',
            name='domain',
            field=models.CharField(blank=True, max_length=253, null=True),
        ),
    ]
