# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0004_auto_20161012_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('date', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(default=dict)),
                ('total', models.PositiveIntegerField(default=0)),
                ('unique', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivityCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('action', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(default=dict)),
                ('date', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(default=dict)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
