# Generated by Django 3.2.15 on 2022-10-27 20:07

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0004_django3_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidMetadataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('custom_metadata_bytes', models.BinaryField()),
                ('guid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_record', to='osf.guid')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.DeleteModel(
            name='FileMetadataRecord',
        ),
    ]
