# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0003_auto_20170330_1251'),
        ('osf', '0004_abstractnode_comment_level'),
    ]

    operations = [
    ]
