# Generated by Django 3.2.15 on 2022-10-31 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.workflows


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0004_django3_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsubmission',
            name='machine_state',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Unapproved'), (2, 'PendingModeration'), (3, 'Approved'), (4, 'Rejected'), (5, 'ModeratorRejected'), (6, 'Completed'), (7, 'InProgress'), (8, 'Removed')], default=osf.utils.workflows.ApprovalStates['IN_PROGRESS']),
        ),
        migrations.AlterField(
            model_name='embargo',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('removed', 'Removed')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='embargoterminationapproval',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('removed', 'Removed')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationapproval',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('removed', 'Removed')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='retraction',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('removed', 'Removed')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='schemaresponse',
            name='reviews_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('removed', 'Removed')], default='in_progress', max_length=255),
        ),
        migrations.AlterField(
            model_name='schemaresponseaction',
            name='from_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('removed', 'Removed')], max_length=31),
        ),
        migrations.AlterField(
            model_name='schemaresponseaction',
            name='to_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress'), ('removed', 'Removed')], max_length=31),
        ),
        migrations.CreateModel(
            name='CollectionSubmissionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=False)),
                ('trigger', models.IntegerField(choices=[(0, 'Submit'), (1, 'Accept'), (2, 'Reject'), (3, 'AdminRemove'), (4, 'ModeratorRemove'), (5, 'Resubmit')])),
                ('from_state', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Unapproved'), (2, 'PendingModeration'), (3, 'Approved'), (4, 'Rejected'), (5, 'ModeratorRejected'), (6, 'Completed'), (7, 'InProgress'), (8, 'Removed')])),
                ('to_state', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Unapproved'), (2, 'PendingModeration'), (3, 'Approved'), (4, 'Rejected'), (5, 'ModeratorRejected'), (6, 'Completed'), (7, 'InProgress'), (8, 'Removed')])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='osf.collectionsubmission')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
