# Generated by Django 3.2.15 on 2022-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0005_django3_upgrade_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractnode',
            name='access_requests_enabled',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='external_registration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='registration_responses_migrated',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='allow_bulk_uploads',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='allow_updates',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='bulk_upload_auto_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='registration_responses_migrated',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
    ]
