# Generated by Django 3.2.15 on 2022-11-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.fields
import osf.utils.workflows
from osf.management.commands.collection_submission_machine_state_backfill import (
    collection_submission_machine_state_backfill,
    reverse_collection_submission_machine_state_backfill
)

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0005_add_notabledomain_domainreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsubmission',
            name='machine_state',
            field=models.IntegerField(choices=[(1, 'InProgress'), (2, 'Pending'), (3, 'Rejected'), (4, 'Accepted'), (5, 'Removed')], default=osf.utils.workflows.CollectionSubmissionStates['IN_PROGRESS']),
        ),
        migrations.CreateModel(
            name='CollectionSubmissionAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('trigger', models.IntegerField(choices=[('submit', 'Submit'), ('accept', 'Accept'), ('reject', 'Reject'), ('remove', 'Remove'), ('resubmit', 'Resubmit')])),
                ('from_state', models.IntegerField(choices=[('in_progress', 'InProgress'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('removed', 'Removed')])),
                ('to_state', models.IntegerField(choices=[('in_progress', 'InProgress'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('removed', 'Removed')])),
                ('comment', models.TextField(blank=True)),
                ('deleted', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='osf.collectionsubmission')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
