# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0005_pagecounter_useractivitycounter'),
        ('osf', '0005_remove_abstractnode_parent_node'),
    ]

    operations = [
    ]
