# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodewikipage',
            name='node',
        ),
        migrations.RemoveField(
            model_name='nodewikipage',
            name='user',
        ),
        migrations.DeleteModel(
            name='NodeWikiPage',
        ),
    ]
