# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 15:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='keenio_read_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, db_index=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, db_index=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='institution',
            name='login_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
