# Generated by Django 3.2.15 on 2022-12-21 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.models.validators
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0006_collections_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAssetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='assets')),
                ('name', models.CharField(choices=[('banner', 'banner'), ('logo', 'logo'), ('logo_rounded_corners', 'logo_rounded_corners')], max_length=63)),
                ('institutions', models.ManyToManyField(blank=True, related_name='asset_files', to='osf.Institution')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='InstitutionAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sso_identity', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sso_mail', osf.utils.fields.LowercaseEmailField(blank=True, default='', max_length=254, null=True, validators=[osf.models.validators.validate_email])),
                ('sso_department', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sso_other_attributes', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'institution')},
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
