# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0007_auto_20170403_2304'),
        ('osf', '0007_auto_20170404_0857'),
    ]

    operations = [
    ]
