# Generated by Django 3.2.15 on 2023-01-20 19:46

from django.db import migrations, models
import osf.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0007_guid_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidmetadatarecord',
            name='funding_info',
            field=models.JSONField(blank=True, default=list, validators=[osf.models.validators.JsonschemaValidator({'items': {'additionalProperties': False, 'minProperties': 1, 'properties': {'award_number': {'type': 'string'}, 'award_title': {'type': 'string'}, 'award_uri': {'type': 'string'}, 'funder_identifier': {'type': 'string'}, 'funder_identifier_type': {'type': 'string'}, 'funder_name': {'type': 'string'}}, 'required': [], 'type': 'object'}, 'type': 'array'})]),
        ),
    ]
