# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 15:06
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfuser',
            name='verification_key_v2',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, null=True),
        ),
    ]
