# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='preprint_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osf.StoredFileNode'),
        ),
    ]
