# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import osf.models.validators
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0009_osfuser_verification_key_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileversion',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='location',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(db_index=True, default=dict, null=True, validators=[osf.models.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='metadata',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, db_index=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='size',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trashedfilenode',
            name='deleted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
