# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0009_auto_20170406_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osfuser',
            options={'permissions': (('view_osfuser', 'Can view user details'),)},
        ),
    ]
