# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0009_auto_20170406_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='delegation_protocol',
            field=models.CharField(blank=True, choices=[(b'CAS_PAC4J', b'CAS by pac4j'), (b'OAUTH_PAC4J', b'OAuth by pac4j'), (b'SAML_SHIB', b'SAML by Shibboleth'), (b'', b'No Delegation Protocol')], max_length=15),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
