# Generated by Django 3.2.15 on 2023-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0009_alter_guidmetadatarecord_funding_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsubmissionaction',
            name='trigger',
            field=models.IntegerField(choices=[('submit', 'Submit'), ('accept', 'Accept'), ('reject', 'Reject'), ('remove', 'Remove'), ('resubmit', 'Resubmit'), ('cancel', 'Cancel')]),
        ),
    ]
