# Generated by Django 3.2.17 on 2023-02-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0010_alter_collectionsubmissionaction_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='banner_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='logo_name',
        ),
        migrations.RemoveField(
            model_name='osfuser',
            name='affiliated_institutions',
        ),
        migrations.RemoveField(
            model_name='osfuser',
            name='department',
        ),
    ]
