# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 22:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0010_update_osfuser_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='size',
            field=models.BigIntegerField(blank=True, default=-1, null=True),
        ),
    ]
