# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0009_abstractnode_preprint_file'),
        ('osf', '0010_auto_20161025_1332'),
    ]

    operations = [
    ]
