# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0010_osfuser_verification_key_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractnode',
            name='root',
        ),
    ]
