# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 17:30


from django.db import migrations
from django.contrib.auth.models import Permission, Group


def fix_osfuser_view_permissions(*args):
    view_osfuser_permission = Permission.objects.get(codename='view_osfuser')
    wrong_osfuser_permission = Permission.objects.filter(codename='view_user')
    if wrong_osfuser_permission.exists():
        wrong_osfuser_permission.delete()

    read_only = Group.objects.get(name='read_only')
    osf_admin = Group.objects.get(name='osf_admin')

    read_only.permissions.add(view_osfuser_permission)
    osf_admin.permissions.add(view_osfuser_permission)

    read_only.save()
    osf_admin.save()


def revert_osfuser_view_permissions(*args):
    view_osfuser_permission = Permission.objects.get(codename='view_osfuser')

    osf_admin = Group.objects.get(name='osf_admin')
    read_only = Group.objects.get(name='read_only')

    read_only.permissions.remove(view_osfuser_permission)
    osf_admin.permissions.remove(view_osfuser_permission)

    osf_admin.save()
    read_only.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0011_auto_20170410_1711'),
    ]

    operations = [
        migrations.RunPython(fix_osfuser_view_permissions, revert_osfuser_view_permissions),
    ]
