# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 17:30
from __future__ import unicode_literals

from django.db import migrations

def noop(*args):
    # This migration used to handle admin permissions
    # This is now handled by the post_migrate signal
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0011_auto_20170410_1711'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
