# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 14:57


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0012_auto_20170411_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilenode',
            name='name',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
