# Generated by Django 3.2.17 on 2023-05-17 19:14

from django.db import migrations
import osf.models.validators
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0012_refactor_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='support_email',
            field=osf.utils.fields.LowercaseEmailField(blank=True, default='', max_length=254, validators=[osf.models.validators.validate_email]),
        ),
    ]
