# Generated by Django 3.2.17 on 2023-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0002_auto_20220817_1915'),
        ('osf', '0013_institution_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='storage_regions',
            field=models.ManyToManyField(to='addons_osfstorage.Region'),
        ),
    ]
