# Generated by Django 3.2.17 on 2023-05-24 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0013_institution_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='storage_regions',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
