# Generated by Django 3.2.17 on 2023-06-14 15:30

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0002_auto_20220817_1915'),
        ('osf', '0013_institution_support_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStorageRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_preferred', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.institution')),
                ('storage_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.region')),
            ],
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AddField(
            model_name='institution',
            name='storage_regions',
            field=models.ManyToManyField(related_name='institutions', through='osf.InstitutionStorageRegion', to='addons_osfstorage.Region'),
        ),
        migrations.AddConstraint(
            model_name='institutionstorageregion',
            constraint=models.UniqueConstraint(fields=('institution', 'storage_region'), name='unique_institution_and_region'),
        ),
        migrations.AddConstraint(
            model_name='institutionstorageregion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('institution', 'is_preferred'), name='unique_institution_preferred_region'),
        ),
    ]
