# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0013_auto_20161028_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractnode',
            name='tags',
            field=models.ManyToManyField(related_name='abstractnode_tagged', to='osf.Tag'),
        ),
        migrations.AlterField(
            model_name='storedfilenode',
            name='tags',
            field=models.ManyToManyField(related_name='storedfilenode_tagged', to='osf.Tag'),
        ),
    ]
