# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0013_preprintprovider_domain'),
        ('osf', '0013_auto_20170412_0957'),
    ]

    operations = [
    ]
