# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0014_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
