# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 13:22
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0014_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraction',
            name='date_retracted',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
    ]
