# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_data(state, schema):
    PreprintService = state.get_model('osf', 'preprintservice')
    Subject = state.get_model('osf', 'subject')
    for pp in PreprintService.objects.all():
        for s_id in list(set(sum(pp.subjects, []))):
            s = Subject.objects.get(_id=s_id)
            pp._subjects.add(s)
        pp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0014_migrate_subject_parents_to_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintservice',
            name='_subjects',
            field=models.ManyToManyField(blank=True, to='osf.Subject')
        ),
        migrations.RunPython(
            migrate_data
        ),
    ]
