# Generated by Django 3.2.17 on 2023-08-16 15:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0014_institution_storage_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='citation_styles',
            field=models.ManyToManyField(to='your_app_name.CitationStyle', related_name='supported_styles'),
        ),
    ]
