# Generated by Django 3.2.17 on 2023-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0014_institution_storage_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfuser',
            name='allow_indexing',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
