# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0014_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractnode',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='basefilenode',
            options={'base_manager_name': 'objects'},
        ),
    ]
