# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 20:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0014_remove_abstractnode_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprintService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_string', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('content_type_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('subjects', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='date_last_reported',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='registered_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_last_reported',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='datetime_initiated',
            field=osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='datetime_updated',
            field=osf.utils.fields.NonNaiveDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='draftregistrationapproval',
            name='end_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='draftregistrationapproval',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftregistrationlog',
            name='date',
            field=osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='embargo',
            name='end_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='embargo',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='embargoterminationapproval',
            name='end_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='embargoterminationapproval',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='date_confirmed',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='date_disabled',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='date_last_login',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='date_registered',
            field=osf.utils.fields.NonNaiveDateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='email_last_sent',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privatelink',
            name='date_created',
            field=osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='send_at',
            field=osf.utils.fields.NonNaiveDateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='sent_at',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationapproval',
            name='end_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registrationapproval',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retraction',
            name='end_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='retraction',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_created',
            field=osf.utils.fields.NonNaiveDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_modified',
            field=osf.utils.fields.NonNaiveDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode'),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preprint_services', to='osf.PreprintProvider'),
        ),
        migrations.AlterUniqueTogether(
            name='preprintservice',
            unique_together=set([('node', 'provider')]),
        ),
    ]
