# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0015_auto_20161104_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractnode',
            old_name='preprint_doi',
            new_name='preprint_article_doi',
        ),
        migrations.RemoveField(
            model_name='abstractnode',
            name='preprint_created',
        ),
        migrations.RemoveField(
            model_name='abstractnode',
            name='preprint_providers',
        ),
        migrations.RemoveField(
            model_name='abstractnode',
            name='preprint_subjects',
        ),
        migrations.AddField(
            model_name='abstractnode',
            name='_has_abandoned_preprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preprintservice',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprint', to='osf.AbstractNode'),
        ),
    ]
