# Generated by Django 3.2.17 on 2023-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0015_osfuser_allow_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='citation_styles',
            field=models.ManyToManyField(related_name='supported_styles', to='osf.CitationStyle'),
        ),
        migrations.AddField(
            model_name='abstractprovider',
            name='assertions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='type',
            field=models.CharField(choices=[('osf.node', 'node'), ('osf.draftnode', 'draft node'), ('osf.registration', 'registration')], db_index=True, max_length=255),
        ),
    ]
