# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 19:38
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

from osf.models import PreprintService, Identifier
from website.identifiers.utils import get_or_create_identifiers


def add_identifiers_to_preprints(*args):
    preprints_without_identifiers = PreprintService.objects.filter(identifiers__isnull=True)

    for preprint in preprints_without_identifiers:
        new_identifiers = get_or_create_identifiers(preprint)
        preprint.set_preprint_identifiers(new_identifiers)
        preprint.save()


def remove_identifiers_from_preprints(*args):
    content_type = ContentType.objects.get_for_model(PreprintService)
    Identifier.objects.filter(content_type=content_type).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0015_auto_20170421_1244'),
    ]

    operations = [
        migrations.RunPython(add_identifiers_to_preprints, remove_identifiers_from_preprints),
    ]
