# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import osf.models.base
import osf.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0015_auto_20170421_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[osf.models.validators.validate_email])),
                ('email_type', models.CharField(blank=True, choices=[(b'contact', b'Contact'), (b'support', b'Support')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreprintProviderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('linked_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.SocialNetwork'),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([('email', 'email_type')]),
        ),
        migrations.AddField(
            model_name='preprintprovider',
            name='emails',
            field=models.ManyToManyField(blank=True, to='osf.Email'),
        ),
        migrations.AddField(
            model_name='preprintprovider',
            name='links',
            field=models.ManyToManyField(blank=True, to='osf.PreprintProviderLink'),
        ),
        migrations.AddField(
            model_name='preprintprovider',
            name='social_accounts',
            field=models.ManyToManyField(blank=True, to='osf.SocialAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set([('username', 'network')]),
        ),
    ]
