# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0016_auto_20161107_1103'),
        ('osf', '0015_auto_20161104_1254'),
    ]

    operations = [
    ]
