# Generated by Django 3.2.17 on 2023-12-12 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0016_auto_20230828_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='data_type_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='collection',
            name='disease_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='collectionsubmission',
            name='data_type',
            field=models.CharField(blank=True, help_text='This field was added for use by Inflammatory Bowel Disease Genetics Consortium', max_length=127),
        ),
        migrations.AddField(
            model_name='collectionsubmission',
            name='disease',
            field=models.CharField(blank=True, help_text='This field was added for use by Inflammatory Bowel Disease Genetics Consortium', max_length=127),
        ),
    ]
