# Generated by Django 3.2.17 on 2023-11-13 18:01

from django.db import migrations, models
import django_extensions.db.fields
import osf.models.base
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0016_auto_20230828_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedarMetadataTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('template', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('active', models.BooleanField(default=True)),
                ('template_version', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('title', 'template_version')},
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
