# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0017_merge'),
        ('osf', '0015_merge'),
    ]

    operations = [
    ]
