# Generated by Django 3.2.17 on 2023-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0017_cedarmetadatatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedarmetadatatemplate',
            name='cedar_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='cedarmetadatatemplate',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='cedarmetadatatemplate',
            unique_together={('cedar_id', 'template_version')},
        ),
    ]
