# Generated by Django 3.2.17 on 2023-12-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0017_alter_notabledomain_note'),
        ('osf', '0017_auto_20231212_1843'),
    ]

    operations = [
    ]
