# Generated by Django 3.2.17 on 2024-02-02 15:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0018_merge_20231218_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedarMetadataTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('schema_name', models.CharField(default=None, max_length=255)),
                ('cedar_id', models.CharField(default=None, max_length=255)),
                ('template', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('active', models.BooleanField(default=True)),
                ('template_version', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('cedar_id', 'template_version')},
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='CedarMetadataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('metadata', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('is_published', models.BooleanField(default=False)),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedar_metadata_records', to='osf.guid')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.cedarmetadatatemplate')),
            ],
            options={
                'unique_together': {('guid', 'template')},
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
