# Generated by Django 3.2.17 on 2024-01-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0018_cedarmetadatarecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedarmetadatarecord',
            old_name='guid',
            new_name='target',
        ),
        migrations.AlterUniqueTogether(
            name='cedarmetadatarecord',
            unique_together={('target', 'template')},
        ),
    ]
