# Generated by Django 3.2.17 on 2024-05-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0019_cedarmetadatarecord_cedarmetadatatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='advertise_on_discover_page',
            field=models.BooleanField(default=True, help_text='Indicates if the provider should be advertised on the discovery page.'),
        ),
    ]
