# Generated by Django 3.2.17 on 2024-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0019_cedarmetadatarecord_cedarmetadatatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprint',
            name='custom_publication_citation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
