# Generated by Django 3.2.17 on 2024-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0019_cedarmetadatarecord_cedarmetadatatemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='advertise_on_discover_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='advisory_board',
            field=models.TextField(blank=True, default='', help_text='Indicates if the provider should be advertised on the discovery page.'),
        ),
    ]
