# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import osf.models.validators
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0021_auto_20161116_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='embargoterminationapproval',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivetarget',
            name='stat_result',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='location',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, db_index=True, default=dict, null=True, validators=[osf.models.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_created',
            field=osf.utils.fields.NonNaiveDatetimeField(default=django.utils.timezone.now),
        ),
    ]
