# Generated by Django 3.2.17 on 2024-07-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0021_preprint_custom_publication_citation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewAction',
            new_name='PreprintAction',
        ),
    ]
