# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0022_backfill_date_retracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='default_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_license', to='osf.NodeLicense'),
        ),
        migrations.AlterField(
            model_name='preprintprovider',
            name='licenses_acceptable',
            field=models.ManyToManyField(blank=True, related_name='licenses_acceptable', to='osf.NodeLicense'),
        ),
    ]
