# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0022_auto_20170503_1818'),
        ('osf', '0021_retraction_date_retracted'),
    ]

    operations = [
    ]
