# Generated by Django 3.2.17 on 2024-07-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0022_alter_abstractnode_subjects_alter_abstractnode_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprint',
            name='affiliated_institutions',
            field=models.ManyToManyField(related_name='preprints', to='osf.Institution'),
        ),
    ]
