# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 17:31
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import osf.models.validators
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0022_auto_20161118_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftregistrationapproval',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='embargo',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='embargoterminationapproval',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='location',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, null=True, validators=[osf.models.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='registrationapproval',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='retraction',
            name='initiation_date',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_modified',
            field=osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now),
        ),
    ]
