# Generated by Django 4.2.15 on 2024-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0023_preprint_affiliated_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='link_to_external_reports_archive',
            field=models.URLField(blank=True, default='', help_text='Full URL where institutional admins can access archived metrics reports.', max_length=2048),
        ),
    ]
