# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0023_merge_20170503_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaschema',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
