# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 20:59
from __future__ import unicode_literals

from django.db import migrations
import osf.models.validators
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0024_auto_20161212_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='location',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, null=True, validators=[osf.models.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='metadata',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict),
        ),
    ]
