# Generated by Django 4.2.15 on 2024-11-22 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0024_guidversionsthrough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdigest',
            name='node_lineage',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
        ),
    ]
