# Generated by Django 4.2.13 on 2024-12-05 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0024_institution_link_to_external_reports_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderequest',
            name='message_recipient',
            field=models.ForeignKey(blank=True, help_text='An optional user who will recieve a message probably an email exaplining the nature of the request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_with_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noderequest',
            name='requested_permissions',
            field=models.CharField(blank=True, choices=[('read', 'read'), ('write', 'write'), ('admin', 'admin')], help_text='The permissions being requested for the node (e.g., read, write, admin).', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='noderequest',
            name='request_type',
            field=models.CharField(choices=[('access', 'Access'), ('withdrawal', 'Withdrawal'), ('institutional_request', 'Institutional_Request')], help_text='The specific type of node request (e.g., access request).', max_length=31),
        ),
        migrations.AlterField(
            model_name='noderequest',
            name='target',
            field=models.ForeignKey(help_text='The target node for the request (usually a project).', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='osf.abstractnode'),
        ),
    ]
