# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0024_migrate_subject_parents_to_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintservice',
            name='_subjects',
            field=models.ManyToManyField(blank=True, related_name='preprint_services', to='osf.Subject'),
        ),
    ]
