# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0025_auto_20161212_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecounter',
            name='_id',
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='useractivitycounter',
            name='_id',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
    ]
