# Generated by Django 4.2.15 on 2025-01-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0025_contributor_is_curator_and_more'),
        ('osf', '0025_versioned_guid_for_preprints_doi_versioning'),
    ]

    operations = [
    ]
