# Generated by Django 4.2.13 on 2025-01-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0025_institutional_request_access_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='is_curator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noderequest',
            name='is_institutional_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preprintrequest',
            name='is_institutional_request',
            field=models.BooleanField(default=False),
        ),
    ]
