# Generated by Django 4.2.13 on 2025-01-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0025_contributor_is_curator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='is_curator',
            field=models.BooleanField(default=False),
        ),
    ]
