# Generated by Django 4.2.15 on 2024-12-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0025_noderequest_requested_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='can_request_access',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
