# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0026_preprintservice_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='header_text',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
