# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 19:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0026_rename_preprintservice_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set([('text', 'provider')]),
        ),
    ]
