# Generated by Django 4.2.15 on 2025-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0026_merge_20250122_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidversionsthrough',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
