# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0027_auto_20170428_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'base_manager_name': 'objects'},
        ),
    ]
