# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0027_auto_20161212_1352'),
        ('osf', '0027_preprintprovider_header_text'),
    ]

    operations = [
    ]
