# Generated by Django 4.2.15 on 2025-03-27 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0027_alter_guidversionsthrough_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='grade_levels_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='collectionsubmission',
            name='grade_levels',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
