# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0028_auto_20170504_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaschema',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
