# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-03 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('osf', '0029_auto_20170103_1309'), ('osf', '0030_auto_20170103_1314')]

    dependencies = [
        ('osf', '0028_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='delegation_protocol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='banner_name',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo_name',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='banner_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
