# Generated by Django 4.2.15 on 2025-04-17 16:21

from django.db import migrations
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0028_collection_grade_levels_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='addon_verified_resource_links',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
    ]
