# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0027_auto_20161213_2150'),
        ('osf', '0028_merge'),
    ]

    operations = [
    ]
