# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0028_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='date_last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
