# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 18:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import osf.models.conference
import osf.models.spam
import osf.models.user
import osf.models.validators
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0028_auto_20170504_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractnode',
            name='child_node_subscriptions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='file_guid_to_share_uuids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='registered_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='reports',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, validators=[osf.models.spam._validate_reports]),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='spam_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='wiki_pages_current',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='wiki_pages_versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='wiki_private_uuids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='archivetarget',
            name='stat_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reports',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, validators=[osf.models.spam._validate_reports]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='spam_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='conference',
            name='field_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=osf.models.conference.get_default_field_names, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='_metaschema_flags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='draftregistration',
            name='registration_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='draftregistrationapproval',
            name='approval_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='draftregistrationapproval',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='embargo',
            name='approval_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='embargo',
            name='stashed_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='embargoterminationapproval',
            name='approval_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='embargoterminationapproval',
            name='stashed_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='location',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, null=True, validators=[osf.models.validators.validate_location]),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='mailrecord',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='metaschema',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='nodelog',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='comments_viewed_timestamp',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='contributor_added_email_records',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='email_verifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='external_identity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='jobs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, validators=[osf.models.validators.validate_history_item]),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='mailchimp_mailing_lists',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='notifications_configured',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='osf_mailing_lists',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=osf.models.user.get_default_mailing_lists, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='schools',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, validators=[osf.models.validators.validate_history_item]),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='security_messages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='social',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, validators=[osf.models.validators.validate_social]),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='unclaimed_records',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='verification_key_v2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='pagecounter',
            name='date',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='preprintprovider',
            name='subjects_acceptable',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='queuedmail',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='registrationapproval',
            name='approval_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='registrationapproval',
            name='stashed_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='retraction',
            name='approval_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='retraction',
            name='stashed_urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='session',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='useractivitycounter',
            name='action',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AlterField(
            model_name='useractivitycounter',
            name='date',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
    ]
