# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0029_externalaccount_date_last_refreshed'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='domain',
            field=models.CharField(blank=True, max_length=253, null=True),
        ),
    ]
