# Generated by Django 4.2.13 on 2025-05-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0029_remove_abstractnode_keenio_read_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='osfgroupgroupobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='osfgroupgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='osfgroupgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='osfgroupgroupobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='osfgrouplog',
            name='group',
        ),
        migrations.RemoveField(
            model_name='osfgrouplog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='osfgroupuserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='osfgroupuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='osfgroupuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='osfgroupuserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='OSFGroup',
        ),
        migrations.DeleteModel(
            name='OSFGroupGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='OSFGroupLog',
        ),
        migrations.DeleteModel(
            name='OSFGroupUserObjectPermission',
        ),
    ]
