# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0029_merge'),
        ('osf', '0029_externalaccount_date_last_refreshed'),
    ]

    operations = [
    ]
