# Generated by Django 4.2.15 on 2025-06-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0029_remove_abstractnode_keenio_read_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftregistration',
            name='custom_storage_usage_limit_private',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='draftregistration',
            name='custom_storage_usage_limit_public',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=100, null=True),
        ),
    ]
