# Generated by Django 4.2.15 on 2025-05-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_abstractnode_manual_guid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractnode',
            old_name='manual_guid',
            new_name='guid_assigned',
        ),
    ]
