# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_preprint_provider_institution_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprintprovider',
            name='banner_name',
        ),
        migrations.RemoveField(
            model_name='preprintprovider',
            name='header_text',
        ),
        migrations.RemoveField(
            model_name='preprintprovider',
            name='logo_name',
        ),
        migrations.AddField(
            model_name='preprintprovider',
            name='footer_links',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='preprintprovider',
            name='advisory_board',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='preprintprovider',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
