# Generated by Django 4.2.13 on 2025-04-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_alter_notificationsubscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='email_freq_options',
        ),
    ]
