# Generated by Django 4.2.13 on 2025-04-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_alter_notificationsubscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osfuser',
            name='contributor_added_email_records',
        ),
    ]
