# Generated by Django 4.2.15 on 2025-06-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_abstractnode__manual_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftregistration',
            name='custom_storage_usage_limit',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=100, null=True),
        ),
    ]
