# Generated by Django 4.2.15 on 2025-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_abstractnode__manual_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='registration_word',
            field=models.CharField(default='registration', max_length=50),
        ),
    ]
