# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_merge'),
        ('osf', '0031_auto_20170202_0943'),
    ]

    operations = [
    ]
