# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0031_auto_20170202_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='blog_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
