# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0031_auto_20170202_0943'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='osfuser',
            managers=[
                ('subselect', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='tags',
            field=models.ManyToManyField(blank=True, to='osf.Tag'),
        ),
    ]
