# Generated by Django 4.2.15 on 2025-08-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0031_abstractprovider_registration_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
