# Generated by Django 4.2.15 on 2025-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0031_abstractprovider_registration_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osfgroup',
            name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='osfgroupgroupobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='osfgroupgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='osfgroupgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='osfgroupgroupobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='osfgrouplog',
            name='group',
        ),
        migrations.RemoveField(
            model_name='osfgrouplog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='osfgroupuserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='osfgroupuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='osfgroupuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='osfgroupuserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuickFilesNode',
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='type',
            field=models.CharField(choices=[('osf.draftnode', 'draft node'), ('osf.node', 'node'), ('osf.registration', 'registration')], db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='OSFGroup',
        ),
        migrations.DeleteModel(
            name='OSFGroupGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='OSFGroupLog',
        ),
        migrations.DeleteModel(
            name='OSFGroupUserObjectPermission',
        ),
    ]
