# Generated by Django 4.2.13 on 2025-04-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0031_remove_osfuser_contributor_added_email_records'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueuedMail',
        ),
    ]
