# Generated by Django 4.2.15 on 2025-09-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0032_brand_background_color'),
        ('osf', '0032_remove_osfgroup_creator_and_more'),
    ]

    operations = [
    ]
