# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.db.models.deletion import CASCADE
from django_extensions.db.fields import CreationDateTimeField, ModificationDateTimeField
from osf.models.validators import validate_email
from osf.utils.fields import LowercaseEmailField


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0032_unquote_gd_nodesettings_folder_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('address', LowercaseEmailField(max_length=254, unique=True, db_index=True, validators=[validate_email])),
                ('user', models.ForeignKey(blank=False, null=False, on_delete=CASCADE, related_name='_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='osfuser',
            name='emails'
        ),
    ]
