# Generated by Django 4.2.13 on 2025-07-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0032_alter_notificationsubscription_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueuedMail',
        ),
    ]
