# Generated by Django 4.2.17 on 2025-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0033_merge_20250915_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureBlobStorageFileNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osf.basefilenode',),
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='type',
            field=models.CharField(choices=[('osf.azureblobstoragefile', 'azure blob storage file'), ('osf.azureblobstoragefilenode', 'azure blob storage file node'), ('osf.azureblobstoragefolder', 'azure blob storage folder'), ('osf.bitbucketfile', 'bitbucket file'), ('osf.bitbucketfilenode', 'bitbucket file node'), ('osf.bitbucketfolder', 'bitbucket folder'), ('osf.boxfile', 'box file'), ('osf.boxfilenode', 'box file node'), ('osf.boxfolder', 'box folder'), ('osf.dataversefile', 'dataverse file'), ('osf.dataversefilenode', 'dataverse file node'), ('osf.dataversefolder', 'dataverse folder'), ('osf.dropboxfile', 'dropbox file'), ('osf.dropboxfilenode', 'dropbox file node'), ('osf.dropboxfolder', 'dropbox folder'), ('osf.figsharefile', 'figshare file'), ('osf.figsharefilenode', 'figshare file node'), ('osf.figsharefolder', 'figshare folder'), ('osf.githubfile', 'github file'), ('osf.githubfilenode', 'github file node'), ('osf.githubfolder', 'github folder'), ('osf.gitlabfile', 'git lab file'), ('osf.gitlabfilenode', 'git lab file node'), ('osf.gitlabfolder', 'git lab folder'), ('osf.googledrivefile', 'google drive file'), ('osf.googledrivefilenode', 'google drive file node'), ('osf.googledrivefolder', 'google drive folder'), ('osf.onedrivefile', 'one drive file'), ('osf.onedrivefilenode', 'one drive file node'), ('osf.onedrivefolder', 'one drive folder'), ('osf.osfstoragefile', 'osf storage file'), ('osf.osfstoragefilenode', 'osf storage file node'), ('osf.osfstoragefolder', 'osf storage folder'), ('osf.owncloudfile', 'owncloud file'), ('osf.owncloudfilenode', 'owncloud file node'), ('osf.owncloudfolder', 'owncloud folder'), ('osf.s3file', 's3 file'), ('osf.s3filenode', 's3 file node'), ('osf.s3folder', 's3 folder'), ('osf.trashedfile', 'trashed file'), ('osf.trashedfilenode', 'trashed file node'), ('osf.trashedfolder', 'trashed folder')], db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AzureBlobStorageFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osf.azureblobstoragefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='AzureBlobStorageFolder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('osf.azureblobstoragefilenode', models.Model),
        ),
    ]
