# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0032_auto_20170217_1111'),
        ('osf', '0033_create_permissions_for_admin_groups'),
    ]

    operations = [
    ]
