# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 22:25


from django.conf import settings
from django.db.models.deletion import CASCADE
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0033_user_emails_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)
        ),
    ]
