# Generated by Django 4.2.17 on 2025-09-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0033_merge_20250915_2100'),
        ('osf', '0033_notification_system'),
    ]

    operations = [
    ]
