# Generated by Django 4.2.13 on 2025-07-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0034_remove_abstractnode_child_node_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osfuser',
            name='contributor_added_email_records',
        ),
        migrations.RemoveField(
            model_name='osfuser',
            name='group_connected_email_records',
        ),
        migrations.RemoveField(
            model_name='osfuser',
            name='member_added_email_records',
        ),
    ]
