# Generated by Django 4.2.15 on 2025-12-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0034_azureblobstoragefilenode_alter_basefilenode_type_and_more'),
        ('osf', '0034_merge_20250917_1902'),
    ]

    operations = [
    ]
