# Generated by Django 4.2.15 on 2025-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0034_remove_abstractnode_child_node_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='_is_digest',
            field=models.BooleanField(default=False),
        ),
    ]
