# Generated by Django 4.2.17 on 2026-01-27 21:03

from django.db import migrations

from django.core.management import call_command


def run_deduplication_command(apps, schema_editor):
    call_command('remove_duplicate_notification_subscriptions_v2')


def reverse(apps, schema_editor):
    """
    This is a no-op since we can't restore deleted records.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0035_merge_20251215_1451'),
    ]

    operations = [
        migrations.RunPython(run_deduplication_command, reverse),
    ]
