# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0033_auto_20170210_1019'),
        ('osf', '0035_adminlogentry_adminprofile'),
    ]

    operations = [
    ]
