# Generated by Django 4.2.26 on 2026-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0035_merge_20251215_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='date_last_indexed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractnode',
            name='has_been_indexed',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='date_last_indexed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='has_been_indexed',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='date_last_indexed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='has_been_indexed',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preprint',
            name='date_last_indexed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preprint',
            name='has_been_indexed',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
