# Generated by Django 4.2.13 on 2025-07-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0035_remove_osfuser_contributor_added_email_records_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationDigest',
        ),
    ]
