# Generated by Django 4.2.15 on 2026-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0035_merge_20251215_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fake_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NO_USER_FOUND', 'No User Found'), ('USER_DISABLED', 'User Disabled'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('PARTIAL_SUCCESS', 'Partial Success'), ('AUTO_FIXED', 'Auto Fixed')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together={('notification_type', 'user', 'content_type', 'object_id', '_is_digest')},
        ),
    ]
