# Generated by Django 4.2.17 on 2026-01-27 21:03

from django.db import migrations, models
import osf.utils.fields

from django.core.management import call_command


def run_deduplication_command(apps, schema_editor):
    call_command('remove_duplicate_notification_subscriptions_v2')


def reverse(apps, schema_editor):
    """
    This is a no-op since we can't restore deleted records.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0035_merge_20251215_1451'),
    ]

    operations = [
        migrations.RunPython(run_deduplication_command, reverse),
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
        migrations.AddField(
            model_name='notification',
            name='fake_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='no_login_email_last_sent',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NO_USER_FOUND', 'No User Found'), ('USER_DISABLED', 'User Disabled'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('PARTIAL_SUCCESS', 'Partial Success'), ('AUTO_FIXED', 'Auto Fixed')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together={('notification_type', 'user', 'content_type', 'object_id', '_is_digest')},
        ),
    ]
