# Generated by Django 4.2.17 on 2026-02-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0035_merge_20251215_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sso_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
