# Generated by Django 4.2.15 on 2026-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0037_notification_refactor_post_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sso_availability',
            field=models.CharField(choices=[('Public', 'PUBLIC'), ('Unavailable', 'UNAVAILABLE'), ('Hidden', 'HIDDEN')], default='Hidden', max_length=15),
        ),
    ]
