# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0037_auto_20170227_1522'),
        ('osf', '0037_auto_20170227_1354'),
    ]

    operations = [
    ]
