# Generated by Django 4.2.26 on 2026-04-23 14:25

from django.db import migrations, models


def create_initial_record(apps, schema_editor):
    MaintenanceMode = apps.get_model('osf', 'MaintenanceMode')
    MaintenanceMode.objects.get_or_create(
        pk=1,
        defaults={'maintenance_mode': False}
    )


def reverse_initial_record(apps, schema_editor):
    # the reverse 'reverse_initial_record' does nothing
    # because the table will be removed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0038_abstractnode_date_last_indexed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            create_initial_record,
            reverse_code=reverse_initial_record
        ),
    ]
