# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0038_merge'),
        ('osf', '0038_abstractnode_root'),
    ]

    operations = [
    ]
