# Generated by Django 4.2.15 on 2026-04-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0038_abstractnode_date_last_indexed_and_more'),
        ('osf', '0038_institution_sso_availability'),
    ]

    operations = [
    ]
