# Generated by Django 4.2.26 on 2026-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0038_abstractprovider_required_metadata_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedarmetadatatemplate',
            name='should_index_for_search',
            field=models.BooleanField(default=False),
        ),
    ]
