# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 17:44


from django.db import migrations, models
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0038_ensure_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', osf.utils.fields.NonNaiveDateTimeField()),
                ('end', osf.utils.fields.NonNaiveDateTimeField()),
            ],
        ),
    ]
