# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0039_maintenancestate'),
        ('osf', '0037_remove_emails_for_unconfirmed_users'),
    ]

    operations = [
    ]
