# Generated by Django 4.2.26 on 2026-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0039_merge_20260427_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
