# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0039_maintenancestate'),
        ('osf', '0033_auto_20170531_1119'),
    ]

    operations = [
    ]
