# Generated by Django 4.2 on 2026-04-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0039_merge_20260427_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='required_metadata_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='required_by_providers',
                to='osf.cedarmetadatatemplate',
            ),
        ),
    ]
