# Generated by Django 4.2.26 on 2026-05-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0039_merge_20260427_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivejob',
            name='src_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.abstractnode', verbose_name='source node'),
        ),
    ]
