# Generated by Django 4.2.26 on 2026-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0040_maintenancemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
