# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0040_merge_20170619_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='preprint_word',
            field=models.CharField(choices=[(b'preprint', b'Preprint'), (b'paper', b'Paper')], default=b'preprint', max_length=10),
        ),
    ]
