# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0040_ensure_root_field'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='abstractnode',
            index_together=set([('is_public', 'is_deleted', 'type')]),
        ),
    ]
