# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0040_merge_20170619_0922'),
        ('osf', '0041_auto_20170615_0855'),
    ]

    operations = [
    ]
