# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0041_auto_20170706_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='reviews_comments_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preprintprovider',
            name='reviews_comments_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preprintprovider',
            name='reviews_workflow',
            field=models.CharField(choices=[('post-moderation', 'Post-Moderation'), ('pre-moderation', 'Pre-Moderation')], default='pre-moderation', max_length=15),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='reviews_state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15),
        ),
    ]
