# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0030_preprintprovider_domain'),
        ('osf', '0041_auto_20170308_1932'),
    ]

    operations = [
    ]
