# Generated by Django 4.2.26 on 2026-05-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0041_cedarmetadatatemplate_should_index_for_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedarmetadatatemplate',
            name='is_for_collections',
            field=models.BooleanField(default=False),
        ),
    ]
