# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0041_auto_20170706_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestate',
            name='_id',
            field=models.CharField(default='default', help_text=b"An identifier for this maintenance state, i.e. 'rackspace', 'maintenance'", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancestate',
            name='level',
            field=models.IntegerField(choices=[(1, b'info'), (2, b'warning'), (3, b'danger')], default=1),
        ),
        migrations.AddField(
            model_name='maintenancestate',
            name='message',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
