# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0042_auto_20170707_1019'),
        ('osf', '0042_preprintprovider_share_title'),
    ]

    operations = [
    ]
