# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 15:07
"""Sets the share_title field on production PreprintProviders. Makes no
updates if the listed providers don't exist in the current envirionment.
"""
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0042_preprintprovider_share_title'),
    ]

    operations = [
    ]
