# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0042_add_registration_registered_date_desc_index'),
        ('osf', '0042_merge'),
    ]

    operations = [
    ]
