# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 17:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import osf.models.base
import osf.models.mixins
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0003_auto_20170317_1256'),
        ('osf', '0042_add_registration_registered_date_desc_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFileNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('guid_string', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('content_type_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('osf.trashedfilenode', 'trashed file node'), ('osf.trashedfile', 'trashed file'), ('osf.trashedfolder', 'trashed folder'), ('osf.osfstoragefilenode', 'osf storage file node'), ('osf.osfstoragefile', 'osf storage file'), ('osf.osfstoragefolder', 'osf storage folder'), ('osf.boxfilenode', 'box file node'), ('osf.boxfolder', 'box folder'), ('osf.boxfile', 'box file'), ('osf.dataversefilenode', 'dataverse file node'), ('osf.dataversefolder', 'dataverse folder'), ('osf.dataversefile', 'dataverse file'), ('osf.dropboxfilenode', 'dropbox file node'), ('osf.dropboxfolder', 'dropbox folder'), ('osf.dropboxfile', 'dropbox file'), ('osf.figsharefilenode', 'figshare file node'), ('osf.figsharefolder', 'figshare folder'), ('osf.figsharefile', 'figshare file'), ('osf.githubfilenode', 'github file node'), ('osf.githubfolder', 'github folder'), ('osf.githubfile', 'github file'), ('osf.googledrivefilenode', 'google drive file node'), ('osf.googledrivefolder', 'google drive folder'), ('osf.googledrivefile', 'google drive file'), ('osf.owncloudfilenode', 'owncloud file node'), ('osf.owncloudfolder', 'owncloud folder'), ('osf.owncloudfile', 'owncloud file'), ('osf.s3filenode', 's3 file node'), ('osf.s3folder', 's3 folder'), ('osf.s3file', 's3 file')], db_index=True, max_length=255)),
                ('last_touched', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('_history', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=[])),
                ('provider', models.CharField(db_index=True, max_length=25)),
                ('name', models.TextField(blank=True, null=True)),
                ('_path', models.TextField(blank=True, null=True)),
                ('_materialized_path', models.TextField(blank=True, null=True)),
                ('deleted_on', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('copied_from', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_of', to='osf.BaseFileNode')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(osf.models.mixins.CommentableMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='storedfilenode',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='storedfilenode',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='copied_from',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='copied_from',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='versions',
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='preprint_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osf.BaseFileNode'),
        ),
        migrations.DeleteModel(
            name='StoredFileNode',
        ),
        migrations.DeleteModel(
            name='TrashedFileNode',
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode'),
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='osf.BaseFileNode'),
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='versions',
            field=models.ManyToManyField(to='osf.FileVersion'),
        ),
        migrations.CreateModel(
            name='BoxFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='DataverseFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='DropboxFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='FigshareFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='GithubFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='GoogleDriveFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='OsfStorageFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='OwncloudFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='S3FileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.AlterIndexTogether(
            name='basefilenode',
            index_together=set([('node', 'type', 'provider', '_path'), ('node', 'type', 'provider')]),
        ),
        migrations.CreateModel(
            name='BoxFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.boxfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='BoxFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.boxfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='DataverseFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.dataversefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='DataverseFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.dataversefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='DropboxFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.dropboxfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='DropboxFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.dropboxfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='FigshareFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.figsharefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='FigshareFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.figsharefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='GithubFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.githubfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='GithubFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.githubfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.googledrivefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='GoogleDriveFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.googledrivefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='OsfStorageFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.osfstoragefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='OsfStorageFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.osfstoragefilenode', models.Model),
        ),
        migrations.CreateModel(
            name='OwncloudFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.owncloudfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='OwncloudFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.owncloudfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='S3File',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.s3filenode', models.Model),
        ),
        migrations.CreateModel(
            name='S3Folder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.s3filenode', models.Model),
        ),
        migrations.CreateModel(
            name='TrashedFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
        migrations.CreateModel(
            name='TrashedFile',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.trashedfilenode',),
        ),
        migrations.CreateModel(
            name='TrashedFolder',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.trashedfilenode',),
        ),
    ]
