# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0042_auto_20170707_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestate',
            name='level',
            field=models.IntegerField(choices=[(1, b'info'), (2, b'warning'), (3, b'danger')], default=1),
        ),
        migrations.AddField(
            model_name='maintenancestate',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
