# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import osf.models.validators
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0042_add_registration_registered_date_desc_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osfuser',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='jobs',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=list, validators=[osf.models.validators.validate_history_item]),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='schools',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=list, validators=[osf.models.validators.validate_history_item]),
        ),
    ]
