# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 18:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import osf.models.base
import osf.models.mixins
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0003_auto_20170311_1656'),
        ('osf', '0042_add_registration_registered_date_desc_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStoredFileNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('guid_string', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('content_type_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('last_touched', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('history', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=[])),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now)),
                ('is_file', models.BooleanField(default=True)),
                ('provider', models.CharField(db_index=True, max_length=25)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.CharField(blank=True, max_length=2000, null=True)),
                ('_materialized_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode')),
                ('tags', models.ManyToManyField(related_name='basestoredfilenode_tagged', to='osf.Tag')),
                ('versions', models.ManyToManyField(to='osf.FileVersion')),
            ],
            bases=(osf.models.mixins.CommentableMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='storedfilenode',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='storedfilenode',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='copied_from',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='storedfilenode',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='copied_from',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='node',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='trashedfilenode',
            name='versions',
        ),
        migrations.DeleteModel(
            name='StoredFileNode',
        ),
        migrations.DeleteModel(
            name='TrashedFileNode',
        ),
        migrations.CreateModel(
            name='StoredFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basestoredfilenode',),
        ),
        migrations.CreateModel(
            name='TrashedFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basestoredfilenode',),
        ),
        migrations.AddField(
            model_name='basestoredfilenode',
            name='copied_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_of', to='osf.StoredFileNode'),
        ),
        migrations.AddField(
            model_name='basestoredfilenode',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='osf.StoredFileNode'),
        ),
        migrations.AlterIndexTogether(
            name='basestoredfilenode',
            index_together=set([('node', 'is_file', 'provider'), ('path', 'node', 'is_file', 'provider')]),
        ),
    ]
