# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0043_auto_20170313_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractnode',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='blacklistguid',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='citationstyle',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['id'], 'permissions': (('view_conference', 'Can view conference details in the admin app.'),)},
        ),
        migrations.AlterModelOptions(
            name='draftregistrationapproval',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='embargo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='embargoterminationapproval',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='externalaccount',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='identifier',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='metaschema',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nodelicense',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='notificationsubscription',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='osfuser',
            options={'ordering': ['id'], 'permissions': (('view_user', 'Can view user details'),)},
        ),
        migrations.AlterModelOptions(
            name='pagecounter',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='preprintservice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='registrationapproval',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='retraction',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='storedfilenode',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='useractivitycounter',
            options={'ordering': ['id']},
        ),
    ]
