# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0043_auto_20170312_1356'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX osf_basestoredfilenode_file_constraint_index ON public.osf_basestoredfilenode (node_id, name, parent_id, is_file, provider, path) WHERE is_deleted IS FALSE;',
            'DROP INDEX public.osf_basestoredfilenode_file_constraint_index RESTRICT;'
        )
    ]
