# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 14:30
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0043_auto_20170313_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='description_link',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict),
        ),
    ]
