# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0029_auto_20170113_1732'),
        ('osf', '0043_auto_20170313_1717'),
    ]

    operations = [
    ]
