# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0039_retraction_date_retracted'),
        ('osf', '0043_auto_20170313_1717'),
    ]

    operations = [
    ]
