# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0041_preprintprovider_about_link'),
        ('osf', '0043_auto_20170313_1717'),
    ]

    operations = [
    ]
