# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 19:26
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0044_filenodeunique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestoredfilenode',
            name='deleted_on',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
    ]
