# Generated by Django 4.2.26 on 2026-08-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0044_notification_scheduled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileversion',
            options={'ordering': ('-created', '-id')},
        ),
    ]
