# Generated by Django 4.2.26 on 2026-07-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0040_alter_archivejob_src_node'),
        ('osf', '0044_notification_scheduled'),
    ]

    operations = [
    ]
