# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0044_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilenode',
            name='tags',
            field=models.ManyToManyField(related_name='basefilenode_tagged', to='osf.Tag'),
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_children', to='osf.BaseFileNode'),
        ),
    ]
