# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0045_auto_20170312_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestoredfilenode',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basestoredfilenode',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='osf.BaseStoredFileNode'),
        ),
    ]
