# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0043_set_share_title'),
        ('osf', '0045_add_view_subject_permissions'),
    ]

    operations = [
    ]
