# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0046_merge_20170803_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractnode',
            name='users_watching_node',
        ),
    ]
