# Generated by Django 4.2.26 on 2026-07-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0046_dashboard_group_staff_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadevent',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
