# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0046_auto_20170321_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilenode',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='osf.AbstractNode'),
        ),
    ]
