# Generated by Django 4.2.26 on 2026-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0047_downloadevent_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadevent',
            name='storage_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
