# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0047_remove_abstractnode_users_watching_node'),
        ('osf', '0044_basefilenode_uniqueness_index'),
    ]

    operations = [
    ]
