# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0047_auto_20170321_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFileNode',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('osf.basefilenode',),
        ),
    ]
