# Generated by Django 4.2.26 on 2026-08-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0049_project_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
