# Generated by Django 4.2.26 on 2026-08-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0051_alter_fileversion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadevent',
            name='download_channel',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend (website)'), ('api', 'API client'), ('other', 'Other / direct')], default='', max_length=16),
        ),
    ]
