# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0051_remove_invalid_social_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintprovider',
            name='share_publish_type',
            field=models.CharField(choices=[(b'Preprint', b'Preprint'), (b'Thesis', b'Thesis')], default=b'Preprint', help_text=b'This SHARE type will be used when pushing publications to SHARE', max_length=32),
        ),
    ]
