# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 17:35
from __future__ import unicode_literals

import logging

from django.db import migrations

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0052_preprintprovider_share_publish_type'),
    ]

    operations = [
    ]
