# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 17:35
from __future__ import unicode_literals

import logging

from django.db import migrations, models
from django.core.paginator import Paginator

from addons.osfstorage.models import NodeSettings as OSFSNodeSettings, OsfStorageFolder
from osf.models import OSFUser, QuickFilesNode, Contributor
from osf.models.base import ensure_guid
from osf.models.quickfiles import get_quickfiles_project_title

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0052_preprintprovider_share_publish_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFilesNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('osf.abstractnode',),
        ),
        migrations.AlterField(
            model_name='abstractnode',
            name='type',
            field=models.CharField(choices=[('osf.node', 'node'), ('osf.collection', 'collection'), ('osf.registration', 'registration'), ('osf.quickfilesnode', 'quickfilesnode')], db_index=True, max_length=255),
        ),
    ]
