# Generated by Django 4.2.26 on 2026-09-03 22:24

import django.contrib.postgres.fields
from django.db import migrations, models
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0052_downloadevent_download_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuckRegistrationReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                ('cadence', models.CharField(choices=[('instantly', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=32)),
                ('last_sent', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
            ],
        ),
    ]
