# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0052_preprintprovider_share_publish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationstyle',
            name='has_bibliography',
            field=models.BooleanField(default=False),
        ),
    ]
