# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0052_preprintprovider_share_publish_type'),
    ]

    operations = [
    ]
