# Generated by Django 4.2.26 on 2026-09-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0054_merge_20260909_reconcile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcampaignrecipient',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationcampaignrecipient',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('postponed', 'Postponed')], db_index=True, default='pending', max_length=20),
        ),
    ]
