# Generated by Django 4.2.26 on 2026-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0055_notificationcampaignrecipient_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcampaign',
            name='queued_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
