# Generated by Django 4.2.26 on 2026-09-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0055_notificationcampaignrecipient_batch_id_and_more'),
        ('osf', '0055_stuckregistrationreportconfig'),
    ]

    operations = [
    ]
