# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0055_auto_20170821_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprintprovider',
            options={'permissions': (('view_submissions', 'Can view all submissions to this provider'), ('add_moderator', 'Can add other users as moderators for this provider'), ('add_reviewer', 'Can add other users as reviewers for this provider'), ('review_assigned_submissions', 'Can submit reviews for submissions to this provider which have been assigned to this user'), ('assign_reviewer', 'Can assign reviewers to review specific submissions to this provider'), ('set_up_moderation', 'Can set up moderation for this provider'), ('view_assigned_submissions', 'Can view submissions to this provider which have been assigned to this user'), ('edit_reviews_settings', 'Can edit reviews settings for this provider'), ('view_review_logs', 'Can view review/moderation logs for submissions to this provider'), ('accept_submissions', 'Can accept submissions to this provider'), ('reject_submissions', 'Can reject submissions to this provider'), ('edit_review_comments', 'Can edit comments on review logs for this provider'), ('view_preprintprovider', 'Can view preprint provider details'))},
        ),
        migrations.AlterField(
            model_name='preprintprovider',
            name='reviews_comments_anonymous',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='preprintprovider',
            name='reviews_comments_private',
            field=models.NullBooleanField(),
        ),
    ]
