# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0053_nodelog_faster_index'),
        ('osf', '0055_auto_20170823_1648'),
    ]

    operations = [
    ]
