# Generated by Django 4.2.26 on 2026-09-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0055_notificationcampaignrecipient_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcampaign',
            name='queued_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificationcampaignrecipient',
            name='status',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued'),
                    ('pending', 'Pending'),
                    ('awaiting_delivery', 'Awaiting Delivery'),
                    ('sent', 'Sent'),
                    ('failed', 'Failed'),
                    ('skipped', 'Skipped'),
                    ('postponed', 'Postponed'),
                ],
                db_index=True,
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='notificationcampaignrecipient',
            name='sent_at',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
