# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0055_auto_20170823_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationstyle',
            name='has_bibliography',
            field=models.BooleanField(default=False),
        ),
    ]
