# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0056_merge_20170831_0832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileversion',
            options={'ordering': ('-date_created',)},
        ),
    ]
