# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 19:52
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0056_merge_20170831_0832'),
    ]

    operations = [
        migrations.RunSQL([
            'CREATE INDEX fileversion__date_created_desc on osf_fileversion (date_created DESC);',
        ], [
            'DROP INDEX IF EXISTS fileversion__date_created_desc RESTRICT;',
        ])
    ]
