# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0057_order_fileversion_by_date_created'),
        ('osf', '0054_add_file_version_indices'),
    ]

    operations = [
    ]
