# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0057_order_fileversion_by_date_created'),
        ('osf', '0057_merge_20170913_1006'),
    ]

    operations = [
    ]
