# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0058_merge_20170913_2232'),
        ('osf', '0055_update_metaschema_active'),
    ]

    operations = [
    ]
