# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # CREATE INDEX CONCURRENTLY cannot be run in a txn

    dependencies = [
        ('osf', '0059_merge_20170914_1100'),
    ]

    operations = [
        migrations.RunSQL([
            'CREATE INDEX CONCURRENTLY osf_nodelog_should_hide_nid ON osf_nodelog (should_hide, node_id);',
        ], [
            'DROP INDEX IF EXISTS osf_nodelog_should_hide_nid, RESTRICT;'
        ])
    ]
