# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0060_add_nodelog_should_hide_nid_index'),
        ('osf', '0060_auto_20171011_1300'),
    ]

    operations = [
    ]
