# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 19:38
from __future__ import unicode_literals

from django.db import migrations
from osf.management.commands.add_notification_subscription import add_reviews_notification_setting


def add_reviews_notification_subscription(state, schema_editor):
    add_reviews_notification_setting('global_reviews', state=state)

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0060_reviews'),
    ]

    operations = [
        migrations.RunPython(add_reviews_notification_subscription),
    ]
