# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0061_add_reviews_notification_subscription'),
    ]

    operations = [
    ]
