# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0060_add_nodelog_should_hide_nid_index'),
        ('osf', '0062_accept_preprints'),
    ]

    operations = [
    ]
