# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0063_merge_20171012_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdigest',
            name='message',
            field=models.TextField(),
        ),
    ]
