# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 17:01
from __future__ import unicode_literals

from django.db import migrations

from reviews.workflow import States


# Make sure all submitted preprints have _has_abandoned_preprint=False.
def set_abandoned_false_for_all_submitted_preprints(apps, schema_editor):
    Preprint = apps.get_model('osf', 'PreprintService')
    abandoned_submitted_preprints = Preprint.objects.filter(node___has_abandoned_preprint=True).exclude(reviews_state=States.INITIAL.value)
    for preprint in abandoned_submitted_preprints.iterator():
        preprint.node._has_abandoned_preprint=False
        preprint.node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0064_merge_20171012_1215'),
    ]

    operations = [
        migrations.RunPython(
            set_abandoned_false_for_all_submitted_preprints
        ),
    ]
