# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0065_preprintservice_original_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftregistration',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
