# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0065_preprintservice_original_publication_date'),
        ('osf', '0061_auto_20171026_1216'),
    ]

    operations = [
    ]
