# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:44
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0065_preprintservice_original_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftregistration',
            name='deleted',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
    ]
