# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0065_preprintservice_original_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefilenode',
            name='node',
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basefilenode',
            name='is_root',
            field=models.NullBooleanField(default=False),
        )
    ]
