# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0061_merge_20171016_0838'),
        ('osf', '0065_preprintservice_original_publication_date'),
    ]

    operations = [
    ]
