# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0065_preprintservice_original_publication_date'),
        ('osf', '0065_auto_20171024_1330'),
    ]

    operations = [
    ]
