# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0066_add_file_fields_for_target'),
    ]

    operations = [
        migrations.RunSQL(
            ["""
        UPDATE osf_basefilenode
        SET target_object_id = node_id;
        UPDATE osf_basefilenode
        SET target_content_type_id = (SELECT id FROM django_content_type WHERE app_label = 'osf' AND model = 'abstractnode');
        """], ["""
        UPDATE osf_basefilenode
        SET target_object_id = NULL;
        UPDATE osf_basefilenode
        SET target_content_type = NULL;
        """]
        ),
    ]
