# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:19
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0067_auto_20171121_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintservice',
            name='preprint_doi_created',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
    ]
