# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0067_migrate_node_info_for_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefilenode',
            name='node',
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
