# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:19
from __future__ import unicode_literals
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0068_preprintservice_preprint_doi_created'),
    ]

    operations = [
    ]
