# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0068_draftregistration_deleted'),
        ('osf', '0070_auto_20171121_1805'),
    ]

    operations = [
    ]
