# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0070_merge_20171127_2232'),
        ('osf', '0071_merge_20171128_0950'),
    ]

    operations = [
    ]
