# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 21:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0074_parse_citation_styles'),
        ('osf', '0074_auto_20171207_1331'),
    ]

    operations = [
    ]
