# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 19:09


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0075_merge_20171207_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='ReviewAction',
        ),
        migrations.RenameField(
            model_name='preprintservice',
            old_name='reviews_state',
            new_name='machine_state',
        ),
    ]
