# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 19:33


import logging

from django.db import migrations
from osf.utils.migrations import ensure_schemas, remove_schemas


logger = logging.getLogger(__file__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0076_action_rename'),
    ]

    operations = [
        migrations.RunPython(ensure_schemas, remove_schemas),
    ]
