# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0076_action_rename'),
        ('osf', '0076_merge_20171221_0948'),
    ]

    operations = [
    ]
