# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 17:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0077_preprintprovider_facebook_app_id'),
        ('osf', '0077_add_maintenance_permissions'),
    ]

    operations = [
    ]
