# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 18:06


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0078_add_banner_permissions'),
        ('osf', '0077_add_maintenance_permissions'),
        ('osf', '0077_ensure_schemas'),
    ]

    operations = [
    ]
