# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0079_merge_20180207_1545'),
        ('osf', '0079_auto_20180207_1017'),
    ]

    operations = [
    ]
