# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0079_merge_20180207_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprintprovider',
            name='preprint_word',
            field=models.CharField(choices=[(b'preprint', b'Preprint'), (b'paper', b'Paper'), (b'thesis', b'Thesis'), (b'work', b'Work'), (b'none', b'None')], default=b'preprint', max_length=10),
        ),
    ]
