# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 10:13
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0047_auto_20171213_0029'),
        ('osf', '0079_merge_20180207_1545'),
    ]

    operations = [
    ]
