# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0079_merge_20180207_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('project_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('date', osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('path', models.CharField(db_index=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='RdmAddonNoInstitutionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('provider', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_forced', models.BooleanField(default=False)),
                ('is_allowed', models.BooleanField(default=True)),
                ('external_accounts', models.ManyToManyField(blank=True, to='osf.ExternalAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdmAddonOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('is_forced', models.BooleanField(default=False)),
                ('is_allowed', models.BooleanField(default=True)),
                ('external_accounts', models.ManyToManyField(blank=True, to='osf.ExternalAccount')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='RdmAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField(max_length=63206)),
                ('announcement_type', models.CharField(max_length=256)),
                ('date_sent', osf.utils.fields.NonNaiveDateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdmAnnouncementOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('twitter_api_key', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('twitter_api_secret', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('twitter_access_token', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('twitter_access_token_secret', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('facebook_api_key', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('facebook_api_secret', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('facebook_access_token', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('redmine_api_url', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('redmine_api_key', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdmFcmDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('device_token', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('date_created', osf.utils.fields.NonNaiveDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdmFileTimestamptokenVerifyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('key_file_name', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=24)),
                ('project_id', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=25, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('timestamp_token', models.BinaryField(blank=True, null=True)),
                ('inspection_result_status', models.IntegerField(default=0)),
                ('create_user', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('validation_user', models.IntegerField(blank=True, null=True)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('update_user', models.IntegerField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdmStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('provider', models.CharField(db_index=True, max_length=50, null=True)),
                ('storage_account_id', models.CharField(max_length=256, null=True)),
                ('project_root_path', models.CharField(max_length=256)),
                ('extention_type', models.CharField(max_length=10, null=True)),
                ('subtotal_file_number', models.BigIntegerField()),
                ('subtotal_file_size', models.FloatField()),
                ('date_acquired', models.DateField()),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.Institution')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RdmTimestampGrantPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('node_guid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp_pattern_division', models.IntegerField(default=1)),
                ('is_forced', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='RdmUserKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('guid', models.IntegerField()),
                ('key_name', models.CharField(max_length=50)),
                ('key_kind', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('delete_flag', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'permissions': (('mark_spam', 'Can mark comments, projects and registrations as spam'), ('view_spam', 'Can view nodes, comments, and projects marked as spam'), ('view_metrics', 'Can view metrics on the OSF Admin app'), ('view_prereg', 'Can view entries for the preregistration chellenge on the admin'), ('administer_prereg', 'Can update, comment on, and approve entries to the prereg challenge'), ('view_desk', 'Can view details about Desk users'), ('view_announcement', 'Can view announcement on the RDM Admin app'))},
        ),
        migrations.AlterUniqueTogether(
            name='rdmtimestampgrantpattern',
            unique_together=set([('institution', 'node_guid')]),
        ),
        migrations.AlterUniqueTogether(
            name='rdmaddonoption',
            unique_together=set([('provider', 'institution')]),
        ),
    ]
