# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0080_add_abstractprovider'),
    ]

    operations = [
    ]
