# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 15:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0080_ensure_schemas'),
        ('osf', '0079_merge_20180202_1206'),
    ]

    operations = [
    ]
