# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0081_auto_20180226_0415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CGGroup',
        ),
        migrations.RenameField(
            model_name='osfuser',
            old_name='groups_admin',
            new_name='cggroups_admin',
        ),
        migrations.RenameField(
            model_name='osfuser',
            old_name='groups_initialized',
            new_name='cggroups_initialized',
        ),
        migrations.RenameField(
            model_name='osfuser',
            old_name='groups_sync',
            new_name='cggroups_sync',
        ),
        migrations.AddField(
            model_name='osfuser',
            name='cggroups',
            field=models.ManyToManyField(related_name='users_group', to='osf.CGGroup'),
        ),
        migrations.AlterField(
            model_name='osfuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]

