# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 21:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0077_add_noderequest_model'),
        ('osf', '0081_merge_20180212_0949'),
    ]

    operations = [
    ]
