# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0081_alter_abstractprovider_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractprovider',
            name='preprint_word',
            field=models.CharField(choices=[(b'preprint', b'Preprint'), (b'paper', b'Paper'), (b'thesis', b'Thesis'), (b'work', b'Work'), (b'none', b'None')], default=b'preprint', max_length=10, null=True),
        ),
    ]
