# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0081_add_ember_waffle_flags'),
        ('osf', '0080_ensure_schemas'),
    ]

    operations = [
    ]
