# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0082_merge_20180213_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprintContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='preprintservice',
            options={'permissions': (('view_preprintservice', 'Can view preprint service details in the admin app.'), ('ADMIN', 'Can do anything the preprint'), ('EDIT', 'Can edit the preprint'), ('READ', 'Can read the preprint'))},
        ),
        migrations.AddField(
            model_name='preprintcontributor',
            name='preprintservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.PreprintService'),
        ),
        migrations.AddField(
            model_name='preprintcontributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='_contributors',
            field=models.ManyToManyField(related_name='preprintservices', through='osf.PreprintContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='preprintcontributor',
            unique_together=set([('user', 'preprintservice')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='preprintcontributor',
            order_with_respect_to='preprintservice',
        ),
    ]
