# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-29 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0080_auto_20180423_0634'),
        ('osf', '0082_auto_20180313_0039'),
    ]

    operations = [
    ]

