# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 20:29
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0082_merge_20180213_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfuser',
            name='change_password_last_attempt',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
    ]
