# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0082_merge_20180213_1502'),
    ]

    operations = [
    ]
