# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 17:45
from __future__ import unicode_literals
from waffle.models import Flag
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0002_auto_20161201_0958'),
    ]

    operations = [
    ]
