# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 22:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0082_add_preprint_word_choice'),
        ('osf', '0082_merge_20180213_1502'),
    ]

    operations = [
    ]
