# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0082_add_preprint_word_choice'),
        ('osf', '0080_ensure_schemas'),
    ]

    operations = [
    ]
