# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 16:14
from __future__ import unicode_literals, division
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    # Avoid locking basefilenode
    atomic = False

    dependencies = [
        ('osf', '0083_add_file_fields_for_target'),
    ]

    operations = [
    ]
