# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0083_auto_20180421_0054'),
        ('osf', '0083_merge_20180528_2128'),
    ]

    operations = [
    ]
