# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0083_add_osf_usagedata'),
        ('osf', '0081_merge_20180212_0949'),
    ]

    operations = [
    ]
