# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0081_auto_20180214_0915'),
        ('osf', '0084_merge_20180308_1821'),
    ]

    operations = [
    ]
