# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0083_merge_20180228_1619'),
        ('osf', '0084_merge_20180308_1821'),
    ]

    operations = [
    ]
