# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 17:21
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0084_preprint_node_divorce'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintservice',
            name='last_logged',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
