# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0085_preprintservice_last_logged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprintservice',
            options={'permissions': (('view_preprintservice', 'Can view preprint service details in the admin app.'), ('read', 'Can read the preprint'), ('write', 'Can write the preprint'), ('admin', 'Can manage the preprint'))},
        ),
    ]
