# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0084_merge_20180308_1821'),
        ('osf', '0086_auto_20180327_1550'),
    ]

    operations = [
    ]
