# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0090_add_collection_groups_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='osf.AbstractProvider'),
        ),
    ]
