# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0092_populate_notification_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='abstractnodes', to='osf.Subject'),
        ),
        migrations.AlterField(
            model_name='preprintservice',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='preprintservices', to='osf.Subject'),
        ),
    ]
