# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 03:41
from __future__ import unicode_literals

from django.db import migrations


def noop(*args, **kwargs):
    # This migration used to update provider group perms,
    # which is now handled by the post_migrate signal
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0093_node_subjects'),
    ]

    operations = [
        migrations.RunPython(noop, noop)
    ]
