# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0094_update_preprintprovider_group_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='allow_commenting',
            field=models.BooleanField(default=False),
        ),
    ]
