# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 20:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0094_update_preprintprovider_group_auth'),
    ]

    operations = [
        migrations.RunSQL(
            """
            SELECT setval(pg_get_serial_sequence('"osf_abstractprovider_licenses_acceptable"','id'),
                        coalesce(max("id"), 1), max("id") IS NOT null)
            FROM "osf_abstractprovider_licenses_acceptable";

            SELECT setval(pg_get_serial_sequence('"osf_abstractprovider"','id'),
                        coalesce(max("id"), 1), max("id") IS NOT null)
            FROM "osf_abstractprovider";
            """,
            """
            SELECT setval(pg_get_serial_sequence('"osf_abstractprovider_licenses_acceptable"','id'), 1, max("id") IS NOT null)
            FROM "osf_abstractprovider_licenses_acceptable";

            SELECT setval(pg_get_serial_sequence('"osf_abstractprovider"','id'), 1, max("id") IS NOT null)
            FROM "osf_abstractprovider_licenses_acceptable";
            """
        ),
    ]
