# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0094_update_preprintprovider_group_auth'),
        ('osf', '0085_ensure_licenses'),
    ]

    operations = [
    ]
