# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 17:11


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0095_collectedguidmetadata_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='primary_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='osf.Collection'),
        ),
    ]
