# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0095_ensure_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='noderequestaction',
            name='permissions',
            field=models.CharField(choices=[(b'admin', 'Admin'), (b'read', 'Read'), (b'write', 'Write')], default=b'read', max_length=5),
        ),
        migrations.AddField(
            model_name='noderequestaction',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='noderequest',
            unique_together=set([]),
        ),
        migrations.RunSQL(
            [
                """
                CREATE UNIQUE INDEX osf_noderequest_target_creator_non_accepted ON osf_noderequest (target_id, creator_id)
                WHERE machine_state != 'accepted';
                """
            ], [
                """
                DROP INDEX IF EXISTS osf_noderequest_target_creator_non_accepted RESTRICT;
                """
            ]
        ),
    ]
