# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 16:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0095_abstractprovider_allow_commenting'),
        ('osf', '0095_ensure_licenses'),
    ]

    operations = [
    ]
