# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0095_ensure_licenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractnode',
            name='wiki_pages_current',
        ),
        migrations.RemoveField(
            model_name='abstractnode',
            name='wiki_pages_versions',
        ),
    ]
