# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 20:39
from __future__ import unicode_literals

import logging
from django.db import migrations, models

from osf.models import PreprintProvider

logger = logging.getLogger(__file__)


PREPRINT_DOI_NAMESPACE = {
    'osf': '10.31219',
    'agrixiv': '10.31220',
    'arabixiv': '10.31221',
    'bitss': '10.31222',
    'eartharxiv': '10.31223',
    'engrxiv': '10.31224',
    'focusarchive': '10.31225',
    'frenxiv': '10.31226',
    'inarxiv': '10.31227',
    'lawarxiv': '10.31228',
    'lissa': '10.31229',
    'marxiv': '10.31230',
    'mindrxiv': '10.31231',
    'nutrixiv': '10.31232',
    'paleorxiv': '10.31233',
    'psyarxiv': '10.31234',
    'socarxiv': '10.31235',
    'sportrxiv': '10.31236',
    'thesiscommons': '10.31237'
}


def add_doi_prefix(*args, **kwargs):
    for key, value in PREPRINT_DOI_NAMESPACE.iteritems():
        provider =  PreprintProvider.objects.filter(_id=key)
        if not provider.exists():
            logger.info('Could not find provider with _id {}, skipping for now...'.format(key))
            continue
        provider = provider.get()
        provider.doi_prefix = value
        provider.save()


def remove_doi_prefix(*args, **kwargs):
    # Reverse migration not needed, as removing the field
    # will remove all values from the field
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0095_add_url_to_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='doi_prefix',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(add_doi_prefix, remove_doi_prefix)
    ]
