# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0096_merge_20180413_1110'),
        ('osf', '0096_auto_20180415_1649'),
    ]

    operations = [
    ]
