# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0096_ensure_schemas'),
        ('osf', '0096_modify_noderequestaction_noderequest'),
    ]

    operations = [
    ]
