# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0096_ensure_schemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledbanner',
            name='link',
            field=models.URLField(blank=True, default=b'https://www.crowdrise.com/centerforopenscience'),
        ),
    ]
