# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0097_merge_20180416_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdigest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractProvider'),
        ),
    ]
