# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0097_merge_20180416_1533'),
        ('osf', '0097_merge_20180416_1453'),
    ]

    operations = [
    ]
