# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 20:16


from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0098_merge_20180424_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedSHAREPreprintProvider',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
