# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 15:57
from __future__ import unicode_literals

import logging

from django.db import migrations
from django.apps import apps


logger = logging.getLogger(__file__)

osfstorage_config = apps.get_app_config('addons_osfstorage')


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0004_storage_region_models'),
        ('osf', '0098_merge_20180416_1807'),
    ]

    operations = [
    ]
