# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0085_finalize_file_node_to_target'),
        ('osf', '0098_merge_20180416_1807'),
    ]

    operations = [
    ]
