# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0098_merge_20180416_1807'),
        ('osf', '0098_auto_20180418_1722'),
    ]

    operations = [
    ]
