# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0098_merge_20180416_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractnode',
            name='wiki_pages_current',
        ),
        migrations.RemoveField(
            model_name='abstractnode',
            name='wiki_pages_versions',
        ),
    ]
