# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 13:42


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0099_whitelistedsharepreprintprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdigest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractProvider'),
        ),
    ]
