# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    # Avoid locking the osf_abstractnode table
    atomic = False

    dependencies = [
        ('osf', '0099_merge_20180427_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderequestaction',
            name='permissions',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', max_length=5),
        ),
    ]
