# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0100_notificationdigest_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAssetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=63)),
                ('file', models.FileField(upload_to=b'assets')),
                ('providers', models.ManyToManyField(blank=True, related_name='asset_files', to='osf.AbstractProvider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
