# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0100_notificationdigest_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintservice',
            name='date_retracted',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='ever_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='retraction_justification',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
