# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0099_migrate_comments_on_deleted_objects'),
        ('osf', '0100_set_access_request_enabled'),
    ]

    operations = [
    ]
