# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0099_merge_20180426_0930'),
        ('osf', '0100_set_access_request_enabled'),
    ]

    operations = [
    ]
