# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 13:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0099_add_default_storage_region'),
        ('osf', '0099_file_version_user_metadata'),
        ('osf', '0101_merge_20180508_1011'),
    ]

    operations = [
    ]
