# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0103_set_osf_storage_node_settings_region'),
        ('osf', '0101_merge_20180514_1932'),
    ]

    operations = [
    ]
