# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0103_transfer_preprint_service_permissions'),
        ('osf', '0099_merge_20180505_1027'),
    ]

    operations = [
    ]
