# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 17:40


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0103_set_osf_storage_node_settings_region'),
        ('osf', '0100_notificationdigest_provider'),
    ]

    operations = [
    ]
