# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0104_merge_20180523_1240'),
        ('osf', '0104_merge_20180524_1621'),
    ]

    operations = [
    ]
