# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0105_merge_20180525_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalaccount',
            name='port',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
