# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0105_merge_20180525_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='citationstyle',
            name='parent_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
