# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0105_add_identifier_deleted_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
