# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.spam
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0107_add_dependent_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='ProviderAssetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=63)),
                ('file', models.FileField(upload_to=b'assets')),
                ('providers', models.ManyToManyField(blank=True, related_name='asset_files', to='osf.AbstractProvider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='date_last_reported',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='date_retracted',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='ever_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='reports',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, validators=[osf.models.spam._validate_reports]),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='retraction_justification',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='spam_data',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='spam_pro_tip',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preprintservice',
            name='spam_status',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scheduledbanner',
            name='link',
            field=models.URLField(blank=True, default=b'https://www.crowdrise.com/centerforopenscience'),
        ),
        migrations.AlterUniqueTogether(
            name='dismissedalert',
            unique_together=set([('_id', 'location')]),
        ),
    ]
