# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 14:47
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Permission
from django.core.management.sql import emit_post_migrate_signal
from osf.models import OSFUser



def unmigrate_preprint_service_permissions(state, schema):
    emit_post_migrate_signal(2, False, 'default')

    # New permission groups
    add_preprint = Permission.objects.get(codename='add_preprint')
    change_preprint = Permission.objects.get(codename='change_preprint')
    delete_preprint = Permission.objects.get(codename='delete_preprint')
    osf_admin_view_preprint = Permission.objects.get(codename='osf_admin_view_preprint')

    remove_users_from_permission(add_preprint)
    remove_users_from_permission(change_preprint)
    remove_users_from_permission(delete_preprint)
    remove_users_from_permission(osf_admin_view_preprint)

def remove_users_from_permission(perm):
    for user in OSFUser.objects.filter(user_permissions=perm):
        user.user_permissions.remove(perm)

def add_users_to_renamed_permission(old_perm, new_perm):
    if old_perm:
        for user in OSFUser.objects.filter(user_permissions=old_perm):
            user.user_permissions.add(new_perm)

def migrate_preprint_service_permissions(state, schema):
    # this is to make sure that the permissions created earlier exist!
    emit_post_migrate_signal(2, False, 'default')
    # Old permission groups
    add_preprintservice = Permission.objects.filter(codename='add_preprintservice').first()
    change_preprintservice = Permission.objects.filter(codename='change_preprintservice').first()
    delete_preprintservice = Permission.objects.filter(codename='delete_preprintservice').first()
    view_preprintservice = Permission.objects.filter(codename='view_preprintservice').first()

    # New permission groups
    add_preprint = Permission.objects.get(codename='add_preprint')
    change_preprint = Permission.objects.get(codename='change_preprint')
    delete_preprint = Permission.objects.get(codename='delete_preprint')
    osf_admin_view_preprint = Permission.objects.get(codename='osf_admin_view_preprint')


    add_users_to_renamed_permission(add_preprintservice, add_preprint)
    add_users_to_renamed_permission(change_preprintservice, change_preprint)
    add_users_to_renamed_permission(delete_preprintservice, delete_preprint)
    add_users_to_renamed_permission(view_preprintservice, osf_admin_view_preprint)

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0107_preprint_node_divorce'),
    ]

    operations = [
        migrations.RunPython(migrate_preprint_service_permissions, unmigrate_preprint_service_permissions),
    ]
