# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0108_auto_20180618_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
