# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 19:10


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0108_auto_20180530_1310'),
        ('osf', '0106_auto_20180601_1341'),
    ]

    operations = [
    ]
