# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0109_auto_20180605_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprintservice',
            old_name='date_retracted',
            new_name='date_withdrawn',
        ),
        migrations.RenameField(
            model_name='preprintservice',
            old_name='retraction_justification',
            new_name='withdrawal_justification',
        ),
    ]
