# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0109_merge_20180611_1410'),
    ]

    operations = [
    ]
