# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0110_set_ever_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderequest',
            name='machine_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='initial', max_length=15),
        ),
        migrations.AlterField(
            model_name='noderequestaction',
            name='from_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=31),
        ),
        migrations.AlterField(
            model_name='noderequestaction',
            name='to_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=31),
        ),
        migrations.AlterField(
            model_name='noderequestaction',
            name='trigger',
            field=models.CharField(choices=[('submit', 'Submit'), ('accept', 'Accept'), ('reject', 'Reject'), ('edit_comment', 'Edit_Comment')], max_length=31),
        ),
        migrations.AlterField(
            model_name='preprintservice',
            name='machine_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='initial', max_length=15),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='from_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=31),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='to_state',
            field=models.CharField(choices=[('initial', 'Initial'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=31),
        ),
        migrations.AlterField(
            model_name='reviewaction',
            name='trigger',
            field=models.CharField(choices=[('submit', 'Submit'), ('accept', 'Accept'), ('reject', 'Reject'), ('edit_comment', 'Edit_Comment'), ('withdraw', 'Withdraw')], max_length=31),
        ),
        migrations.RenameField(
            model_name='preprintservice',
            old_name='date_retracted',
            new_name='date_withdrawn',
        ),
        migrations.RenameField(
            model_name='preprintservice',
            old_name='retraction_justification',
            new_name='withdrawal_justification',
        ),
    ]
