# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0107_merge_20180604_1232'),
        ('osf', '0111_auto_20180605_1240'),
    ]

    operations = [
    ]
