# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 13:15


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0111_auto_20180605_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionprovider',
            options={'permissions': (('view_collectionprovider', 'Can view collection provider details'),)},
        ),
    ]
