# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0112_ensure_schemas'),
        ('osf', '0106_merge_20180531_0919'),
    ]

    operations = [
    ]
