# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0109_externalaccount_nickname'),
        ('osf', '0112_ensure_schemas'),
    ]

    operations = [
    ]
