# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 18:08
from __future__ import unicode_literals

import logging
from django.db import migrations

from osf.models import PreprintProvider

logger = logging.getLogger(__file__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0112_merge_20180614_1454'),
    ]

    operations = [
    ]
