# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0113_auto_20180615_1308'),
        ('osf', '0112_ensure_schemas'),
    ]

    operations = [
    ]
