# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 18:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0113_add_view_collectionprovider_to_admin_perm'),
        ('osf', '0112_ensure_schemas'),
    ]

    operations = [
    ]
