# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0114_merge_20180621_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerassetfile',
            name='name',
            field=models.CharField(choices=[(b'favicon', b'favicon'), (b'powered_by_share', b'powered_by_share'), (b'sharing', b'sharing'), (b'square_color_no_transparent', b'square_color_no_transparent'), (b'square_color_transparent', b'square_color_transparent'), (b'style', b'style'), (b'wide_black', b'wide_black'), (b'wide_color', b'wide_color'), (b'wide_white', b'wide_white')], max_length=63),
        ),
    ]
