# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:53
from __future__ import unicode_literals

import logging
from django.db import migrations

from osf.models import PreprintProvider

logger = logging.getLogger(__file__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0114_merge_20180628_1234'),
    ]

    operations = [
    ]
