# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0115_auto_20180628_1253'),
        ('osf', '0106_merge_20180531_0919'),
    ]

    operations = [
    ]
