# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0115_auto_20180628_1253'),
        ('osf', '0115_auto_20180621_1324'),
    ]

    operations = [
    ]
