# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 17:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0116_osfuser_deleted'),
        ('osf', '0116_merge_20180703_2258'),
    ]

    operations = [
    ]
