# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0116_merge_20180703_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProvider',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'permissions': (('view_registrationprovider', 'Can view registration provider details'),),
            },
            bases=('osf.abstractprovider',),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='type',
            field=models.CharField(choices=[('osf.collectionprovider', 'collection provider'), ('osf.registrationprovider', 'registration provider'), ('osf.preprintprovider', 'preprint provider')], db_index=True, max_length=255),
        ),
    ]
