# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 17:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0117_merge_20180712_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerassetfile',
            options={'permissions': (('view_providerassetfile', 'Can view provider asset files'),)},
        ),
    ]
