# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0119_add_registrationprovider_perms_to_admin'),
        ('osf', '0119_add_asset_perms'),
    ]

    operations = [
    ]
