# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 22:19
from __future__ import unicode_literals

from django.db import migrations


def noop(*args):
    # This migration used to handle admin permissions
    # This is now handled by the post_migrate signal
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0120_merge_20180716_1457'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
