# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0123_auto_20180726_1546'),
        ('osf', '0122_auto_20180801_2105'),
    ]

    operations = [
    ]
