# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0123_merge_20180803_1346'),
        ('osf', '0121_remove_wiki_fields_from_node'),
    ]

    operations = [
    ]
