# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0123_merge_20180803_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='custom_citation_text',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
