# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0123_merge_20180802_2004'),
        ('osf', '0123_merge_20180803_1346'),
    ]

    operations = [
    ]
