# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0121_remove_support_page_waffle_flag'),
        ('osf', '0123_merge_20180803_1346'),
    ]

    operations = [
    ]
