# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0124_merge_20180816_1229'),
        ('osf', '0124_merge_20180808_1451'),
    ]

    operations = [
    ]
