# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 20:39
from __future__ import unicode_literals

import logging
from tqdm import tqdm

from django.db import migrations, connection


logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0125_merge_20180824_1856'),
    ]

    operations = [
    ]
