# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0004_storage_region_models'),
        ('osf', '0125_merge_20180822_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='region',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region'),
        ),
    ]
