# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 17:06
from __future__ import unicode_literals

import logging

from django.db import migrations, models
import django.db.models.deletion
from django.apps import apps

from addons.osfstorage.settings import DEFAULT_REGION_ID, DEFAULT_REGION_NAME

logger = logging.getLogger(__name__)


BATCHSIZE = 5000


def add_regions_to_existing_versions(*args, **kwargs):
    Region = apps.get_model('addons_osfstorage.region')
    FileVersion = apps.get_model('osf.fileversion')
    default_region = Region.objects.get(
        _id=DEFAULT_REGION_ID,
        name=DEFAULT_REGION_NAME,
    )
    max_pk = FileVersion.objects.aggregate(models.Max('pk'))['pk__max']
    if max_pk is not None:
        for offset in range(0, max_pk + 1, BATCHSIZE):
            (FileVersion.objects
                .filter(pk__gte=offset)
                .filter(pk__lt=offset + BATCHSIZE)
                .filter(basefilenode__provider='osfstorage')
                .filter(region__isnull=True)
                .update(region=default_region))
            logger.info(
                'Updated osf_fileversions {}-{}/{}'.format(
                    offset,
                    offset + BATCHSIZE,
                    max_pk,
                )
            )

def remove_regions_from_versions(*args, **kwargs):
    # Reverse migration will remove fk field, no need to reset manually
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('addons_osfstorage', '0004_storage_region_models'),
        ('osf', '0125_merge_20180822_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='region',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region'),
        ),
        migrations.RunPython(add_regions_to_existing_versions, remove_regions_from_versions)
    ]
