# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 20:20
from __future__ import unicode_literals

import logging

from django.db import migrations, models
from django.apps import apps

from addons.osfstorage.settings import DEFAULT_REGION_ID, DEFAULT_REGION_NAME

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('osf', '0130_fileversion_region'),
    ]

    operations = [
    ]
