# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0127_add_regions_to_all_versions'),
        ('osf', '0125_merge_20180824_1856'),
    ]

    operations = [
    ]
