# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0127_merge_20180822_1927'),
        ('osf', '0125_merge_20180824_1856'),
    ]

    operations = [
    ]
