# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0128_merge_20180829_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osfuser',
            name='is_claimed',
        ),
    ]
