# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-31 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0128_merge_20180829_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='custom_citation',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
