# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0004_storage_region_models'),
        ('osf', '0129_merge_20180910_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region'),
        ),
    ]
