# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0130_add_guardian_to_nodes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={},
        ),
        migrations.AlterModelOptions(
            name='preprint',
            options={'permissions': (('view_preprint', 'Can view preprint details in the admin app'), ('read_preprint', 'Can read the preprint'), ('write_preprint', 'Can write the preprint'), ('admin_preprint', 'Can manage the preprint'))},
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='read',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='write',
        ),
        migrations.RemoveField(
            model_name='institutionalcontributor',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='institutionalcontributor',
            name='read',
        ),
        migrations.RemoveField(
            model_name='institutionalcontributor',
            name='write',
        ),
    ]
