# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-13 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0124_merge_20180815_1924'),
        ('osf', '0130_create_cache_table'),
    ]

    operations = [
    ]
