# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0130_fileversion_region'),
        ('osf', '0130_merge_20180914_1414'),
    ]

    operations = [
    ]
