# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0125_merge_20180822_1508'),
        ('osf', '0129_merge_20180904_2028'),
        ('osf', '0131_merge_20180914_1937'),
    ]

    operations = [
    ]
