# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0132_osfgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfgroup',
            name='content_type_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
