# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0132_merge_20180914_2001'),
        ('osf', '0130_auto_20180912_2039'),
    ]

    operations = [
    ]
