# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0132_merge_20180914_2001'),
        ('osf', '0125_add_datacite_file_metadata_schema'),
    ]

    operations = [
    ]
