# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0133_auto_20180905_0156'),
        ('osf', '0133_osfgroup_content_type_pk'),
    ]

    operations = [
    ]
