# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0133_merge_20180920_2022'),
        ('osf', '0133_merge_20180921_0025'),
    ]

    operations = [
    ]
