# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0134_abstractnode_custom_citation'),
    ]

    operations = [
    ]
