# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0084_merge_20180702_0200'),
        ('osf', '0134_abstractnode_custom_citation'),
    ]

    operations = [
    ]
