# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 13:51
from __future__ import unicode_literals
import logging

from django.db import migrations

logger = logging.getLogger(__file__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0134_add_provider_reg_fks'),
    ]

    operations = [
    ]
