# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 14:20
from __future__ import unicode_literals

from django.db import migrations

from osf.utils.migrations import AddWaffleFlags


USER_SETTINGS_FLAGS = [
    'ember_user_settings_account_page',
    'ember_user_settings_addons_page',
    'ember_user_settings_notifications_page',
    'ember_user_settings_apps_page',
    'ember_user_settings_tokens_page',
]


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0134_abstractnode_custom_citation'),
    ]

    operations = [
        AddWaffleFlags(USER_SETTINGS_FLAGS),
    ]
