# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0134_add_fm_record_to_osfstorage_files'),
        ('osf', '0134_abstractnode_custom_citation'),
    ]

    operations = [
    ]
