# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0135_merge_20190212_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'permissions': (('mark_spam', 'Can mark comments, projects and registrations as spam'), ('view_spam', 'Can view nodes, comments, and projects marked as spam'), ('view_metrics', 'Can view metrics on the GakuNin RDM Admin app'), ('view_prereg', 'Can view entries for the preregistration chellenge on the admin'), ('administer_prereg', 'Can update, comment on, and approve entries to the prereg challenge'), ('view_desk', 'Can view details about Desk users'), ('delete_preprintrequest', 'Can delete preprints withdrawal requests'), ('change_preprintrequest', 'Can update preprints withdrawal requests'), ('view_announcement', 'Can view announcement on the RDM Admin app'))},
        ),
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='update_date',
            new_name='upload_file_created_at',
        ),
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='update_user',
            new_name='upload_file_created_user',
        ),
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='validation_date',
            new_name='upload_file_modified_at',
        ),
        migrations.RenameField(
            model_name='rdmfiletimestamptokenverifyresult',
            old_name='validation_user',
            new_name='upload_file_modified_user',
        ),
        migrations.RemoveField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='create_user',
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='upload_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_file_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_file_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='verify_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
