# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0135_migrate_registrations_to_osf_registries_provider'),
        ('osf', '0134_abstractnode_custom_citation'),
    ]

    operations = [
    ]
