# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 13:01
from __future__ import unicode_literals
from django.db import migrations

from osf import features
from osf.utils.migrations import AddWaffleFlags

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0135_user_settings_waffles'),
    ]

    operations = [
        AddWaffleFlags([features.EMBER_AUTH_REGISTER]),
    ]
