# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0136_auto_20190308_0043'),
        ('osf', '0086_auto_20190417_0000'),
    ]

    operations = [
    ]
