# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 15:18
from __future__ import unicode_literals

from django.db import migrations, connection


def remove_records_from_files(state, schema):
    FileMetadatRecord = state.get_model('osf', 'filemetadatarecord')
    FileMetadatRecord.objects.all().delete()

def add_records_to_files_sql(state, schema):
    FileMetadataSchema = state.get_model('osf', 'filemetadataschema')
    datacite_schema_id = FileMetadataSchema.objects.filter(_id='datacite').values_list('id', flat=True)[0]
    sql = """
    INSERT INTO osf_filemetadatarecord (created, modified, _id, metadata, id, file_id, schema_id)
    SELECT  NOW(), NOW(), generate_object_id(), '{}', nextval('osf_filemetadatarecord_id_seq'), OSF_FILE.id, %d
        FROM osf_basefilenode OSF_FILE
            LEFT OUTER JOIN osf_filemetadatarecord ON
                (OSF_FILE.id = osf_filemetadatarecord.file_id)
            WHERE (OSF_FILE.type = 'osf.osfstoragefile'
                   AND OSF_FILE.provider = 'osfstorage'
                   AND osf_filemetadatarecord.id IS NULL
            );
    """ % (datacite_schema_id)

    with connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0136_add_datacite_file_metadata_schema'),
    ]

    operations = [
        migrations.RunPython(add_records_to_files_sql, remove_records_from_files),
    ]
