# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-10 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0129_remove_osfuser_is_claimed'),
        ('osf', '0136_add_ember_auth_register_waffle_flag'),
    ]

    operations = [
    ]
