# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 15:18
from __future__ import unicode_literals
from math import ceil
import logging

from django.db import migrations, connection

logger = logging.getLogger(__name__)

increment = 500000



class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0136_add_datacite_file_metadata_schema'),
    ]

    operations = [
    ]
