# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-12 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0136_auto_20190308_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAPProfile',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('eppn', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('oauth_access_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('oauth_refresh_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('oauth_refresh_time', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='abstractnode',
            name='map_group_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='map_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osf.MAPProfile'),
        ),
    ]
