# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0136_merge_20181010_2242'),
        ('osf', '0136_add_ember_auth_register_waffle_flag'),
    ]

    operations = [
    ]
