# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0137_merge_20190508_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdmaddonoption',
            name='organizational_node',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode'),
        ),
        migrations.AddField(
            model_name='rdmaddonnoinstitutionoption',
            name='organizational_node',
            field=models.ForeignKey(null=True, blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode'),
        ),
    ]
