# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0137_merge_20181011_1525'),
        ('osf', '0137_auto_20181012_1756'),
    ]

    operations = [
    ]
