# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0137_timestamptask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdmfiletimestamptokenverifyresult',
            name='file_id',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
