# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0137_timestamptask'),
        ('osf', '0137_fileinfo_userquota'),
    ]

    operations = [
    ]
