# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0137_auto_20190327_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cggroup',
            old_name='geoup_key',
            new_name='group_key',
        ),
        migrations.AlterField(
            model_name='cggroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
