# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0138_ensure_subjects_and_providers'),
        ('osf', '0138_merge_20181012_1944'),
    ]

    operations = [
    ]
