# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0138_ensure_subjects_and_providers'),
        ('osf', '0138_add_chronos_models'),
    ]

    operations = [
    ]
