# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0135_user_settings_waffles'),
        ('osf', '0138_remove_node_preprint_fields'),
    ]

    operations = [
    ]
