# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-21 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0138_auto_20190513_0817'),
        ('osf', '0138_auto_20190603_1531'),
    ]

    operations = [
    ]
