# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-03 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0138_merge_20190403_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='storage_type',
            field=models.IntegerField(choices=[(1, b'NII Storage'), (2, b'Custom Storage')], default=1),
        ),
        migrations.AddField(
            model_name='userquota',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
