# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0129_remove_osfuser_is_claimed'),
        ('osf', '0139_merge_20181019_0412'),
    ]

    operations = [
    ]
