# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-15 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0140_auto_20190405_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('storage_type', models.IntegerField(choices=[(1, b'NII Storage'), (2, b'Custom Storage')], default=1)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
