# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0139_rename_aspredicted_schema'),
        ('osf', '0140_merge_20181022_1446'),
    ]

    operations = [
    ]
