# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0140_auto_20190405_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
