# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0141_merge_20181023_1526'),
        ('osf', '0140_update_schema_data'),
    ]

    operations = [
    ]
