# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 21:29
from __future__ import unicode_literals
from django.db import migrations
from osf.utils.migrations import DeleteWaffleFlags
from osf.features import EMBER_PROJECT_FORKS


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0141_merge_20181023_1526'),
    ]

    operations = [
        DeleteWaffleFlags([EMBER_PROJECT_FORKS])
    ]
