# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 15:13
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('osf', '0142_remove_forks_flag'),
    ]
    operations = [
    ]
