# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models, connection
import django.db.models.deletion


def reverse_func(state, schema):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE osf_pagecounter
            SET (action, guid_id, file_id, version) = ('download', NULL, NULL, NULL);
            """
        )

def separate_pagecounter_id(state, schema):
    """
    Splits the data in pagecounter _id field of form action:guid_id:file_id:version into
    four new columns: action(char), guid(fk), file(fk), version(int)
    """
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE osf_pagecounter PC
            SET (action, guid_id, file_id, version) = (split_part(PC._id, ':', 1), G.id, F.id, NULLIF(split_part(PC._id, ':', 4), '')::int)
            FROM osf_guid G, osf_basefilenode F
            WHERE PC._id LIKE '%' || G._id || '%'
            AND PC._id LIKE '%' || F._id || '%';
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0141_merge_20181023_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecounter',
            name='action',
            field=models.CharField(default=b'download', max_length=128, db_index=True),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagecounters', to='osf.BaseFileNode'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='guid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagecounters', to='osf.Guid'),
        ),
        migrations.AddField(
            model_name='pagecounter',
            name='version',
            field=models.IntegerField(blank=True, null=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='pagecounter',
            index_together=set([('action', 'guid', 'file', 'version')]),
        ),
        migrations.RunPython(
            separate_pagecounter_id, reverse_func
        ),
    ]
