# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-23 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0141_projectstoragetype'),
        ('osf', '0141_auto_20190418_0751'),
    ]

    operations = [
    ]
