# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0141_merge_20181023_1526'),
        ('osf', '0142_merge_20181015_1554'),
    ]

    operations = [
    ]
