# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0005_region_mfr_url'),
        ('osf', '0142_merge_20190423_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.ExternalAccount')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
