# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models

"""
2-part migration to make scopes an m2m field instead of a charfield on tokens

This migration:
1. Makes scopes field nullable
2. Adds a scopes_temp field
3. Copies scopes information from scopes field to scopes temp (char -> m2m)

0140_auto_20181018_0008:
1. Removes old scopes field (charfield)
2. Renames scopes_temp -> scopes

"""

def remove_m2m_scopes(state, schema):
    ApiOAuth2PersonalToken = state.get_model('osf', 'apioauth2personaltoken')
    tokens = ApiOAuth2PersonalToken.objects.all()
    for token in tokens:
        token.scopes = ' '.join([scope.name for scope in token.scopes_temp.all()])
        token.scopes_temp.clear()
        token.save()

def migrate_scopes_from_char_to_m2m(state, schema):
    ApiOAuth2PersonalToken = state.get_model('osf', 'apioauth2personaltoken')
    ApiOAuth2Scope = state.get_model('osf', 'apioauth2scope')

    tokens = ApiOAuth2PersonalToken.objects.all()
    # Loop inside loop? How many tokens do we have on prod?
    for token in tokens:
        string_scopes = token.scopes.split(' ')
        for scope in string_scopes:
            token.scopes_temp.add(ApiOAuth2Scope.objects.get(name=scope))
            token.save()

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0142_apioauth2scope_is_public'),
    ]

    # AlterField migration added to set null=True because when reverting 0140_auto_20181018_0008,
    # scopes will be renamed to scopes_temp, and a scopes field will be restored.  That scopes
    # field would be empty until this migration was run, but null needs to be True to all this.
    operations = [
        migrations.AlterField(
            model_name='apioauth2personaltoken',
            name='scopes',
            field=models.CharField(blank=False, null=True, max_length=300)
        ),

        migrations.AddField(
            model_name='apioauth2personaltoken',
            name='scopes_temp',
            field=models.ManyToManyField(related_name='tokens', to='osf.ApiOAuth2Scope'),
        ),
        migrations.RunPython(
            migrate_scopes_from_char_to_m2m,
            remove_m2m_scopes
        )
    ]
