# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0142_merge_20190423_0442'),
        ('osf', '0139_merge_20190517_0633'),
    ]

    operations = [
    ]
