# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-27 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0142_show_inactive_schemas_switch'),
        ('osf', '0143_merge_20181115_1458'),
    ]

    operations = [
    ]
