# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0142_merge_20181025_1435'),
        ('osf', '0143_merge_20181115_1458'),
    ]

    operations = [
    ]
