# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0143_merge_20181023_1807'),
        ('osf', '0142_remove_waffle_analytics_flags'),
    ]

    operations = [
    ]
