# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-03 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0143_regionexternalaccount'),
        ('osf', '0143_merge_20190523_0813'),
    ]

    operations = [
    ]
