# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0143_merge_20181023_1807'),
        ('osf', '0144_merge_20181022_1948'),
    ]

    operations = [
    ]
