# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 16:56
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0144_merge_20181113_1420'),
    ]

    operations = [
    ]
