# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0144_merge_20190603_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccountTemporary',
            fields=[
                ('externalaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osf.ExternalAccount')),
            ],
            options={
                'abstract': False,
            },
            bases=('osf.externalaccount',),
        ),
    ]
