# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 06:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0144_merge_20190603_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccountTemporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('oauth_key', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('oauth_secret', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('refresh_token', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('date_last_refreshed', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('expires_at', osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None)),
                ('provider', models.CharField(max_length=50)),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_id', models.CharField(max_length=255)),
                ('display_name', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
                ('profile_url', osf.utils.fields.EncryptedTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='externalaccounttemporary',
            unique_together=set([('provider', 'provider_id')]),
        ),
    ]
