# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0144_pagecounter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecounter',
            name='_id',
            field=models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=50, unique=True),
        ),
    ]
