# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-26 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0145_auto_20190710_0451'),
        ('osf', '0145_auto_20190708_0623'),
    ]

    operations = [
    ]
