# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0143_merge_20181115_1458'),
        ('osf', '0145_add_preprint_contenttype_to_collections'),
    ]

    operations = [
    ]
