# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0142_change_registration_schemas'),
        ('osf', '0146_merge_20181105_1820'),
    ]

    operations = [
    ]
