# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0144_merge_20181129_2128'),
        ('osf', '0146_merge_20181119_2236'),
    ]

    operations = [
    ]
