# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0147_blacklistedemaildomain'),
        ('osf', '0147_repoint_preprint_pagecounters'),
    ]

    operations = [
    ]
