# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 19:31
from __future__ import unicode_literals
import datetime as dt

from django.db import connection
from django.db import migrations
import pytz

dummy_datetime = dt.datetime(1970, 1, 1, tzinfo=pytz.UTC)

def forward(state, *args, **kwargs):
    Preprint = state.get_model('osf', 'Preprint')
    with connection.cursor() as cursor:
        cursor.execute("""
        SELECT applied FROM django_migrations
        WHERE name = '0136_preprint_node_divorce'
        AND app = 'osf'
        """)
        npd_release_date = cursor.fetchone()[0]
    preprints = (
        Preprint.objects
        .filter(created__lt=npd_release_date)
        .filter(node__is_deleted=True, deleted__isnull=True)
    )
    preprints.update(deleted=dummy_datetime)


def backward(state, *args, **kwargs):
    Preprint = state.get_model('osf', 'Preprint')
    preprints = (
        Preprint.objects
        .filter(deleted=dummy_datetime)
    )
    preprints.update(deleted=None)

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0149_add_datacite_doi_switch'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
