# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 19:31
from __future__ import unicode_literals
import datetime as dt

from django.db import connection
from django.db import migrations
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0149_add_datacite_doi_switch'),
    ]

    operations = [
    ]
