# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0150_auto_20180905_0156'),
        ('osf', '0146_merge_20181105_1820'),
    ]

    operations = [
    ]
