# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0151_merge_20181107_1522'),
        ('osf', '0147_merge_20181108_1643'),
    ]

    operations = [
    ]
