# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0152_remove_doi_switches'),
        ('osf', '0152_ensure_schemas'),
    ]

    operations = [
    ]
