# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models
from osf.utils.migrations import disable_auto_now_fields

def add_registration_files_count(state, *args, **kwargs):
    AbstractNode = state.get_model('osf.abstractnode')
    BaseFileNode = state.get_model('osf.basefilenode')
    ContentType = state.get_model('contenttypes', 'ContentType')
    registrations = AbstractNode.objects.filter(type='osf.registration', is_deleted=False)
    content_type = ContentType.objects.get(app_label='osf', model='abstractnode')

    with disable_auto_now_fields(models=[AbstractNode]):
        for registration in registrations:
            job = registration.archive_jobs.first() if registration.archive_jobs.count() else None
            archiving = job and not job.done and (job.status != 'SUCCESS')
            if archiving:
                # Skip stuck, failed, or archiving registrations.
                continue
            registration_files = BaseFileNode.objects.filter(
                target_object_id=registration.id,
                target_content_type=content_type,
                type='osf.osfstoragefile',
                deleted_on__isnull=True)
            registration.files_count = registration_files.count()
            registration.save()

def noop(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0152_ensure_schemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='files_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(add_registration_files_count, noop)
    ]
