# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('osf', '0152_osfgroup_logging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osfgroup',
            options={'permissions': (('member_group', 'Has group membership'), ('manage_group', 'Can manage group membership'), ('groups_read', 'Can view the group'))},
        ),
        migrations.AlterUniqueTogether(
            name='osfgroupgroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
    ]
