# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0137_add_fm_record_to_osfstorage_files'),
        ('osf', '0153_merge_20181221_1842'),
    ]

    operations = [
    ]
