# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0142_merge_20181025_1422'),
        ('osf', '0153_merge_20181221_1842'),
    ]

    operations = [
    ]
