# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 18:52
from __future__ import unicode_literals

from django.db import migrations
from osf.utils.migrations import DeleteWaffleFlags
from osf.features import EMBER_PROJECT_REGISTRATIONS

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0153_merge_20181221_1842'),
    ]

    operations = [
        DeleteWaffleFlags([EMBER_PROJECT_REGISTRATIONS])
    ]
