# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0153_merge_20181221_1842'),
        ('osf', '0142_reinstate_path_unique_constraint'),
    ]

    operations = [
    ]
