# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-22 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0137_add_fm_record_to_osfstorage_files'),
        ('osf', '0154_remove_ember_project_registrations_flag'),
    ]

    operations = [
    ]
