# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import osf.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0154_remove_ember_project_registrations_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='article_doi',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[osf.models.validators.validate_doi]),
        ),
    ]
