# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0155_merge_20190115_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
