# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-26 15:42
from __future__ import unicode_literals

import logging

from django.db import migrations, models
from django_bulk_update.helper import bulk_update

logger = logging.getLogger(__file__)


def populate_fileversion_name(state, *args, **kwargs):
    FileVersion = state.get_model('osf.fileversion')
    file_versions_to_update = []
    for fv in FileVersion.includable_objects.all():
        fv.name = fv.basefilenode_set.first().name
        file_versions_to_update.append(fv)

    bulk_update(file_versions_to_update, update_fields=['name'], batch_size=1000)
    logger.info('Populated `name` on a total of {} file versions'.format(len(file_versions_to_update)))

def noop(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0155_merge_20190115_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(populate_fileversion_name, noop)

    ]
