# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0154_merge_20190115_1630'),
        ('osf', '0155_merge_20190115_1437'),
    ]

    operations = [
    ]
