# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-08 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0156_add_education_employment_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osfuser',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='osfuser',
            name='schools',
        ),
    ]
