# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-31 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0158_fix_fork_last_logged'),
        ('osf', '0156_auto_20190306_1648'),
    ]

    operations = [
    ]
