# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 15:52
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0158_osfgroup_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfuser',
            name='group_connected_email_records',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='member_added_email_records',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder),
        ),
    ]
