# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0159_merge_20190331_2301'),
        ('osf', '0156_abstractnode_article_doi'),
    ]

    operations = [
    ]
