# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0157_pagecounter_index'),
        ('osf', '0160_merge_20190408_1618'),
    ]

    operations = [
    ]
