# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 02:05
from __future__ import unicode_literals

from django.db import migrations

"""
PREPRINT MIGRATION (we were already using guardian for preprints, but weren't using direct foreign keys)
1) For each guardian GroupObjectPermission table entry that is related to a preprint, add entry to the
PreprintGroupObjectPermission table
"""

# Forward migration - moving preprints to dfks
migrate_preprints_to_dfk_table = [
    """
    INSERT INTO osf_preprintgroupobjectpermission (content_object_id, group_id, permission_id)
    SELECT CAST(GO.object_pk AS INT), CAST(GO.group_id AS INT), CAST(GO.permission_id AS INT)
    FROM guardian_groupobjectpermission GO, django_content_type CT
    WHERE CT.model = 'preprint' AND ct.app_label = 'osf'
    AND GO.content_type_id = CT.id;
    """
]

reverse_migrate_preprints = [
    """
    -- Reverse migration - dropping PreprintGroupObject permission table
    DELETE FROM osf_preprintgroupobjectpermission;
    """
]

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0160_add_guardian_to_nodes'),
    ]

    operations = [
        migrations.RunSQL(migrate_preprints_to_dfk_table, reverse_migrate_preprints)
    ]
