# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 02:05
from __future__ import unicode_literals
from django.db import migrations, connection


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0162_post_migrate'),
    ]

    operations = [
    ]
