# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-29 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0160_merge_20190408_1618'),
        ('osf', '0165_osfgroup'),
    ]

    operations = [
    ]
