# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-10 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0161_add_spam_fields_to_user'),
        ('osf', '0167_auto_20190506_1556'),
    ]

    operations = [
    ]
