# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-17 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0168_merge_20190610_2308'),
        ('osf', '0139_merge_20190517_0633'),
    ]

    operations = [
    ]
