# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-18 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0163_populate_conference_submissions'),
        ('osf', '0168_merge_20190610_2308'),
    ]

    operations = [
    ]
