# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-07 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0145_auto_20190710_0451'),
        ('osf', '0169_merge_20190717_0831'),
    ]

    operations = [
    ]
