# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 15:44
from __future__ import unicode_literals

from scripts.repoint_quickfiles_pagecounters import rekey_pagecounters, noop
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0169_auto_20190614_1429'),
    ]

    operations = [
        migrations.RunPython(rekey_pagecounters, noop)
    ]
