# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-15 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0170_merge_20190807_0515'),
        ('osf', '0139_merge_20190621_0820'),
    ]

    operations = [
    ]
