# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-27 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0141_mapsync'),
        ('osf', '0170_merge_20190807_0515'),
    ]

    operations = [
    ]
