# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-11 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0171_add_registration_files_count'),
    ]

    operations = []
