# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-17 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0171_merge_20190815_0233'),
        ('osf', '0171_merge_20190827_1908'),
    ]

    operations = [
    ]
