# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-17 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0172_merge_20191017_0244'),
        ('osf', '0146_merge_20190726_0906'),
    ]

    operations = [
    ]
