# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-15 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0173_merge_20191017_0916'),
        ('osf', '0172_userextendeddata'),
    ]

    operations = [
    ]
