# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-28 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0174_merge_20191115_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxBusinessFileNode',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('osf.basefilenode',),
        ),
        migrations.AlterField(
            model_name='basefilenode',
            name='type',
            field=models.CharField(choices=[('osf.trashedfilenode', 'trashed file node'), ('osf.trashedfile', 'trashed file'), ('osf.trashedfolder', 'trashed folder'), ('osf.osfstoragefilenode', 'osf storage file node'), ('osf.osfstoragefile', 'osf storage file'), ('osf.osfstoragefolder', 'osf storage folder'), ('osf.bitbucketfilenode', 'bitbucket file node'), ('osf.bitbucketfolder', 'bitbucket folder'), ('osf.bitbucketfile', 'bitbucket file'), ('osf.boxfilenode', 'box file node'), ('osf.boxfolder', 'box folder'), ('osf.boxfile', 'box file'), ('osf.dataversefilenode', 'dataverse file node'), ('osf.dataversefolder', 'dataverse folder'), ('osf.dataversefile', 'dataverse file'), ('osf.dropboxfilenode', 'dropbox file node'), ('osf.dropboxfolder', 'dropbox folder'), ('osf.dropboxfile', 'dropbox file'), ('osf.figsharefilenode', 'figshare file node'), ('osf.figsharefolder', 'figshare folder'), ('osf.figsharefile', 'figshare file'), ('osf.githubfilenode', 'github file node'), ('osf.githubfolder', 'github folder'), ('osf.githubfile', 'github file'), ('osf.gitlabfilenode', 'git lab file node'), ('osf.gitlabfolder', 'git lab folder'), ('osf.gitlabfile', 'git lab file'), ('osf.googledrivefilenode', 'google drive file node'), ('osf.googledrivefolder', 'google drive folder'), ('osf.googledrivefile', 'google drive file'), ('osf.onedrivefilenode', 'one drive file node'), ('osf.onedrivefolder', 'one drive folder'), ('osf.onedrivefile', 'one drive file'), ('osf.owncloudfilenode', 'owncloud file node'), ('osf.owncloudfolder', 'owncloud folder'), ('osf.owncloudfile', 'owncloud file'), ('osf.s3filenode', 's3 file node'), ('osf.s3folder', 's3 folder'), ('osf.s3file', 's3 file'), ('osf.swiftfilenode', 'swift file node'), ('osf.swiftfolder', 'swift folder'), ('osf.swiftfile', 'swift file'), ('osf.azureblobstoragefilenode', 'azure blob storage file node'), ('osf.azureblobstoragefolder', 'azure blob storage folder'), ('osf.azureblobstoragefile', 'azure blob storage file'), ('osf.wekofilenode', 'weko file node'), ('osf.wekofolder', 'weko folder'), ('osf.wekofile', 'weko file'), ('osf.iqbrimsfilenode', 'iqbrims file node'), ('osf.iqbrimsfolder', 'iqbrims folder'), ('osf.iqbrimsfile', 'iqbrims file'), ('osf.dropboxbusinessfilenode', 'dropbox business file node'), ('osf.dropboxbusinessfolder', 'dropbox business folder'), ('osf.dropboxbusinessfile', 'dropbox business file'), ('osf.s3compatfilenode', 's3 compat file node'), ('osf.s3compatfolder', 's3 compat folder'), ('osf.s3compatfile', 's3 compat file'), ('osf.nextcloudfilenode', 'nextcloud file node'), ('osf.nextcloudfolder', 'nextcloud folder'), ('osf.nextcloudfile', 'nextcloud file')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rdmaddonnoinstitutionoption',
            name='management_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_rdm_addon_no_institution_option_set', to='osf.AbstractNode'),
        ),
        migrations.AlterField(
            model_name='rdmaddonnoinstitutionoption',
            name='organizational_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizational_rdm_addon_no_institution_option_set', to='osf.AbstractNode'),
        ),
        migrations.AlterField(
            model_name='rdmaddonoption',
            name='management_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_rdm_addon_option_set', to='osf.AbstractNode'),
        ),
        migrations.AlterField(
            model_name='rdmaddonoption',
            name='organizational_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizational_rdm_addon_option_set', to='osf.AbstractNode'),
        ),
        migrations.CreateModel(
            name='DropboxBusinessFile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('osf.dropboxbusinessfilenode', models.Model),
        ),
        migrations.CreateModel(
            name='DropboxBusinessFolder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('osf.dropboxbusinessfilenode', models.Model),
        ),
    ]
