# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0178_apioauth2scope_is_public'),
    ]

    # AlterField migration added to set null=True because when reverting 0171_finalize_token_scopes_mig,
    # scopes will be renamed to scopes_temp, and a scopes field will be restored.  That scopes
    # field would be empty until this migration was run, but null needs to be True to all this.
    operations = [
        migrations.AlterField(
            model_name='apioauth2personaltoken',
            name='scopes',
            field=models.CharField(blank=False, null=True, max_length=300)
        ),

        migrations.AddField(
            model_name='apioauth2personaltoken',
            name='scopes_temp',
            field=models.ManyToManyField(related_name='tokens', to='osf.ApiOAuth2Scope'),
        ),
    ]
