# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0179_apioauth2personaltoken_scopes_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apioauth2personaltoken',
            name='scopes',
        ),
        migrations.RenameField(
            model_name='apioauth2personaltoken',
            old_name='scopes_temp',
            new_name='scopes',
        ),
    ]
