# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0180_finalize_token_scopes_mig'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfuser',
            name='contacted_deactivation',
            field=models.BooleanField(default=False),
        ),
    ]
