# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 17:18
from __future__ import unicode_literals

import logging

from django.db import migrations

from osf.management.commands.migrate_deleted_date import populate_deleted
from website.settings import DEBUG_MODE

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0181_deleted_field_mig'),
    ]

    if DEBUG_MODE:
        operations = [
            populate_deleted(dry_run=False, page_size=100000)
        ]
    else:
        operations = []
        logger.info(
            'The automatic migration only runs in DEBUG_MODE. Use management command migrate_deleted_date instead'
        )
