# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-03 17:52
from __future__ import unicode_literals

import logging

from django.db import migrations, connection

logger = logging.getLogger(__file__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0182_add_custom_file_versions_through'),
    ]

    operations = [
    ]
