# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-23 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0185_basefilenode_versions'),
        ('osf', '0183_remove_old_jobs_and_schools'),
    ]

    operations = [
    ]
