# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 17:18
from __future__ import unicode_literals

import logging

from django.db import migrations

from osf.management.commands.migrate_deleted_date import (
    FORWARD_BASE_FILE,
    FORWARD_ABSTRACT_NODE,
    FORWARD_COMMENT,
    FORWARD_INSTITUTION,
    FORWARD_PRIVATE_LINK,
    REVERSE_BASE_FILE,
    REVERSE_ABSTRACT_NODE,
    REVERSE_COMMENT,
    REVERSE_INSTITUTION,
    REVERSE_PRIVATE_LINK,
)
from website.settings import DEBUG_MODE

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0188_deleted_field_mig'),
    ]

    if DEBUG_MODE:
        operations = [
            migrations.RunSQL(FORWARD_BASE_FILE, REVERSE_BASE_FILE),
            migrations.RunSQL(FORWARD_INSTITUTION, REVERSE_INSTITUTION),
            migrations.RunSQL(FORWARD_ABSTRACT_NODE, REVERSE_ABSTRACT_NODE),
            migrations.RunSQL(FORWARD_PRIVATE_LINK, REVERSE_PRIVATE_LINK),
            migrations.RunSQL(FORWARD_COMMENT, REVERSE_COMMENT)
        ]
    else:
        operations = []
        logger.info(
            'The automatic migration only runs in DEBUG_MODE. Use management command migrate_deleted_date instead'
        )
