# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-18 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0189_deleted_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='external_registration',
            field=models.NullBooleanField(default=False),
        ),
    ]
