# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0189_deleted_field_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractprovider',
            name='reviews_workflow',
            field=models.CharField(blank=True, choices=[('post-moderation', b'Post-Moderation'), ('pre-moderation', b'Pre-Moderation')], max_length=15, null=True),
        ),
    ]
