# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0191_abstractnode_external_registered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractnode',
            name='external_registered_date',
        ),
        migrations.AddField(
            model_name='abstractnode',
            name='external_registration',
            field=models.NullBooleanField(default=False),
        ),
    ]
