# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-21 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0189_deleted_field_data'),
        ('osf', '0191_migrate_registered_meta'),
    ]

    operations = [
    ]
