# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-15 18:42
from __future__ import unicode_literals

import logging

from django.db import migrations
from osf.management.commands.migrate_registration_responses import (
    migrate_draft_registrations,
    migrate_registrations
)
from website.settings import DEBUG_MODE

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0192_add_registation_responses_fields'),
    ]

    operations = []
