# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-13 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0191_abstractnode_external_registered_date'),
        ('osf', '0193_migrate_registered_meta'),
    ]

    operations = [
    ]
