# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-23 14:26
from __future__ import unicode_literals
from django.db import migrations

from osf import features
from osf.utils.migrations import AddWaffleFlags, DeleteWaffleSwitches

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0197_add_ab_testing_home_page_hero_text_version_b_flag'),
    ]

    operations = [
        AddWaffleFlags([features.EGAP_ADMINS], on_for_everyone=None),
        DeleteWaffleSwitches(['enable_inactive_schemas'])
    ]
