# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-29 21:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models

from osf.features import SLOAN_STUDY_DATA
from osf.utils.migrations import AddWaffleSwitches


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0197_add_ab_testing_home_page_hero_text_version_b_flag'),
    ]

    operations = [
        AddWaffleSwitches([SLOAN_STUDY_DATA], active=False),
        migrations.AddField(
            model_name='preprint',
            name='data_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='preprint',
            name='has_data_links',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='preprint',
            name='why_no_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
