# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-31 21:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
from osf.utils.migrations import AddWaffleSwitches
from osf.features import SLOAN_STUDY_PREREG

class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0197_add_ab_testing_home_page_hero_text_version_b_flag'),
    ]

    operations = [
        AddWaffleSwitches([SLOAN_STUDY_PREREG], active=False),
        migrations.AddField(
            model_name='preprint',
            name='has_prereg_links',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='preprint',
            name='prereg_link_explanations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='preprint',
            name='prereg_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='preprint',
            name='why_no_prereg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
