# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0202_add_sloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprint',
            name='has_data_links',
            field=models.TextField(blank=True, choices=[('available', 'Available'), ('no', 'No'), ('not_applicable', 'Not applicable')], null=True),
        ),
        migrations.AlterField(
            model_name='preprint',
            name='has_prereg_links',
            field=models.TextField(blank=True, choices=[('available', 'Available'), ('no', 'No'), ('not_applicable', 'Not applicable')], null=True),
        ),
    ]
