# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-23 14:26
from __future__ import unicode_literals
from django.db import migrations

from osf import features
from osf.utils.migrations import DeleteWaffleFlags


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0204_ensure_schemas'),
    ]

    operations = [
        DeleteWaffleFlags([features.OSF_PREREGISTRATION]),
    ]
