# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-20 18:32
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0204_ensure_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hero_logo_image', models.URLField()),
                ('topnav_logo_image', models.URLField()),
                ('hero_background_image', models.URLField()),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AddField(
            model_name='abstractprovider',
            name='advertises_on_discovery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='abstractprovider',
            name='branded_discovery_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='abstractprovider',
            name='has_landing_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstractprovider',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='osf.Brand'),
        ),
    ]
