# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0205_auto_20200323_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='chronos_enabled',
            field=models.NullBooleanField(default=False),
        ),
    ]
