# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0208_update_EGAP_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='auto_check_spam',
            field=models.BooleanField(default=True),
        ),
    ]
