# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0211_auto_20200709_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationschema',
            name='provider',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemas', to='osf.RegistrationProvider'),
        ),
    ]
