# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-10 17:34
from __future__ import unicode_literals

from django.db import migrations

from osf.models import RegistrationProvider


def add_provider(state, *args, **kwargs):
    provider, created = RegistrationProvider.objects.get_or_create(**RegistrationProvider.default)
    provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0211_auto_20200709_1320'),
    ]

    operations = [
        migrations.RunPython(add_provider, migrations.RunPython.noop),
    ]
