# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-12 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0212_merge_20200912_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstoragetype',
            name='storage_type',
            field=models.IntegerField(choices=[(1, 'NII Storage'), (2, 'Custom Storage')], default=1),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='storage_type',
            field=models.IntegerField(choices=[(1, 'NII Storage'), (2, 'Custom Storage')], default=1),
        ),
    ]
