# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import osf.models.registrations


class Migration(migrations.Migration):

    # This migration must run after all fields are added to AbstractProvider
    dependencies = [
        ('osf', '0228_auto_20210317_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftregistration',
            name='provider',
            field=models.ForeignKey(default=osf.models.registrations.get_default_id, on_delete=django.db.models.deletion.CASCADE, related_name='draft_registrations', to='osf.RegistrationProvider'),
        ),
    ]
