# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-12 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0178_auto_20210302_0148'),
        ('osf', '0213_auto_20200912_2258'),
    ]

    operations = [
    ]
