# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    # 0213 now depends on 0228, so this is a skip-level dependency
    dependencies = [
        ('osf', '0212_registrationschema_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractprovider',
            name='share_publish_type',
            field=models.CharField(choices=[('Preprint', 'Preprint'), ('Thesis', 'Thesis'), ('Registration', 'Registration')], default='Thesis', help_text='This SHARE type will be used when pushing publications to SHARE', max_length=32),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='share_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='abstractprovider',
            name='share_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
