# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-10-01 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0214_merge_20210312_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractnode',
            name='comment_level',
            field=models.CharField(default='private', max_length=10),
        ),
        migrations.RunSQL(
            [
                """
                UPDATE osf_abstractnode SET comment_level = 'private';
                """
            ],
            migrations.RunSQL.noop
        ),
    ]
