# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0215_auto_20200819_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='custom_storage_usage_limit_private',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='abstractnode',
            name='custom_storage_usage_limit_public',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=100, null=True),
        ),
    ]
