# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-02-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0218_ensure_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfuser',
            name='erad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='family_name_ja',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='given_name_ja',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='middle_names_ja',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
