# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-02-10 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0216_merge_20211009_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfuser',
            name='erad',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='family_name_end',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='given_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='middle_names_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
