# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0217_auto_20200901_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
