# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-02 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0217_institution_entitlement'),
        ('osf', '0217_osfuser_temp_account'),
    ]

    operations = [
    ]
