# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-04-28 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0217_osfuser_temp_account'),
        ('osf', '0217_institution_entitlement'),
        ('osf', '0217_add_fields_to_osfuser'),
    ]

    operations = [
    ]
