# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-03 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0218_merge_20220428_0616'),
        ('osf', '0218_merge_20220502_0236'),
    ]

    operations = [
    ]
