# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-10 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0219_merge_20220503_1236'),
        ('osf', '0218_merge_20220506_0441'),
    ]

    operations = [
    ]
