# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0221_add_schemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftregistration',
            name='date_last_transitioned',
        ),
        migrations.RemoveField(
            model_name='draftregistration',
            name='machine_state',
        ),
        migrations.AddField(
            model_name='abstractnode',
            name='moderation_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('initial', 'Initial'), ('reverted', 'Reverted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('embargo', 'Embargo'), ('pending_embargo_termination', 'PendingEmbargoTermination'), ('pending_withdraw_request', 'PendingWithdrawRequest'), ('pending_withdraw', 'PendingWithdraw'), ('withdrawn', 'Withdrawn')], default='initial', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='draftregistrationapproval',
            name='sanction_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('pending_admin_approval', 'PendingAdminApproval'), ('pending_moderator_approval', 'PendingModeratorApproval'), ('accepted', 'Accepted'), ('admin_rejected', 'AdminRejected'), ('moderator_rejected', 'ModeratorRejected'), ('complete', 'Complete')], default='pending_admin_approval', max_length=30),
        ),
        migrations.AddField(
            model_name='embargo',
            name='sanction_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('pending_admin_approval', 'PendingAdminApproval'), ('pending_moderator_approval', 'PendingModeratorApproval'), ('accepted', 'Accepted'), ('admin_rejected', 'AdminRejected'), ('moderator_rejected', 'ModeratorRejected'), ('complete', 'Complete')], default='pending_admin_approval', max_length=30),
        ),
        migrations.AddField(
            model_name='embargoterminationapproval',
            name='sanction_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('pending_admin_approval', 'PendingAdminApproval'), ('pending_moderator_approval', 'PendingModeratorApproval'), ('accepted', 'Accepted'), ('admin_rejected', 'AdminRejected'), ('moderator_rejected', 'ModeratorRejected'), ('complete', 'Complete')], default='pending_admin_approval', max_length=30),
        ),
        migrations.AddField(
            model_name='registrationapproval',
            name='sanction_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('pending_admin_approval', 'PendingAdminApproval'), ('pending_moderator_approval', 'PendingModeratorApproval'), ('accepted', 'Accepted'), ('admin_rejected', 'AdminRejected'), ('moderator_rejected', 'ModeratorRejected'), ('complete', 'Complete')], default='pending_admin_approval', max_length=30),
        ),
        migrations.AddField(
            model_name='retraction',
            name='sanction_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('pending_admin_approval', 'PendingAdminApproval'), ('pending_moderator_approval', 'PendingModeratorApproval'), ('accepted', 'Accepted'), ('admin_rejected', 'AdminRejected'), ('moderator_rejected', 'ModeratorRejected'), ('complete', 'Complete')], default='pending_admin_approval', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationaction',
            name='from_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('initial', 'Initial'), ('reverted', 'Reverted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('embargo', 'Embargo'), ('pending_embargo_termination', 'PendingEmbargoTermination'), ('pending_withdraw_request', 'PendingWithdrawRequest'), ('pending_withdraw', 'PendingWithdraw'), ('withdrawn', 'Withdrawn')], max_length=31),
        ),
        migrations.AlterField(
            model_name='registrationaction',
            name='to_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('initial', 'Initial'), ('reverted', 'Reverted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('embargo', 'Embargo'), ('pending_embargo_termination', 'PendingEmbargoTermination'), ('pending_withdraw_request', 'PendingWithdrawRequest'), ('pending_withdraw', 'PendingWithdraw'), ('withdrawn', 'Withdrawn')], max_length=31),
        ),
        migrations.AlterField(
            model_name='registrationaction',
            name='trigger',
            field=models.CharField(choices=[('submit', 'Submit'), ('accept_submission', 'AcceptSubmission'), ('reject_submission', 'RejectSubmission'), ('request_withdrawal', 'RequestWithdrawal'), ('accept_withdrawal', 'AcceptWithdrawal'), ('reject_withdrawal', 'RejectWithdrawal'), ('force_withdraw', 'ForceWithdraw')], max_length=31),
        ),
    ]
