# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-13 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.models.export_data
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0006_rename_deleted_field'),
        ('osf', '0223_ensure_schema_and_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('process_start', osf.models.export_data.SecondDateTimeField(auto_now_add=True)),
                ('process_end', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Stopping', 'Stopping'), ('Checking', 'Checking'), ('Stopped', 'Stopped'), ('Completed', 'Completed'), ('Error', 'Error')], max_length=255)),
                ('export_file', models.CharField(blank=True, max_length=255, null=True)),
                ('project_number', models.PositiveIntegerField(default=0)),
                ('file_number', models.PositiveIntegerField(default=0)),
                ('total_size', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'osf_export_data',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='ExportDataLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('institution_guid', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('waterbutler_credentials', osf.utils.fields.EncryptedJSONField(default=dict)),
                ('waterbutler_url', models.URLField(default='http://localhost:7777')),
                ('mfr_url', models.URLField(default='http://localhost:7778')),
                ('waterbutler_settings', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
            ],
            options={
                'db_table': 'osf_export_data_location',
                'ordering': ['pk'],
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='ExportDataRestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('process_start', osf.models.export_data.SecondDateTimeField(auto_now_add=True)),
                ('process_end', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Stopping', 'Stopping'), ('Checking', 'Checking'), ('Stopped', 'Stopped'), ('Completed', 'Completed'), ('Error', 'Error')], max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.ExportData')),
            ],
            options={
                'db_table': 'osf_export_data_restore',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AlterUniqueTogether(
            name='exportdatalocation',
            unique_together=set([('institution_guid', 'name')]),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.ExportDataLocation'),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='exportdatarestore',
            unique_together=set([('export', 'destination', 'process_start')]),
        ),
        migrations.AlterUniqueTogether(
            name='exportdata',
            unique_together=set([('source', 'location', 'process_start')]),
        ),
    ]
