# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-01-30 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0224_auto_20220913_0447'),
        ('osf', '0224_ensure_schema_and_reports'),
    ]

    operations = [
    ]
