# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-03-29 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0225_add_pattern_and_norm_to_registration_schema_block'),
        ('osf', '0225_merge_20230130_1127'),
    ]

    operations = [
    ]
