# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-17 14:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0225_auto_20201119_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='IA_url',
            field=models.URLField(blank=True, help_text='Where the archive.org data for the registration is stored', null=True),
        ),
    ]
