# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0226_auto_20210224_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='branched_from_node',
            field=models.NullBooleanField(),
        ),
    ]
