# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0227_auto_20230406_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportdata',
            name='total_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
