# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import osf.utils.datetime_aware_jsonfield
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0228_auto_20230601_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportdata',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='source_waterbutler_credentials',
            field=osf.utils.fields.EncryptedJSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='source_waterbutler_settings',
            field=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default=dict, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, null=True),
        ),
    ]
