# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-11 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0228_abstractnode_branched_from_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractnode',
            name='ia_url',
            field=models.URLField(blank=True, help_text='Where the archive.org data for the registration is stored', null=True),
        ),
    ]
