# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0229_auto_20210317_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='default_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_schema', to='osf.RegistrationSchema'),
        ),
    ]
