# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-07-13 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0228_ensure_schema_and_reports'),
        ('osf', '0230_update_source_name'),
    ]

    operations = [
    ]
