# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-10 18:12
from __future__ import unicode_literals

from django.db import migrations
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0231_abstractprovider_default_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='deactivated',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
    ]
