# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-08 18:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0232_abstractnode_ia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='school_type_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='collection',
            name='study_design_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='collectionsubmission',
            name='school_type',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='collectionsubmission',
            name='study_design',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
