# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-06-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0232_auto_20210614_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationschemablock',
            name='registration_response_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
