# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-06-04 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0233_ensure_schema_and_reports'),
        ('osf', '0233_update_storage_region'),
    ]

    operations = [
    ]
