# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-18 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0235_auto_20210818_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaresponse',
            name='pending_approvers',
            field=models.ManyToManyField(related_name='pending_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemaresponse',
            name='reviews_state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress')], default='in_progress', max_length=255),
        ),
        migrations.AlterField(
            model_name='draftregistrationapproval',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='embargo',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='embargoterminationapproval',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationapproval',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress')], default='unapproved', max_length=255),
        ),
        migrations.AlterField(
            model_name='retraction',
            name='state',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('unapproved', 'Unapproved'), ('pending_moderation', 'PendingModeration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('moderator_rejected', 'ModeratorRejected'), ('completed', 'Completed'), ('in_progress', 'InProgress')], default='unapproved', max_length=255),
        ),
    ]
