# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-08-20 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0214_auto_20200701_1658'),
        ('osf', '0235_ensure_schema_and_reports'),
    ]

    operations = [
    ]
