# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-18 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0235_auto_20210818_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemaresponses',
            old_name='schema_responses',
            new_name='response_blocks',
        ),
    ]
