# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-09-07 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0236_add_columns_to_registration_schema_block'),
        ('osf', '0236_merge_20240820_0820'),
    ]

    operations = [
    ]
