# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-09-08 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0237_merge_20240907_0019'),
        ('osf', '0237_ensure_schema_and_mappings'),
    ]

    operations = [
    ]
