# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-10-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0237_auto_20210929_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='allow_updates',
            field=models.NullBooleanField(default=False),
        ),
    ]
