# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-11-11 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0238_auto_20240924_0331'),
        ('osf', '0238_merge_20240908_2053'),
    ]

    operations = [
    ]
