# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-08-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0238_abstractprovider_allow_updates'),
    ]

    operations = [
        migrations.RenameModel('BlacklistedEmailDomain', 'NotableEmailDomain'),
        migrations.AddField(
            model_name='notableemaildomain',
            name='note',
            field=models.IntegerField(choices=[(0, 'EXCLUDE_FROM_ACCOUNT_CREATION'), (1, 'ASSUME_HAM_UNTIL_REPORTED')], default=0),
        ),
    ]
