# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0238_abstractprovider_allow_updates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schemaresponse',
            index=models.Index(fields=['object_id', 'content_type'], name='osf_schemar_object__8cc95e_idx'),
        ),
    ]
