# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-09-24 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0238_merge_20240908_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquota',
            unique_together=set([('user', 'storage_type')]),
        ),
    ]
