# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-10 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0239_auto_20211110_1921'),
        ('osf', '0239_notable_email_domains'),
    ]

    operations = [
    ]
