# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-11-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0240_ensure_schema_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLimitNumberDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_limit_number_default', to='osf.Institution')),
                ('project_limit_number', models.IntegerField()),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'db_table': 'osf_project_limit_number_default',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='ProjectLimitNumberTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('is_availability', models.BooleanField(default=True)),
                ('used_setting_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'db_table': 'osf_project_limit_number_template',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='ProjectLimitNumberTemplateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='osf.ProjectLimitNumberTemplate')),
                ('attribute_name', models.CharField(max_length=255)),
                ('setting_type', models.IntegerField(choices=[(1, 'free_value_all_match'), (2, 'free_value_left_suffix_match'), (3, 'fixed_value_all_match'), (4, 'fixed_value_left_suffix_match'), (5, 'list_value_all_match'), (6, 'list_value_left_suffix_match')])),
                ('attribute_value', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'db_table': 'osf_project_limit_number_template_attribute',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='ProjectLimitNumberSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_limit_number_settings', to='osf.Institution')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='osf.ProjectLimitNumberTemplate')),
                ('name', models.CharField(max_length=255)),
                ('project_limit_number', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField()),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_availability', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'db_table': 'osf_project_limit_number_setting',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='ProjectLimitNumberSettingAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_attributes', to='osf.ProjectLimitNumberTemplateAttribute')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='osf.ProjectLimitNumberSetting')),
                ('attribute_value', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'db_table': 'osf_project_limit_number_setting_attribute',
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
    ]
