# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-11-16 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0239_abstractprovider_allow_bulk_uploads'),
        ('osf', '0240_merge_20211110_2051'),
    ]

    operations = [
    ]
