# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-10-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0240_merge_20211110_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='ror',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
