# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0241_abstractprovider_allow_bulk_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaresponseblock',
            name='source_schema_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='osf.RegistrationSchemaBlock'),
        ),
    ]
