# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-03-20 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0241_ensure_schema_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationschemablock',
            name='auto_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='auto_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='auto_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='concealment_page_navigator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='hide_projectmetadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='multi_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='required_all_check',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='retrieval_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='retrieval_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='retrieval_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='row_addition_caption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registrationschemablock',
            name='sentence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Stopping', 'Stopping'), ('Completed', 'Completed'), ('Checking', 'Checking'), ('Stopped', 'Stopped'), ('Error', 'Error')], max_length=255),
        ),
        migrations.AlterField(
            model_name='exportdatarestore',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Stopping', 'Stopping'), ('Completed', 'Completed'), ('Checking', 'Checking'), ('Stopped', 'Stopped'), ('Error', 'Error')], max_length=255),
        ),
    ]
