# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-07 17:49
from __future__ import unicode_literals

from django.db import migrations
from django.db import utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0241_abstractprovider_allow_bulk_uploads'),
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        try:
            return super().apply(project_state, schema_editor, collect_sql)
        except ValueError as e:
            assert str(e) in (
                "Related model 'osf.FileMetadataSchema' cannot be resolved",
                'Found wrong number (0) of constraints for osf_filemetadatarecord(file_id, schema_id)',
            )
        except utils.ProgrammingError as e:
            assert e.args[0] == 'relation "osf_filemetadataschema" does not exist'

        print('Local environment, skipping...')
        return project_state

    operations = [
        migrations.DeleteModel(name='FileMetadataSchema'),
        migrations.AlterUniqueTogether(
            name='filemetadatarecord',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='filemetadatarecord',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filemetadatarecord',
            name='schema',
        ),
        migrations.DeleteModel(
            name='FileMetadataRecord',
        ),
    ]
