# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-06 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0241_abstractprovider_allow_bulk_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSchemaBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('help_text', models.TextField()),
                ('example_text', models.TextField(null=True)),
                ('response_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('schema_block_group_key', models.CharField(db_index=True, max_length=24, null=True)),
                ('block_type', models.CharField(choices=[('page-heading', 'page-heading'), ('section-heading', 'section-heading'), ('subsection-heading', 'subsection-heading'), ('paragraph', 'paragraph'), ('question-label', 'question-label'), ('short-text-input', 'short-text-input'), ('long-text-input', 'long-text-input'), ('file-input', 'file-input'), ('contributors-input', 'contributors-input'), ('single-select-input', 'single-select-input'), ('multi-select-input', 'multi-select-input'), ('select-input-option', 'select-input-option'), ('select-other-option', 'select-other-option')], db_index=True, max_length=31)),
                ('display_text', models.TextField()),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='FileSchemaResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_responses', to='osf.OsfStorageFile')),
                ('response_blocks', models.ManyToManyField(to='osf.SchemaResponseBlock')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='FileSchemaResponseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('schema_key', models.CharField(max_length=255)),
                ('response', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder, null=True)),
                ('source_schema_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.FileSchemaBlock')),
                ('source_schema_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_response_blocks', to='osf.FileSchemaResponse')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.RenameModel(
            old_name='FileMetadataSchema',
            new_name='FileSchema',
        ),
        migrations.AlterUniqueTogether(
            name='filemetadatarecord',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='filemetadatarecord',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filemetadatarecord',
            name='schema',
        ),
        migrations.DeleteModel(
            name='FileMetadataRecord',
        ),
        migrations.AddField(
            model_name='fileschemaresponse',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.FileSchema'),
        ),
        migrations.AddField(
            model_name='fileschemablock',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_blocks', to='osf.FileSchema'),
        ),
        migrations.AlterUniqueTogether(
            name='fileschemaresponseblock',
            unique_together=set([('source_schema_response', 'source_schema_block')]),
        ),
        migrations.AlterUniqueTogether(
            name='fileschemablock',
            unique_together=set([('schema', 'response_key')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='fileschemablock',
            order_with_respect_to='schema',
        ),
    ]
