# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-03-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models

def remove_if_exist(apps, schema_editor):
    try:
        schema_editor.execute(
            schema_editor.sql_delete_table % {
                'table': schema_editor.quote_name('quickfilesnode')
            }
        )
    except KeyError:
        ## No quickfilesnode to delete all good
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0242_auto_20220125_1604'),
    ]

    operations = [
        migrations.RunPython(remove_if_exist, migrations.RunPython.noop),
        migrations.DeleteModel(name='quickfilesnode'),
        migrations.AlterField(
            model_name='abstractnode',
            name='type',
            field=models.CharField(choices=[('osf.node', 'node'), ('osf.draftnode', 'draft node'), ('osf.registration', 'registration')], db_index=True, max_length=255),
        ),
    ]
