# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-03-25 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0242_auto_20220125_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='orcid_record_verified_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='delegation_protocol',
            field=models.CharField(blank=True, choices=[('saml-shib', 'SAML_SHIBBOLETH'), ('cas-pac4j', 'CAS_PAC4J'), ('oauth-pac4j', 'OAUTH_PAC4J'), ('via-orcid', 'AFFILIATION_VIA_ORCID'), ('', 'NONE')], default='', max_length=15),
        ),
    ]
