# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-25 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0242_auto_20220125_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'permissions': (('mark_spam', 'Can mark comments, projects and registrations as spam'), ('view_spam', 'Can view nodes, comments, and projects marked as spam'), ('view_metrics', 'Can view metrics on the OSF Admin app'), ('view_desk', 'Can view details about Desk users'), ('delete_preprintrequest', 'Can delete preprints withdrawal requests'), ('change_preprintrequest', 'Can update preprints withdrawal requests'))},
        ),
        migrations.RemoveField(
            model_name='abstractprovider',
            name='in_sloan_study',
        ),
        migrations.RemoveField(
            model_name='draftregistration',
            name='approval',
        ),
        migrations.DeleteModel(
            name='DraftRegistrationApproval',
        ),
    ]
