# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0243_auto_20211025_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='identifier_domain',
            field=models.URLField(blank=True, help_text='The full domain this institutions that will appear in DOI metadata.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='ror_uri',
            field=models.URLField(blank=True, help_text='The full URI for the this institutions ROR.', max_length=500, null=True),
        ),
    ]
