# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-07 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0243_auto_20211025_1353'),
        ('osf', '0243_auto_20220325_0504'),
    ]

    operations = [
    ]
