# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-04-23 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0242_auto_20241113_1058'),
        ('osf', '0245_ensure_schema'),
    ]

    operations = [
    ]
