# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0246_add_outcomes_and_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomeartifact',
            name='deleted',
            field=osf.utils.fields.NonNaiveDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcomeartifact',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outcomeartifact',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='outcomeartifact',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='outcomeartifact',
            name='artifact_type',
            field=models.IntegerField(choices=[(0, 'UNDEFINED'), (1, 'DATA'), (11, 'ANALYTIC_CODE'), (21, 'MATERIALS'), (31, 'PAPERS'), (41, 'SUPPLEMENTS'), (1001, 'PRIMARY')], default=osf.utils.outcomes.ArtifactTypes(0)),
        ),
    ]
