# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0248_artifact_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaresponse',
            name='revision_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
