# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-04-24 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0246_merge_20250423_0331'),
        ('osf', '0249_ensure_schema_mappings'),
    ]

    operations = [
    ]
