# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.models.notable_domain


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0250_auto_20220915_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('referent_object_id', models.PositiveIntegerField()),
                ('is_triaged', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AlterField(
            model_name='notabledomain',
            name='note',
            field=models.IntegerField(choices=[(0, 'EXCLUDE_FROM_ACCOUNT_CREATION_AND_CONTENT'), (1, 'ASSUME_HAM_UNTIL_REPORTED'), (2, 'UNKOWN'), (3, 'IGNORED')], default=osf.models.notable_domain.Note(0)),
        ),
        migrations.AddField(
            model_name='domainreference',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.NotableDomain'),
        ),
        migrations.AddField(
            model_name='domainreference',
            name='referent_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
