# Generated by Django 3.2.15 on 2022-10-24 14:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('osf', '0004_django3_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('referrer_object_id', models.PositiveIntegerField()),
                ('is_triaged', models.BooleanField(default=False)),
            ],
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AddField(
            model_name='domainreference',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.notableemaildomain'),
        ),
        migrations.AddField(
            model_name='domainreference',
            name='referrer_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='domainreference',
            unique_together={('referrer_object_id', 'domain')},
        ),
        migrations.RenameModel(
            old_name='NotableEmailDomain',
            new_name='NotableDomain',
        ),
        migrations.AlterField(
            model_name='domainreference',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osf.notabledomain'),
        ),
        migrations.AlterField(
            model_name='notabledomain',
            name='note',
            field=models.IntegerField(
                choices=[(0, 'EXCLUDE_FROM_ACCOUNT_CREATION_AND_CONTENT'), (1, 'ASSUME_HAM_UNTIL_REPORTED'),
                         (2, 'UNKNOWN'), (3, 'IGNORED')],
                default=osf.models.notable_domain.NotableDomain.Note['UNKNOWN']),
        ),

    ]
