# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'sales_analytics', '0001_initial'), (b'sales_analytics', '0002_auto_20160512_1015')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('tag', models.TextField()),
                ('count', models.IntegerField()),
                ('percent', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usercount',
            unique_together=set([('date', 'tag')]),
        ),
    ]
