# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analytics', '0002_auto_20160512_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmetrics',
            name='timespan',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='dbmetrics',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 18)),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 18)),
        ),
        migrations.AlterUniqueTogether(
            name='dbmetrics',
            unique_together=set([('date', 'name', 'timespan')]),
        ),
    ]
