# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_owncloud', '0003_add_trailing_slash_back_to_implict_folders'),
        ('addons_owncloud', '0003_auto_20170713_1125'),
    ]

    operations = [
    ]
