# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-04-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_onedrivebusiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='drive_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
