# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osf', '0001_initial'),
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxusersettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boxnodesettings',
            name='external_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf_models.ExternalAccount'),
        ),
        migrations.AddField(
            model_name='boxnodesettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf_models.AbstractNode'),
        ),
        migrations.AddField(
            model_name='boxnodesettings',
            name='user_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.BoxUserSettings'),
        ),
    ]
