# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesettings',
            name='folder_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
