# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0009_osfuser_verification_key_v2'),
        ('addons_osfstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='root_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.StoredFileNode'),
        ),
    ]
