# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models
from website.settings import MFR_SERVER_URL


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0004_storage_region_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='mfr_url',
            field=models.URLField(default=MFR_SERVER_URL),
        ),
    ]
