# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-01 15:45
from __future__ import unicode_literals

from django.db import migrations

from osf.models import QuickFolder
from osf.quickfiles.migration_utils import create_quickfolders, migrate_quickfiles_to_quickfolders

import logging
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


def migrate_to_quickfolders(*args, **kwargs):
    create_quickfolders()
    migrate_quickfiles_to_quickfolders()


def remove_quickfolders(*args, **kwargs):
    QuickFolder.objects.all().delete()


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_to_quickfolders, remove_quickfolders),
        migrations.RunSQL(
            [
                """
                CREATE UNIQUE INDEX one_quickfolder_per_user ON osf_basefilenode (target_object_id, type)
                WHERE type='osf.quickfolder';
                """
            ], [
                """
                DROP INDEX IF EXISTS one_quickfolder_per_user RESTRICT;
                """
            ]
        ),

    ]
