ENABLE_INACTIVE_SCHEMAS = 'enable_inactive_schemas'
OSF_PREREGISTRATION = 'osf_preregistration'
DISABLE_ENGAGEMENT_EMAILS = 'disable_engagement_emails'
ELASTICSEARCH_METRICS = 'elasticsearch_metrics'
ENFORCE_CSRF = 'enforce_csrf'
