# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 16:40
from __future__ import unicode_literals

import addons.wiki.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import osf.models.base
import osf.utils.fields


class Migration(migrations.Migration):

    replaces = [(b'addons_wiki', '0001_initial'), (b'addons_wiki', '0002_auto_20161019_1116'), (b'addons_wiki', '0003_auto_20170119_0944'), (b'addons_wiki', '0004_auto_20170227_1354')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osf', '0007_auto_20161014_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, default=osf.models.base.generate_object_id, max_length=24, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_publicly_editable', models.BooleanField(db_index=True, default=False)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_wiki_node_settings', to='osf.AbstractNode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeWikiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_string', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('content_type_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('page_name', models.CharField(max_length=200, validators=[addons.wiki.models.validate_page_name])),
                ('version', models.IntegerField(default=1)),
                ('date', osf.utils.fields.NonNaiveDateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default=b'')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osf.AbstractNode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
