# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_wiki_node_settings', to='osf.AbstractNode'),
        ),
        migrations.AlterField(
            model_name='nodewikipage',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
