# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-23 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addons_wiki', '0001_initial'),
        ('osf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiversion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wikiversion',
            name='wiki_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='addons_wiki.WikiPage'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wikis', to='osf.AbstractNode'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons_wiki_node_settings', to='osf.AbstractNode'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['page_name', 'node'], name='addons_wiki_page_na_6d5d96_idx'),
        ),
    ]
