# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 23:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0002_auto_20161019_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodewikipage',
            name='discourse_post_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nodewikipage',
            name='discourse_topic_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodewikipage',
            name='discourse_topic_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nodewikipage',
            name='discourse_topic_parent_guids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=b''), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='nodewikipage',
            name='discourse_topic_title',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
