# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 15:44
from __future__ import unicode_literals

import addons.wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0002_auto_20161019_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodewikipage',
            name='page_name',
            field=models.CharField(max_length=200, validators=[addons.wiki.models.validate_page_name]),
        ),
    ]
