# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0003_auto_20170113_1732'),
        ('addons_wiki', '0004_auto_20170227_1354'),
    ]

    operations = [
    ]
