# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0004_auto_20170227_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodesettings',
            options={'ordering': ['id']},
        ),
    ]
