# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 20:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0006_wikipage_wikiversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodewikipage',
            name='former_guid',
            field=models.CharField(blank=True, max_length=100, null=True, db_index=True),
        ),
    ]
