# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 20:16
from __future__ import unicode_literals
import progressbar
from django.db import migrations
from bulk_update.helper import bulk_update
from django.contrib.contenttypes.models import ContentType

def reverse_func(state, schema):
    NodeWikiPage = state.get_model('addons_wiki', 'nodewikipage')
    NodeWikiPage.objects.all().update(former_guid='')

def add_guid_field(state, schema):
    """
    Store guid on NodeWikiPage to make the migration from NodeWikiPages => WikiPages/WikiVersions easily reversible.
    """
    NodeWikiPage = state.get_model('addons_wiki', 'nodewikipage')
    Guid = state.get_model('osf', 'guid')
    nwp_content_type = ContentType.objects.get_for_model(NodeWikiPage).id
    bulk_save = []
    all_node_wiki_pages = NodeWikiPage.objects.all()
    progress_bar = progressbar.ProgressBar(maxval=all_node_wiki_pages.count()).start()
    for i, nwp in enumerate(all_node_wiki_pages):
        progress_bar.update(i + 1)
        nwp.former_guid = Guid.objects.get(object_id=nwp.id, content_type_id=nwp_content_type)._id
        bulk_save.append(nwp)
    progress_bar.finish()
    bulk_update(bulk_save, batch_size=1000)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0007_nodewikipage_former_guid'),
    ]

    operations = [
        migrations.RunPython(add_guid_field, reverse_func)
    ]
