# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0008_store_guid_on_nodewikipage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['page_name', 'node'], name='addons_wiki_page_na_6d5d96_idx'),
        ),
    ]
