# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-16 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_wiki', '0014_wikiimporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikiimporttask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wikiimporttask',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Stopped', 'Stopped'), ('Error', 'Error')], default='Running', max_length=255),
        ),
        migrations.AlterField(
            model_name='wikiimporttask',
            name='task_id',
            field=models.CharField(default='Running', max_length=255, unique=True),
        ),
    ]
