# API CAS Login Endpoint errors for 400s and 500s response.
# Must match io.cos.cas.api.util.AbstractApiEndpointUtils in CAS.
# TODO: use database

ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND'
ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED'
ACCOUNT_NOT_CLAIMED = 'ACCOUNT_NOT_CLAIMED'
ACCOUNT_DISABLED = 'ACCOUNT_DISABLED'
EXTERNAL_IDENTITY_CLAIMED = 'EXTERNAL_IDENTITY_CLAIMED'
INVALID_PASSWORD = 'INVALID_PASSWORD'
INVALID_KEY = 'INVALID_VERIFICATION_KEY'
INVALID_TOTP = 'INVALID_TIME_BASED_ONE_TIME_PASSWORD'
INVALID_ACCOUNT_STATUS = 'INVALID_ACCOUNT_STATUS'
TFA_REQUIRED = 'TWO_FACTOR_AUTHENTICATION_REQUIRED'
INVALID_EXTERNAL_IDENTITY = 'INVALID_EXTERNAL_IDENTITY'
