# API CAS Login Endpoint errors for 400s and 500s response.
# Must match io.cos.cas.api.util.AbstractApiEndpointUtils in CAS.

# inactive account status
ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND'
ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED'
ACCOUNT_NOT_CLAIMED = 'ACCOUNT_NOT_CLAIMED'
ACCOUNT_DISABLED = 'ACCOUNT_DISABLED'
ACCOUNT_STATUS_INVALID = 'ACCOUNT_STATUS_INVALID'

# invalid credentials
INVALID_PASSWORD = 'INVALID_PASSWORD'
INVALID_VERIFICATION_KEY = 'INVALID_VERIFICATION_KEY'

# two factor
TWO_FACTOR_AUTHENTICATION_REQUIRED = 'TWO_FACTOR_AUTHENTICATION_REQUIRED'
INVALID_TIME_BASED_ONE_TIME_PASSWORD = 'INVALID_TIME_BASED_ONE_TIME_PASSWORD'

# external identity
EXTERNAL_IDENTITY_CLAIMED = 'EXTERNAL_IDENTITY_CLAIMED'
INVALID_EXTERNAL_IDENTITY = 'INVALID_EXTERNAL_IDENTITY'
